# Generated by Django 5.2.6 on 2025-09-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='carga_horaria',
            field=models.IntegerField(default=40, help_text='Horas semanais'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='curso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_emissao_carteira',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_ultimo_reajuste',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(choices=[('FUND', 'Fundamental'), ('MED', 'Médio'), ('TEC', 'Técnico'), ('SUP', 'Superior'), ('POS', 'Pós-graduação'), ('MES', 'Mestrado'), ('DOU', 'Doutorado')], default='MED', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='experiencia_anterior',
            field=models.TextField(blank=True, help_text='Resumo das experiências profissionais anteriores'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='instituicao_ensino',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero_carteira_trabalho',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='plano_saude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='seguro_vida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='serie_carteira_trabalho',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(choices=[('CLT', 'CLT'), ('TEMP', 'Temporário'), ('EST', 'Estágio'), ('PJ', 'Pessoa Jurídica'), ('AUT', 'Autônomo')], default='CLT', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral'), ('ROTATIVO', 'Rotativo')], default='INTEGRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='vale_alimentacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='vale_transporte',
            field=models.BooleanField(default=False),
        ),
    ]
