# Generated by Django 5.2.6 on 2025-09-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_funcionario_carga_horaria_funcionario_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_emissao_carteira',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='numero_carteira_trabalho',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='pis',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='serie_carteira_trabalho',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='vale_alimentacao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='vale_transporte',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_emissao_dire',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão DIRE'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_validade_dire',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade DIRE'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='dire',
            field=models.CharField(blank=True, help_text='Documento de Identificação e Residência para Estrangeiros', max_length=20, verbose_name='DIRE'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='inss',
            field=models.CharField(blank=True, help_text='Número de Segurança Social', max_length=20, verbose_name='INSS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero_carteira',
            field=models.CharField(blank=True, help_text='Número da carteira conforme emitida pelo Ministério do Trabalho', max_length=20, verbose_name='Número da Carteira de Trabalho'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='subsidio_alimentacao',
            field=models.BooleanField(default=False, verbose_name='Subsídio de Alimentação'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='subsidio_funeral',
            field=models.BooleanField(default=False, verbose_name='Subsídio de Funeral'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='subsidio_risco',
            field=models.BooleanField(default=False, verbose_name='Subsídio de Risco'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='subsidio_transporte',
            field=models.BooleanField(default=False, verbose_name='Subsídio de Transporte'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='subsidio_turno',
            field=models.BooleanField(default=False, verbose_name='Subsídio de Turno'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(choices=[('EP1', 'Ensino Primário do 1º Grau'), ('EP2', 'Ensino Primário do 2º Grau'), ('ESG1', 'Ensino Secundário Geral do 1º Ciclo'), ('ESG2', 'Ensino Secundário Geral do 2º Ciclo'), ('TEC', 'Ensino Técnico Profissional'), ('SUP', 'Ensino Superior'), ('POS', 'Pós-graduação'), ('MES', 'Mestrado'), ('DOU', 'Doutoramento')], default='ESG1', help_text='Nível de escolaridade conforme o Sistema Nacional de Educação de Moçambique', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_saude',
            field=models.BooleanField(default=False, verbose_name='Plano de Saúde'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='seguro_vida',
            field=models.BooleanField(default=False, verbose_name='Seguro de Vida'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(choices=[('IND', 'Indeterminado'), ('DET', 'Determinado'), ('EST', 'Estágio'), ('TMP', 'Temporário'), ('PRB', 'Período Probatório')], default='PRB', help_text='Tipo de contrato conforme a Lei do Trabalho de Moçambique (Lei 23/2007)', max_length=20),
        ),
    ]
