# Generated by Django 5.2.6 on 2025-09-09 21:23

import django.db.models.deletion
import meuprojeto.empresa.models_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_remove_funcionario_data_emissao_carteira_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='cargo',
            name='beneficios_especificos',
            field=models.TextField(blank=True, help_text='Benefícios específicos para este cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='carga_horaria',
            field=models.IntegerField(default=40, help_text='Carga horária semanal padrão'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='categoria',
            field=models.CharField(choices=[('OP', 'Operacional'), ('ADM', 'Administrativo'), ('TEC', 'Técnico'), ('GES', 'Gestão'), ('EXE', 'Executivo')], default='OP', help_text='Categoria funcional do cargo', max_length=3),
        ),
        migrations.AddField(
            model_name='cargo',
            name='codigo_cargo',
            field=models.CharField(blank=True, help_text='Código único do cargo (gerado automaticamente)', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='competencias',
            field=models.TextField(blank=True, help_text='Competências necessárias para o cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='equipamentos_obrigatorios',
            field=models.TextField(blank=True, help_text='Equipamentos de proteção ou trabalho necessários'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='faixa_salarial_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor máximo da faixa salarial', max_digits=10),
        ),
        migrations.AddField(
            model_name='cargo',
            name='faixa_salarial_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo da faixa salarial', max_digits=10),
        ),
        migrations.AddField(
            model_name='cargo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre o cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='requisitos_desejaveis',
            field=models.TextField(blank=True, help_text='Requisitos desejáveis para o cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='requisitos_obrigatorios',
            field=models.TextField(blank=True, help_text='Requisitos mínimos para ocupar o cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='riscos_ocupacionais',
            field=models.TextField(blank=True, help_text='Riscos ocupacionais associados ao cargo'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='email_departamento',
            field=models.EmailField(blank=True, help_text='Email institucional do departamento', max_length=254),
        ),
        migrations.AddField(
            model_name='departamento',
            name='meta_anual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta anual do departamento (quando aplicável)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre o departamento'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orçamento mensal do departamento', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ramal',
            field=models.CharField(blank=True, help_text='Número do ramal do departamento', max_length=10),
        ),
        migrations.AddField(
            model_name='departamento',
            name='responsavel',
            field=models.CharField(blank=True, help_text='Nome do responsável pelo departamento', max_length=200),
        ),
        migrations.AddField(
            model_name='departamento',
            name='tipo',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('FIN', 'Financeiro'), ('RH', 'Recursos Humanos'), ('COM', 'Comercial'), ('MKT', 'Marketing'), ('OPR', 'Operações'), ('LOG', 'Logística'), ('TI', 'Tecnologia da Informação'), ('JUR', 'Jurídico'), ('PROD', 'Produção'), ('MANUT', 'Manutenção'), ('QUAL', 'Qualidade'), ('COMP', 'Compras'), ('ALM', 'Almoxarifado'), ('EXP', 'Exportação'), ('IMP', 'Importação')], default='ADM', help_text='Tipo/Área do departamento', max_length=10),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='alvara_comercial',
            field=models.CharField(blank=True, help_text='Número do Alvará Comercial', max_length=50),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='data_alvara',
            field=models.DateField(blank=True, help_text='Data de emissão do alvará', null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='data_licenca',
            field=models.DateField(blank=True, help_text='Data de emissão da licença operacional', null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='licenca_operacional',
            field=models.CharField(blank=True, help_text='Número da Licença Operacional', max_length=50),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='nivel_operacional',
            field=models.IntegerField(default=1, help_text='Nível hierárquico da sucursal (1 = principal)'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a sucursal'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o cargo está ativo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação do cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(help_text='Departamento ao qual o cargo está vinculado', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='empresa.departamento'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada das responsabilidades do cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel',
            field=models.CharField(choices=[('EST', 'Estagiário'), ('APR', 'Aprendiz'), ('AUX', 'Auxiliar'), ('ASS', 'Assistente'), ('ANA', 'Analista'), ('TCN', 'Técnico'), ('ESP', 'Especialista'), ('SUP', 'Supervisor'), ('CRD', 'Coordenador'), ('GER', 'Gerente'), ('DIR', 'Director')], help_text='Nível hierárquico do cargo', max_length=3),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(help_text='Nome do cargo', max_length=100),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salário base do cargo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o departamento está ativo'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(help_text='Código único do departamento', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação do departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição das responsabilidades do departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(help_text='Nome do departamento', max_length=100),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='sucursal',
            field=models.ForeignKey(help_text='Sucursal à qual o departamento está vinculado', on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='empresa.sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Indica se a sucursal está operacional'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='bairro',
            field=models.CharField(help_text='Bairro onde a sucursal está localizada', max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cidade',
            field=models.CharField(help_text='Cidade/Distrito onde a sucursal está localizada', max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(help_text='Código único da sucursal', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='data_abertura',
            field=models.DateField(help_text='Data de início das operações'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='email',
            field=models.EmailField(help_text='Email de contato da sucursal', max_length=254),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='empresa_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursais', to='empresa.dadosempresa', verbose_name='Empresa Sede'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='endereco',
            field=models.TextField(help_text='Endereço completo (Av./Rua, Número, Referências)'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nome',
            field=models.CharField(help_text='Nome comercial da sucursal', max_length=200),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='provincia',
            field=models.CharField(choices=[('MP', 'Maputo Cidade'), ('MA', 'Maputo Província'), ('GA', 'Gaza'), ('IN', 'Inhambane'), ('MN', 'Manica'), ('SO', 'Sofala'), ('ZA', 'Zambézia'), ('TE', 'Tete'), ('NA', 'Nampula'), ('NI', 'Niassa'), ('CD', 'Cabo Delgado')], help_text='Província onde a sucursal está localizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='responsavel',
            field=models.CharField(help_text='Nome do responsável pela sucursal', max_length=200),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefone',
            field=models.CharField(help_text='Número de telefone com código do país (+258)', max_length=13, validators=[meuprojeto.empresa.models_base.validar_telefone_moz]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='tipo',
            field=models.CharField(choices=[('SEDE', 'Sede Principal'), ('FILIAL', 'Filial'), ('LOJA', 'Loja'), ('ARMAZEM', 'Armazém'), ('FABRICA', 'Fábrica'), ('ESCRITORIO', 'Escritório'), ('CENTRO_DIST', 'Centro de Distribuição'), ('POSTO_VENDA', 'Posto de Venda')], default='FILIAL', help_text='Tipo de estabelecimento', max_length=20),
        ),
    ]
