# Generated by Django 5.2.6 on 2025-09-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_remove_cargo_requisitos_cargo_beneficios_especificos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(blank=True, help_text='Número da agência', max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(blank=True, help_text='Nome do banco', max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='conta',
            field=models.CharField(blank=True, help_text='Número da conta', max_length=20),
        ),
    ]
