# Generated by Django 5.2.6 on 2025-09-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_funcionario_agencia_alter_funcionario_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='codigo_cargo',
            field=models.CharField(blank=True, help_text='Código único do cargo (gerado automaticamente)', max_length=20, unique=True),
        ),
    ]
