# Generated by Django 5.2.6 on 2025-09-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_cargo_codigo_cargo'),
    ]

    operations = [
    ]
