# Generated by Django 5.2.6 on 2025-09-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_reset_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
