# Generated by Django 5.2.6 on 2025-09-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_remove_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('codigo_funcionario', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('AF', 'Afastado'), ('FE', 'Férias'), ('IN', 'Inativo')], default='AT', max_length=2)),
                ('data_admissao', models.DateField()),
                ('salario_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='empresa.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='empresa.departamento')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome_completo'],
            },
        ),
    ]
