# Generated by Django 5.2.6 on 2025-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosempresa',
            name='actividade_principal',
            field=models.CharField(blank=True, help_text='Descrição da actividade principal da empresa', max_length=200, verbose_name='Actividade Principal'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='capital_social',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capital social em Meticais (MZN)', max_digits=15, verbose_name='Capital Social'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='data_registro_comercial',
            field=models.DateField(blank=True, help_text='Data de registo no Registo Nacional de Pessoas Colectivas', null=True, verbose_name='Data de Registo Comercial'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='numero_registro_comercial',
            field=models.CharField(blank=True, help_text='Número de Registo Comercial no Registo Nacional de Pessoas Colectivas', max_length=50, verbose_name='Número de Registo Comercial'),
        ),
    ]
