# Generated by Django 5.2.6 on 2025-09-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_dadosempresa_actividade_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosempresa',
            name='actividade_principal',
            field=models.CharField(blank=True, choices=[('AGRICULTURA', 'Agricultura, Pecuária e Pesca'), ('MINERACAO', 'Extracção de Minerais'), ('INDUSTRIA', 'Indústria Transformadora'), ('CONSTRUCAO', 'Construção Civil'), ('COMERCIO', 'Comércio por Grosso e Retalho'), ('HOTELARIA', 'Alojamento e Restauração'), ('TRANSPORTES', 'Transportes e Armazenagem'), ('INFORMACAO', 'Tecnologias de Informação e Comunicação'), ('FINANCEIRO', 'Actividades Financeiras e Seguros'), ('IMOBILIARIO', 'Actividades Imobiliárias'), ('PROFISSIONAL', 'Actividades Profissionais e Técnicas'), ('ADMINISTRATIVO', 'Actividades Administrativas'), ('EDUCACAO', 'Educação'), ('SAUDE', 'Actividades de Saúde'), ('CULTURAL', 'Actividades Artísticas e Culturais'), ('DESPORTO', 'Actividades Desportivas e Recreativas'), ('OUTRAS', 'Outras Actividades de Serviços')], help_text='Actividade económica principal conforme classificação moçambicana', max_length=20, verbose_name='Actividade Principal'),
        ),
        migrations.AlterField(
            model_name='dadosempresa',
            name='tipo_societario',
            field=models.CharField(choices=[('SA', 'Sociedade Anónima'), ('LDA', 'Sociedade por Quotas'), ('SU', 'Sociedade Unipessoal'), ('ENI', 'Empresário em Nome Individual'), ('SC', 'Sociedade em Comandita'), ('SNC', 'Sociedade em Nome Colectivo'), ('COOP', 'Cooperativa'), ('ONG', 'Organização Não Governamental'), ('FUNDACAO', 'Fundação'), ('ASSOCIACAO', 'Associação')], default='LDA', help_text='Tipo societário conforme legislação moçambicana', max_length=20),
        ),
    ]
