# Generated by Django 5.2.6 on 2025-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_alter_dadosempresa_actividade_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosempresa',
            name='codigo_empresa',
            field=models.CharField(blank=True, help_text='Código único da empresa (gerado automaticamente)', max_length=10, unique=True),
        ),
    ]
