# Generated by Django 5.2.6 on 2025-09-11 18:01

from django.db import migrations, models


def popular_codigos_empresas(apps, schema_editor):
    DadosEmpresa = apps.get_model('empresa', 'DadosEmpresa')
    
    def gerar_codigo_empresa(nome_empresa):
        # Remover palavras comuns e extrair iniciais
        palavras_ignorar = ['ltda', 'ltd', 'sa', 'sociedade', 'empresa', 'e', 'da', 'do', 'dos', 'das', 'de', 'com', 'e', '&']
        palavras = nome_empresa.lower().split()
        iniciais = [palavra[0].upper() for palavra in palavras if palavra not in palavras_ignorar and len(palavra) > 1]
        
        # Se não temos 3 letras, pegar as primeiras letras das palavras mais longas
        if len(iniciais) < 3:
            palavras_ordenadas = sorted([p for p in palavras if p not in palavras_ignorar and len(p) > 1], key=len, reverse=True)
            iniciais = [palavra[0].upper() for palavra in palavras_ordenadas[:3]]
        
        return ''.join(iniciais[:3]) if len(iniciais) >= 3 else ''.join(iniciais).ljust(3, 'X')
    
    # Atualizar códigos das empresas existentes
    empresas = DadosEmpresa.objects.all()
    for i, empresa in enumerate(empresas, 1):
        iniciais = gerar_codigo_empresa(empresa.nome)
        empresa.codigo_empresa = f"{iniciais}{i:03d}"
        empresa.save()


def reverter_codigos_empresas(apps, schema_editor):
    DadosEmpresa = apps.get_model('empresa', 'DadosEmpresa')
    DadosEmpresa.objects.all().update(codigo_empresa='')


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_dadosempresa_codigo_empresa'),
    ]

    operations = [
        migrations.RunPython(popular_codigos_empresas, reverter_codigos_empresas),
    ]
