# Generated by Django 5.2.6 on 2025-09-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_auto_20250911_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosempresa',
            name='codigo_empresa',
        ),
    ]
