# Generated by Django 5.2.6 on 2025-09-11 18:21

from django.db import migrations, models


def popular_codigos_empresas_sequenciais(apps, schema_editor):
    DadosEmpresa = apps.get_model('empresa', 'DadosEmpresa')
    
    # Atualizar códigos das empresas existentes com formato sequencial
    empresas = DadosEmpresa.objects.all().order_by('id')
    for i, empresa in enumerate(empresas, 1):
        # Limpar nome da empresa (remover espaços e caracteres especiais)
        nome_limpo = ''.join(c for c in empresa.nome if c.isalnum())
        empresa.codigo_empresa = f"{i:03d}{nome_limpo}"
        empresa.save()


def reverter_codigos_empresas_sequenciais(apps, schema_editor):
    DadosEmpresa = apps.get_model('empresa', 'DadosEmpresa')
    DadosEmpresa.objects.all().update(codigo_empresa='')


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_remove_codigo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosempresa',
            name='codigo_empresa',
            field=models.CharField(blank=True, help_text='Código único da empresa (gerado automaticamente)', max_length=50),
        ),
        migrations.RunPython(popular_codigos_empresas_sequenciais, reverter_codigos_empresas_sequenciais),
        migrations.AlterField(
            model_name='dadosempresa',
            name='codigo_empresa',
            field=models.CharField(blank=True, help_text='Código único da empresa (gerado automaticamente)', max_length=50, unique=True),
        ),
    ]
