# Generated by Django 5.2.6 on 2025-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_add_codigo_empresa_sequencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(help_text='Código único da sucursal', max_length=50, unique=True),
        ),
    ]
