# Generated by Django 5.2.6 on 2025-09-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0016_increase_codigo_sucursal_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único do departamento (gerado automaticamente)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_funcionario',
            field=models.CharField(blank=True, help_text='Código único do funcionário (gerado automaticamente)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único da sucursal (gerado automaticamente)', max_length=50, unique=True),
        ),
    ]
