# Generated by Django 5.2.6 on 2025-09-11 21:14

import meuprojeto.empresa.models_rh
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_departamento_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(blank=True, help_text='Número da agência', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ano_conclusao',
            field=models.IntegerField(blank=True, help_text='Ano de conclusão', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(blank=True, help_text='Nome do banco', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='bi',
            field=models.CharField(blank=True, help_text='Número do BI', max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='conta',
            field=models.CharField(blank=True, help_text='Número da conta', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='curso',
            field=models.CharField(blank=True, help_text='Curso de formação', max_length=100),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, help_text='Data de demissão', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_emissao_bi',
            field=models.DateField(blank=True, help_text='Data de emissão do BI', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_validade_bi',
            field=models.DateField(blank=True, help_text='Data de validade do BI', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, help_text='Email pessoal', max_length=254),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço residencial', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('EFI', 'Ensino Fundamental Incompleto'), ('EFC', 'Ensino Fundamental Completo'), ('EMI', 'Ensino Médio Incompleto'), ('EMC', 'Ensino Médio Completo'), ('ETI', 'Ensino Técnico Incompleto'), ('ETC', 'Ensino Técnico Completo'), ('ESI', 'Ensino Superior Incompleto'), ('ESC', 'Ensino Superior Completo'), ('PGI', 'Pós-Graduação Incompleta'), ('PGC', 'Pós-Graduação Completa'), ('MES', 'Mestrado'), ('DOU', 'Doutorado')], help_text='Nível de escolaridade', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('U', 'União Estável')], help_text='Estado civil', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], help_text='Gênero', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='instituicao_ensino',
            field=models.CharField(blank=True, help_text='Instituição de ensino', max_length=100),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='local_emissao_bi',
            field=models.CharField(blank=True, help_text='Local de emissão do BI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nacionalidade',
            field=models.CharField(blank=True, help_text='Nacionalidade', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='naturalidade',
            field=models.CharField(blank=True, help_text='Cidade natal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nib',
            field=models.CharField(blank=True, help_text='Número de NIB', max_length=21, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nuit',
            field=models.CharField(blank=True, help_text='Número de NUIT', max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='outros_subsidios',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outros subsídios', max_digits=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='provincia',
            field=models.CharField(blank=True, help_text='Província', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='subsidio_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subsídio de alimentação', max_digits=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='subsidio_transporte',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subsídio de transporte', max_digits=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone (+258XXXXXXXXX)', max_length=13, null=True, validators=[meuprojeto.empresa.models_rh.validar_telefone_moz]),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone_alternativo',
            field=models.CharField(blank=True, help_text='Telefone alternativo', max_length=13, validators=[meuprojeto.empresa.models_rh.validar_telefone_moz]),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('TMP', 'Temporário'), ('EST', 'Estágio'), ('APR', 'Aprendiz'), ('TER', 'Terceirizado'), ('PJ', 'Pessoa Jurídica')], help_text='Tipo de contrato', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(help_text='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do funcionário', max_length=200),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario_atual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salário atual', max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('AT', 'Ativo'), ('AF', 'Afastado'), ('FE', 'Férias'), ('IN', 'Inativo')], default='AT', help_text='Status atual', max_length=2),
        ),
    ]
