# Generated by Django 5.2.6 on 2025-09-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0018_funcionario_agencia_funcionario_ano_conclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_funcionario',
            field=models.CharField(blank=True, help_text='Código único do funcionário (gerado automaticamente)', max_length=15, unique=True),
        ),
    ]
