# Generated by Django 5.2.6 on 2025-09-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0019_alter_funcionario_codigo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nivel',
            field=models.CharField(choices=[('EST', 'Estagiário'), ('APR', 'Aprendiz'), ('AUX', 'Auxiliar'), ('ASS', 'Assistente'), ('ANA', 'Analista'), ('TCN', 'Técnico'), ('ESP', 'Especialista'), ('SUP', 'Supervisor'), ('CRD', 'Coordenador'), ('GER', 'Gestor'), ('DIR', 'Director')], help_text='Nível hierárquico do cargo', max_length=3),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='tipo',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('FIN', 'Financeiro'), ('RH', 'Recursos Humanos'), ('COM', 'Comercial'), ('MKT', 'Marketing'), ('OPR', 'Operações'), ('LOG', 'Logística'), ('TI', 'Tecnologia de Informação'), ('JUR', 'Jurídico'), ('PROD', 'Produção'), ('MANUT', 'Manutenção'), ('QUAL', 'Qualidade'), ('COMP', 'Aprovisionamento'), ('ALM', 'Armazém'), ('EXP', 'Exportação'), ('IMP', 'Importação')], default='ADM', help_text='Tipo/Área do departamento', max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('EPI', 'Ensino Primário Incompleto'), ('EPC', 'Ensino Primário Completo'), ('ESI', 'Ensino Secundário Incompleto'), ('ESC', 'Ensino Secundário Completo'), ('ETI', 'Ensino Técnico Incompleto'), ('ETC', 'Ensino Técnico Completo'), ('EUI', 'Ensino Universitário Incompleto'), ('EUC', 'Ensino Universitário Completo'), ('PGI', 'Pós-Graduação Incompleta'), ('PGC', 'Pós-Graduação Completa'), ('MES', 'Mestrado'), ('DOU', 'Doutoramento')], help_text='Nível de escolaridade', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('EFT', 'Efectivo'), ('TMP', 'Temporário'), ('EST', 'Estágio'), ('APR', 'Aprendiz'), ('TER', 'Terceirizado'), ('PRS', 'Prestador de Serviços')], help_text='Tipo de contrato', max_length=3, null=True),
        ),
    ]
