# Generated by Django 5.2.6 on 2025-09-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0020_alter_cargo_nivel_alter_departamento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_funcionario',
            field=models.CharField(blank=True, help_text='Código único do funcionário (gerado automaticamente)', max_length=7, unique=True),
        ),
    ]
