# Generated by Django 5.2.6 on 2025-09-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0021_alter_funcionario_codigo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosempresa',
            name='codigo_empresa',
            field=models.CharField(blank=True, editable=False, help_text='Código único da empresa (gerado automaticamente)', max_length=50, unique=True),
        ),
    ]
