# Generated by Django 5.2.6 on 2025-09-11 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0022_alter_dadosempresa_codigo_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do benefício', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do benefício')),
                ('tipo_valor', models.CharField(choices=[('FX', 'Valor Fixo'), ('PC', 'Percentual')], help_text='Tipo de valor do benefício', max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do benefício (fixo ou percentual)', max_digits=10)),
                ('incide_inss', models.BooleanField(default=False, help_text='Se o benefício incide no cálculo do INSS')),
                ('incide_irps', models.BooleanField(default=False, help_text='Se o benefício incide no cálculo do IRPS')),
                ('ativo', models.BooleanField(default=True, help_text='Se o benefício está ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Benefício',
                'verbose_name_plural': 'Tipos de Benefícios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do desconto', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do desconto')),
                ('tipo_valor', models.CharField(choices=[('FX', 'Valor Fixo'), ('PC', 'Percentual')], help_text='Tipo de valor do desconto', max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do desconto (fixo ou percentual)', max_digits=10)),
                ('periodicidade', models.CharField(choices=[('UN', 'Única vez'), ('ME', 'Mensal'), ('TR', 'Trimestral'), ('SM', 'Semestral'), ('AN', 'Anual')], default='ME', help_text='Periodicidade do desconto', max_length=2)),
                ('incide_inss', models.BooleanField(default=False, help_text='Se o desconto afeta a base de cálculo do INSS')),
                ('incide_irps', models.BooleanField(default=False, help_text='Se o desconto afeta a base de cálculo do IRPS')),
                ('ativo', models.BooleanField(default=True, help_text='Se o desconto está ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Desconto',
                'verbose_name_plural': 'Tipos de Descontos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='dadosempresa',
            name='codigo_empresa',
            field=models.CharField(blank=True, help_text='Código único da empresa (gerado automaticamente)', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='BeneficioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo específico para este funcionário', max_digits=10, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual específico para este funcionário', max_digits=5, null=True)),
                ('data_inicio', models.DateField(help_text='Data de início do benefício')),
                ('data_fim', models.DateField(blank=True, help_text='Data de fim do benefício', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o benefício')),
                ('ativo', models.BooleanField(default=True, help_text='Se o benefício está ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='empresa.funcionario')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.tipobeneficio')),
            ],
            options={
                'verbose_name': 'Benefício do Funcionário',
                'verbose_name_plural': 'Benefícios dos Funcionários',
                'ordering': ['funcionario__codigo_funcionario', 'tipo_beneficio__nome'],
            },
        ),
        migrations.CreateModel(
            name='DescontoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo específico para este funcionário', max_digits=10, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual específico para este funcionário', max_digits=5, null=True)),
                ('data_inicio', models.DateField(help_text='Data de início do desconto')),
                ('data_fim', models.DateField(blank=True, help_text='Data de fim do desconto', null=True)),
                ('numero_parcelas', models.IntegerField(blank=True, help_text='Número de parcelas (para descontos parcelados)', null=True)),
                ('parcelas_pagas', models.IntegerField(default=0, help_text='Número de parcelas já pagas')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o desconto')),
                ('ativo', models.BooleanField(default=True, help_text='Se o desconto está ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='empresa.funcionario')),
                ('tipo_desconto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.tipodesconto')),
            ],
            options={
                'verbose_name': 'Desconto do Funcionário',
                'verbose_name_plural': 'Descontos dos Funcionários',
                'ordering': ['funcionario__codigo_funcionario', 'tipo_desconto__nome'],
            },
        ),
    ]
