# Generated by Django 5.2.6 on 2025-09-11 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0023_tipobeneficio_tipodesconto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tipo de presença', max_length=100)),
                ('codigo', models.CharField(choices=[('PR', 'Presente'), ('AU', 'Ausente'), ('AT', 'Atraso'), ('FE', 'Falta Justificada'), ('FE', 'Falta Injustificada'), ('LI', 'Licença'), ('FE', 'Férias'), ('SU', 'Suspensão'), ('OU', 'Outro')], help_text='Código único do tipo', max_length=2, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do tipo de presença')),
                ('desconta_salario', models.BooleanField(default=False, help_text='Se este tipo desconta do salário')),
                ('cor', models.CharField(default='#28a745', help_text='Cor para exibição (código hexadecimal)', max_length=7)),
                ('ativo', models.BooleanField(default=True, help_text='Se o tipo está ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Presença',
                'verbose_name_plural': 'Tipos de Presenças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da presença')),
                ('hora_entrada', models.TimeField(blank=True, help_text='Hora de entrada', null=True)),
                ('hora_saida', models.TimeField(blank=True, help_text='Hora de saída', null=True)),
                ('horas_trabalhadas', models.DecimalField(blank=True, decimal_places=2, help_text='Horas trabalhadas no dia', max_digits=4, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a presença')),
                ('justificativa', models.TextField(blank=True, help_text='Justificativa para faltas ou atrasos')),
                ('data_aprovacao', models.DateTimeField(blank=True, help_text='Data de aprovação da justificativa', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, help_text='Usuário que aprovou a justificativa', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='empresa.funcionario')),
                ('tipo_presenca', models.ForeignKey(help_text='Tipo de presença', on_delete=django.db.models.deletion.PROTECT, to='empresa.tipopresenca')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-data', 'funcionario__codigo_funcionario'],
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
