# Generated by Django 5.2.6 on 2025-09-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_tipopresenca_presenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='hora_saida',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='horas_trabalhadas',
        ),
        migrations.AddField(
            model_name='presenca',
            name='horas_extras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas extras trabalhadas (opcional)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tipopresenca',
            name='codigo',
            field=models.CharField(choices=[('PR', 'Presente'), ('AU', 'Ausente'), ('FJ', 'Falta Justificada'), ('FI', 'Falta Injustificada'), ('LI', 'Licença'), ('FE', 'Férias'), ('SU', 'Suspensão'), ('AT', 'Atraso'), ('OU', 'Outro')], help_text='Código único do tipo', max_length=2, unique=True),
        ),
    ]
