# Generated by Django 5.2.6 on 2025-09-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0026_criar_tipos_presenca_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do feriado', max_length=100)),
                ('data', models.DateField(help_text='Data do feriado')),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Feriado Nacional'), ('REGIONAL', 'Feriado Regional'), ('EMPRESA', 'Feriado da Empresa'), ('MUNICIPAL', 'Feriado Municipal')], default='NACIONAL', help_text='Tipo do feriado', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do feriado')),
                ('ativo', models.BooleanField(default=True, help_text='Feriado ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data', 'nome'],
                'unique_together': {('data', 'nome')},
            },
        ),
    ]
