# Generated by Django 5.2.6 on 2025-09-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0027_feriado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopresenca',
            name='codigo',
            field=models.CharField(choices=[('PR', 'Presente'), ('AU', 'Ausente'), ('FJ', 'Falta Justificada'), ('FI', 'Falta Injustificada'), ('LI', 'Licença'), ('FE', 'Férias'), ('SU', 'Suspensão'), ('AT', 'Atraso'), ('FD', 'Feriado'), ('OU', 'Outro')], help_text='Código único do tipo', max_length=2, unique=True),
        ),
    ]
