# Generated by Django 5.2.6 on 2025-09-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0028_add_feriado_tipo_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Benefício')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('SB', 'Subsídio de Alimentação'), ('ST', 'Subsídio de Transporte'), ('SH', 'Subsídio de Habitação'), ('BO', 'Bónus'), ('PR', 'Prémio'), ('CO', 'Comissão'), ('HE', 'Horas Extras'), ('OU', 'Outro')], max_length=2, verbose_name='Tipo')),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Fixo')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual (%)')),
                ('base_calculo', models.CharField(blank=True, max_length=50, verbose_name='Base de Cálculo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Benefício Salarial',
                'verbose_name_plural': 'Benefícios Salariais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DescontoSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Desconto')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('IR', 'Imposto de Renda'), ('IN', 'INSS'), ('SS', 'Segurança Social'), ('EM', 'Empréstimo'), ('AD', 'Adiantamento'), ('FA', 'Falta'), ('AT', 'Atraso'), ('OU', 'Outro')], max_length=2, verbose_name='Tipo')),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Fixo')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual (%)')),
                ('base_calculo', models.CharField(blank=True, max_length=50, verbose_name='Base de Cálculo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Desconto Salarial',
                'verbose_name_plural': 'Descontos Salariais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('SU', 'Suspenso')], default='AT', max_length=2, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Salário',
                'verbose_name_plural': 'Salários',
                'ordering': ['-data_inicio', 'funcionario'],
            },
        ),
        migrations.CreateModel(
            name='SalarioBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_aplicacao', models.DateField(auto_now_add=True, verbose_name='Data de Aplicação')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.beneficiosalarial', verbose_name='Benefício')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='empresa.salario', verbose_name='Salário')),
            ],
            options={
                'verbose_name': 'Benefício do Salário',
                'verbose_name_plural': 'Benefícios do Salário',
                'unique_together': {('salario', 'beneficio')},
            },
        ),
        migrations.CreateModel(
            name='SalarioDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_aplicacao', models.DateField(auto_now_add=True, verbose_name='Data de Aplicação')),
                ('desconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.descontosalarial', verbose_name='Desconto')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='empresa.salario', verbose_name='Salário')),
            ],
            options={
                'verbose_name': 'Desconto do Salário',
                'verbose_name_plural': 'Descontos do Salário',
                'unique_together': {('salario', 'desconto')},
            },
        ),
    ]
