# Generated by Django 5.2.6 on 2025-09-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0029_beneficiosalarial_descontosalarial_salario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descontofuncionario',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='descontofuncionario',
            name='tipo_desconto',
        ),
        migrations.RemoveField(
            model_name='beneficiosalarial',
            name='percentual',
        ),
        migrations.RemoveField(
            model_name='beneficiosalarial',
            name='valor_fixo',
        ),
        migrations.RemoveField(
            model_name='descontosalarial',
            name='percentual',
        ),
        migrations.RemoveField(
            model_name='descontosalarial',
            name='valor_fixo',
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='base_calculo_personalizada',
            field=models.CharField(blank=True, max_length=50, verbose_name='Base de Cálculo Personalizada'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='tipo_valor',
            field=models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual')], default='FIXO', max_length=10, verbose_name='Tipo de Valor'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='descontosalarial',
            name='base_calculo_personalizada',
            field=models.CharField(blank=True, max_length=50, verbose_name='Base de Cálculo Personalizada'),
        ),
        migrations.AddField(
            model_name='descontosalarial',
            name='tipo_valor',
            field=models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual')], default='FIXO', max_length=10, verbose_name='Tipo de Valor'),
        ),
        migrations.AddField(
            model_name='descontosalarial',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='beneficiosalarial',
            name='base_calculo',
            field=models.CharField(choices=[('SALARIO_BASE', 'Salário Base'), ('SALARIO_BRUTO', 'Salário Bruto'), ('SALARIO_LIQUIDO', 'Salário Líquido'), ('REMUNERACAO_TOTAL', 'Remuneração Total'), ('HORAS_TRABALHADAS', 'Horas Trabalhadas'), ('DIAS_TRABALHADOS', 'Dias Trabalhados'), ('PRODUCAO', 'Produção'), ('VENDAS', 'Vendas'), ('OUTRO', 'Outro')], default='SALARIO_BASE', max_length=20, verbose_name='Base de Cálculo'),
        ),
        migrations.AlterField(
            model_name='descontosalarial',
            name='base_calculo',
            field=models.CharField(choices=[('SALARIO_BASE', 'Salário Base'), ('SALARIO_BRUTO', 'Salário Bruto'), ('SALARIO_LIQUIDO', 'Salário Líquido'), ('REMUNERACAO_TOTAL', 'Remuneração Total'), ('HORAS_TRABALHADAS', 'Horas Trabalhadas'), ('DIAS_TRABALHADOS', 'Dias Trabalhados'), ('PRODUCAO', 'Produção'), ('VENDAS', 'Vendas'), ('OUTRO', 'Outro')], default='SALARIO_BASE', max_length=20, verbose_name='Base de Cálculo'),
        ),
        migrations.AlterField(
            model_name='salariobeneficio',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='salariodesconto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.DeleteModel(
            name='BeneficioFuncionario',
        ),
        migrations.DeleteModel(
            name='TipoBeneficio',
        ),
        migrations.DeleteModel(
            name='DescontoFuncionario',
        ),
        migrations.DeleteModel(
            name='TipoDesconto',
        ),
    ]
