# Generated by Django 5.2.6 on 2025-09-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0030_remove_basic_benefits_discounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiosalarial',
            options={'ordering': ['nome'], 'verbose_name': 'Benefício', 'verbose_name_plural': 'Benefícios'},
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='contato_responsavel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contacto do Responsável'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='documento_necessario',
            field=models.CharField(blank=True, max_length=200, verbose_name='Documentos Necessários'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fornecedor/Prestador'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='limite_uso',
            field=models.CharField(blank=True, max_length=100, verbose_name='Limite de Uso'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='beneficiosalarial',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contacto'),
        ),
        migrations.AlterField(
            model_name='beneficiosalarial',
            name='tipo',
            field=models.CharField(choices=[('SB', 'Subsídio de Alimentação'), ('ST', 'Subsídio de Transporte'), ('SH', 'Subsídio de Habitação'), ('BO', 'Bónus'), ('PR', 'Prémio'), ('CO', 'Comissão'), ('HE', 'Horas Extras'), ('PS', 'Plano de Saúde'), ('GI', 'Acesso ao Ginásio'), ('ES', 'Estacionamento'), ('RE', 'Refeições'), ('TR', 'Transporte Empresarial'), ('ED', 'Educação/Formação'), ('TE', 'Tecnologia/Equipamentos'), ('FE', 'Férias Extras'), ('FL', 'Flexibilidade Horária'), ('HO', 'Home Office'), ('OU', 'Outro')], max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='beneficiosalarial',
            name='tipo_valor',
            field=models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual'), ('NAO_MONETARIO', 'Não Monetário')], default='FIXO', max_length=15, verbose_name='Tipo de Valor'),
        ),
        migrations.AlterField(
            model_name='descontosalarial',
            name='tipo_valor',
            field=models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual'), ('NAO_MONETARIO', 'Não Monetário')], default='FIXO', max_length=15, verbose_name='Tipo de Valor'),
        ),
    ]
