# Generated by Django 5.2.6 on 2025-09-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0031_add_non_monetary_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Treinamento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido')], default='INTERNO', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('ADIADO', 'Adiado')], default='PLANEJADO', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='Prioridade')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('data_limite_inscricao', models.DateField(blank=True, null=True, verbose_name='Data Limite de Inscrição')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('instrutor', models.CharField(blank=True, max_length=200, verbose_name='Instrutor/Facilitador')),
                ('instituicao', models.CharField(blank=True, max_length=200, verbose_name='Instituição/Fornecedor')),
                ('capacidade_maxima', models.PositiveIntegerField(default=20, verbose_name='Capacidade Máxima')),
                ('custo_por_participante', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo por Participante')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Total')),
                ('requisitos', models.TextField(blank=True, verbose_name='Requisitos')),
                ('objetivos', models.TextField(blank=True, verbose_name='Objetivos')),
                ('conteudo_programatico', models.TextField(blank=True, verbose_name='Conteúdo Programático')),
                ('emite_certificado', models.BooleanField(default=True, verbose_name='Emite Certificado')),
                ('carga_horaria', models.PositiveIntegerField(default=0, verbose_name='Carga Horária (horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída'), ('FALTOSA', 'Faltosa')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Final')),
                ('frequencia_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Frequência (%)')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.funcionario', verbose_name='Funcionário')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='empresa.treinamento', verbose_name='Treinamento')),
            ],
            options={
                'verbose_name': 'Inscrição em Treinamento',
                'verbose_name_plural': 'Inscrições em Treinamentos',
                'ordering': ['-data_inscricao'],
                'unique_together': {('treinamento', 'funcionario')},
            },
        ),
    ]
