# Generated by Django 5.2.6 on 2025-09-12 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0032_add_treinamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Critério')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Peso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANUAL', 'Avaliação Anual'), ('SEMESTRAL', 'Avaliação Semestral'), ('TRIMESTRAL', 'Avaliação Trimestral'), ('MENSAL', 'Avaliação Mensal'), ('PERIODICA', 'Avaliação Periódica'), ('ESPECIAL', 'Avaliação Especial')], default='ANUAL', max_length=20, verbose_name='Tipo de Avaliação')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(verbose_name='Data de Início do Período')),
                ('data_fim', models.DateField(verbose_name='Data de Fim do Período')),
                ('data_avaliacao', models.DateField(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('nota_geral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Geral')),
                ('classificacao', models.CharField(blank=True, max_length=50, verbose_name='Classificação')),
                ('metas_estabelecidas', models.TextField(blank=True, verbose_name='Metas Estabelecidas')),
                ('metas_alcancadas', models.TextField(blank=True, verbose_name='Metas Alcançadas')),
                ('pontos_fortes', models.TextField(blank=True, verbose_name='Pontos Fortes')),
                ('pontos_melhoria', models.TextField(blank=True, verbose_name='Pontos de Melhoria')),
                ('observacoes_avaliador', models.TextField(blank=True, verbose_name='Observações do Avaliador')),
                ('observacoes_funcionario', models.TextField(blank=True, verbose_name='Observações do Funcionário')),
                ('plano_desenvolvimento', models.TextField(blank=True, verbose_name='Plano de Desenvolvimento')),
                ('aprovada', models.BooleanField(default=False, verbose_name='Aprovada')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_aprovadas', to='empresa.funcionario', verbose_name='Aprovada por')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_realizadas', to='empresa.funcionario', verbose_name='Avaliador')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='empresa.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Avaliação de Desempenho',
                'verbose_name_plural': 'Avaliações de Desempenho',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CriterioAvaliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_avaliados', to='empresa.avaliacaodesempenho', verbose_name='Avaliação')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.criterioavaliacao', verbose_name='Critério')),
            ],
            options={
                'verbose_name': 'Critério Avaliado',
                'verbose_name_plural': 'Critérios Avaliados',
                'unique_together': {('avaliacao', 'criterio')},
            },
        ),
    ]
