# Generated by Django 5.2.6 on 2025-09-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0033_criterioavaliacao_avaliacaodesempenho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência')),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga')], default='ABERTA', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Bruto')),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Descontos')),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Líquido')),
                ('total_funcionarios', models.IntegerField(default=0, verbose_name='Total de Funcionários')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Folha Salarial',
                'verbose_name_plural': 'Folhas Salariais',
                'unique_together': {('mes_referencia',)},
            },
        ),
        migrations.CreateModel(
            name='FuncionarioFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base')),
                ('salario_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salário Bruto')),
                ('total_beneficios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Benefícios')),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Descontos')),
                ('salario_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salário Líquido')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Trabalhadas')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Extras')),
                ('dias_trabalhados', models.IntegerField(default=0, verbose_name='Dias Trabalhados')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_folha', to='empresa.folhasalarial', verbose_name='Folha')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Funcionário na Folha',
                'verbose_name_plural': 'Funcionários na Folha',
                'unique_together': {('folha', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='DescontoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('desconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.descontosalarial', verbose_name='Desconto')),
                ('funcionario_folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos_folha', to='empresa.funcionariofolha', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Desconto na Folha',
                'verbose_name_plural': 'Descontos na Folha',
                'unique_together': {('funcionario_folha', 'desconto')},
            },
        ),
        migrations.CreateModel(
            name='BeneficioFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.beneficiosalarial', verbose_name='Benefício')),
                ('funcionario_folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_folha', to='empresa.funcionariofolha', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Benefício na Folha',
                'verbose_name_plural': 'Benefícios na Folha',
                'unique_together': {('funcionario_folha', 'beneficio')},
            },
        ),
    ]
