# Generated by Django 5.2.6 on 2025-09-13 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0034_folhasalarial_funcionariofolha_descontofolha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Trabalhador', 'verbose_name_plural': 'Trabalhadores'},
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='dias_trabalho_semana',
            field=models.PositiveSmallIntegerField(default=5, help_text='Número de dias de trabalho por semana', verbose_name='Dias de Trabalho por Semana'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='duracao_almoco',
            field=models.DurationField(default='01:00:00', help_text='Duração da pausa para almoço (formato HH:MM:SS)', verbose_name='Duração do Almoço'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='hora_fim_expediente',
            field=models.TimeField(default='17:00', help_text='Hora de fim do expediente (formato HH:MM)', verbose_name='Hora de Fim do Expediente'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='hora_inicio_expediente',
            field=models.TimeField(default='08:00', help_text='Hora de início do expediente (formato HH:MM)', verbose_name='Hora de Início do Expediente'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='horas_trabalho_dia',
            field=models.DurationField(default='08:00:00', help_text='Número de horas de trabalho por dia (formato HH:MM:SS)', verbose_name='Horas de Trabalho por Dia'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='dias_trabalho_semana',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de dias de trabalho por semana (deixa vazio para usar da empresa sede)', null=True, verbose_name='Dias de Trabalho por Semana'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='duracao_almoco',
            field=models.DurationField(blank=True, help_text='Duração da pausa para almoço (deixa vazio para usar da empresa sede)', null=True, verbose_name='Duração do Almoço'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_fim_expediente',
            field=models.TimeField(blank=True, help_text='Hora de fim do expediente (deixa vazio para usar da empresa sede)', null=True, verbose_name='Hora de Fim do Expediente'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_inicio_expediente',
            field=models.TimeField(blank=True, help_text='Hora de início do expediente (deixa vazio para usar da empresa sede)', null=True, verbose_name='Hora de Início do Expediente'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horas_trabalho_dia',
            field=models.DurationField(blank=True, help_text='Número de horas de trabalho por dia (deixa vazio para usar da empresa sede)', null=True, verbose_name='Horas de Trabalho por Dia'),
        ),
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='status',
            field=models.CharField(choices=[('PLANEJADA', 'Planificada'), ('EM_ANDAMENTO', 'Em Curso'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remuneração base do cargo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='descontosalarial',
            name='tipo',
            field=models.CharField(choices=[('IR', 'Imposto de Renda'), ('IN', 'INSS Moçambique'), ('SS', 'Segurança Social'), ('EM', 'Empréstimo'), ('AD', 'Adiantamento'), ('FA', 'Falta'), ('AT', 'Atraso'), ('OU', 'Outro')], max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_funcionario',
            field=models.CharField(blank=True, help_text='Código único do trabalhador (gerado automaticamente)', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], help_text='Género', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do trabalhador', max_length=200),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario_atual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remuneração atual', max_digits=10),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que aprovou a justificação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, help_text='Data de aprovação da justificação', null=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Justificação para faltas ou atrasos'),
        ),
        migrations.AlterField(
            model_name='tipopresenca',
            name='desconta_salario',
            field=models.BooleanField(default=False, help_text='Se este tipo desconta da remuneração'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='status',
            field=models.CharField(choices=[('PLANEJADO', 'Planificado'), ('EM_ANDAMENTO', 'Em Curso'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('ADIADO', 'Adiado')], default='PLANEJADO', max_length=20, verbose_name='Status'),
        ),
    ]
