# Generated by Django 5.2.6 on 2025-09-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0035_alter_funcionario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='dias_trabalho_semana',
            field=models.PositiveSmallIntegerField(default=5, help_text='Número de dias de trabalho por semana', verbose_name='Dias de Trabalho por Semana'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='duracao_almoco',
            field=models.DurationField(default='01:00:00', help_text='Duração da pausa para almoço (formato HH:MM:SS)', verbose_name='Duração do Almoço'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='hora_fim_expediente',
            field=models.TimeField(default='17:00', help_text='Hora de fim do expediente (formato HH:MM)', verbose_name='Hora de Fim do Expediente'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='hora_inicio_expediente',
            field=models.TimeField(default='08:00', help_text='Hora de início do expediente (formato HH:MM)', verbose_name='Hora de Início do Expediente'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='horas_trabalho_dia',
            field=models.DurationField(default='08:00:00', help_text='Número de horas de trabalho por dia (formato HH:MM:SS)', verbose_name='Horas de Trabalho por Dia'),
        ),
    ]
