# Generated by Django 5.2.6 on 2025-09-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0036_make_sucursal_work_hours_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='salario_atual',
        ),
    ]
