# Generated by Django 5.2.6 on 2025-09-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0037_remove_salario_atual_redundant'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='salario_atual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salário atual do funcionário (FONTE PRINCIPAL)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionariofolha',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, help_text='SOMENTE LEITURA - Populado automaticamente da tabela Salario', max_digits=10, verbose_name='Salário Base'),
        ),
    ]
