# Generated by Django 5.2.6 on 2025-09-13 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0038_restore_salario_atual_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROMOCAO', 'Promoção de Cargo'), ('AUMENTO', 'Aumento Salarial'), ('BONUS', 'Bônus'), ('AJUSTE', 'Ajuste Salarial'), ('REVISAO', 'Revisão Anual'), ('MERITO', 'Aumento por Mérito'), ('INFLACAO', 'Ajuste por Inflação'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('IMPLEMENTADO', 'Implementado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('salario_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Anterior')),
                ('salario_novo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Novo')),
                ('percentual_aumento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de Aumento (%)')),
                ('valor_aumento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Aumento')),
                ('data_solicitacao', models.DateField(verbose_name='Data da Solicitação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data da Aprovação')),
                ('data_implementacao', models.DateField(blank=True, null=True, verbose_name='Data da Implementação')),
                ('data_efetivacao', models.DateField(blank=True, null=True, verbose_name='Data da Efetivação')),
                ('motivo', models.TextField(verbose_name='Motivo da Promoção/Aumento')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa Detalhada')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('cargo_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_anteriores', to='empresa.cargo', verbose_name='Cargo Anterior')),
                ('cargo_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_novas', to='empresa.cargo', verbose_name='Cargo Novo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.funcionario', verbose_name='Funcionário')),
                ('rejeitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_rejeitadas', to=settings.AUTH_USER_MODEL, verbose_name='Rejeitado por')),
            ],
            options={
                'verbose_name': 'Promoção/Aumento',
                'verbose_name_plural': 'Promoções/Aumentos',
                'ordering': ['-data_solicitacao', 'funcionario'],
            },
        ),
    ]
