# Generated by Django 5.2.6 on 2025-09-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0040_add_desconto_faltas_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='descontosalarial',
            name='aplicar_automaticamente',
            field=models.BooleanField(default=False, help_text='Se deve ser aplicado automaticamente na folha de salário', verbose_name='Aplicar Automaticamente'),
        ),
        migrations.AddField(
            model_name='descontosalarial',
            name='valor_maximo_isencao',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor máximo do salário para isenção total (opcional)', max_digits=10, verbose_name='Valor Máximo para Isenção'),
        ),
        migrations.AddField(
            model_name='descontosalarial',
            name='valor_minimo_isencao',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mínimo do salário para aplicar o desconto (ex: 19000 para IRPS)', max_digits=10, verbose_name='Valor Mínimo para Isenção'),
        ),
    ]
