# Generated by Django 5.2.6 on 2025-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0041_adicionar_campos_desconto_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='hora_entrada',
            field=models.TimeField(blank=True, help_text='Hora de entrada', null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='hora_saida',
            field=models.TimeField(blank=True, help_text='Hora de saída', null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='horas_extras_diurnas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas extras diurnas (50%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='horas_extras_noturnas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas extras noturnas (100%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='horas_trabalhadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas trabalhadas no dia', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='trabalho_extraordinario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trabalho extraordinário (100%)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='horas_extras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas extras trabalhadas (calculado automaticamente)', max_digits=4, null=True),
        ),
    ]
