# Generated by Django 5.2.6 on 2025-09-14 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0042_add_time_fields_to_presenca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='horas_extras',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='horas_extras_diurnas',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='horas_extras_noturnas',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='trabalho_extraordinario',
        ),
        migrations.AlterField(
            model_name='presenca',
            name='hora_entrada',
            field=models.TimeField(blank=True, help_text='Hora de início do trabalho', null=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='hora_saida',
            field=models.TimeField(blank=True, help_text='Hora de fim do trabalho', null=True),
        ),
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data das horas extras')),
                ('tipo', models.CharField(choices=[('DI', 'Horas Extras Diurnas (50%)'), ('NO', 'Horas Extras Noturnas (100%)'), ('EX', 'Trabalho Extraordinário (100%)')], help_text='Tipo de horas extras', max_length=2)),
                ('hora_inicio', models.TimeField(help_text='Hora de início das horas extras')),
                ('hora_fim', models.TimeField(help_text='Hora de fim das horas extras')),
                ('quantidade_horas', models.DecimalField(decimal_places=2, help_text='Quantidade de horas extras', max_digits=4)),
                ('valor_por_hora', models.DecimalField(decimal_places=2, help_text='Valor por hora (calculado automaticamente)', max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total das horas extras', max_digits=10)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre as horas extras')),
                ('data_aprovacao', models.DateTimeField(blank=True, help_text='Data de aprovação', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, help_text='Usuário que aprovou as horas extras', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='empresa.funcionario')),
            ],
            options={
                'verbose_name': 'Horas Extras',
                'verbose_name_plural': 'Horas Extras',
                'ordering': ['-data', 'funcionario__codigo_funcionario'],
                'unique_together': {('funcionario', 'data', 'tipo')},
            },
        ),
    ]
