# Generated by Django 5.2.6 on 2025-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0043_add_horas_extras_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasextras',
            name='tipo',
            field=models.CharField(blank=True, choices=[('DI', 'Horas Extras Diurnas (50%)'), ('NO', 'Horas Extras Noturnas (100%)'), ('EX', 'Trabalho Extraordinário (100%)')], help_text='Tipo de horas extras (calculado automaticamente se não especificado)', max_length=2),
        ),
    ]
