# Generated by Django 5.2.6 on 2025-09-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0044_make_tipo_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horasextras',
            unique_together=set(),
        ),
    ]
