# Generated by Django 5.2.6 on 2025-09-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0045_remove_unique_constraint_horas_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariofolha',
            name='horas_extras',
        ),
    ]
