# Generated by Django 5.2.6 on 2025-09-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0046_remove_horas_extras_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horasextras',
            unique_together={('funcionario', 'data', 'hora_inicio', 'hora_fim')},
        ),
    ]
