# Generated by Django 5.2.6 on 2025-09-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0047_add_unique_constraint_horas_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='hora_saida',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='horas_trabalhadas',
        ),
        migrations.AddField(
            model_name='funcionariofolha',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Extras'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='horas_extras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas extras trabalhadas (opcional)', max_digits=4, null=True),
        ),
        migrations.DeleteModel(
            name='HorasExtras',
        ),
    ]
