# Generated by Django 5.2.6 on 2025-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0048_add_horas_extras_to_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='hora_fim',
            field=models.TimeField(blank=True, help_text='Hora de fim do trabalho', null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de início do trabalho', null=True),
        ),
        migrations.AddField(
            model_name='presenca',
            name='horas_extras_100',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas extras noturnas (100%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='presenca',
            name='horas_extras_50',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas extras normais (50%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='presenca',
            name='trabalho_extraordinario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Trabalho extraordinário (finais de semana)', max_digits=4),
        ),
    ]
