# Generated by Django 5.2.6 on 2025-09-14 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0049_add_horas_extras_detailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='tipo',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('FIN', 'Financeiro'), ('RH', 'Recursos Humanos'), ('COM', 'Comercial'), ('MKT', 'Marketing'), ('OPR', 'Operações'), ('LOG', 'Logística'), ('TI', 'Tecnologia de Informação'), ('JUR', 'Jurídico'), ('PROD', 'Produção'), ('MANUT', 'Manutenção'), ('QUAL', 'Qualidade'), ('COMP', 'Aprovisionamento'), ('ALM', 'Armazém'), ('EXP', 'Exportação'), ('IMP', 'Importação'), ('GOV', 'Governação'), ('AUD', 'Auditoria Interna'), ('SEG', 'Segurança'), ('SOC', 'Responsabilidade Social'), ('AMBI', 'Ambiente'), ('COMU', 'Comunicação'), ('PLAN', 'Planeamento'), ('MON', 'Monitoria e Avaliação')], default='ADM', help_text='Tipo/Área do departamento', max_length=10),
        ),
        migrations.CreateModel(
            name='DepartamentoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o departamento está ativo nesta sucursal')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de vinculação do departamento à sucursal')),
                ('departamento', models.ForeignKey(help_text='Departamento que pode ser usado em múltiplas sucursais', on_delete=django.db.models.deletion.CASCADE, related_name='sucursais_vinculadas', to='empresa.departamento')),
                ('sucursal', models.ForeignKey(help_text='Sucursal onde o departamento pode ser usado', on_delete=django.db.models.deletion.CASCADE, related_name='departamentos_vinculados', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Departamento por Sucursal',
                'verbose_name_plural': 'Departamentos por Sucursais',
                'ordering': ['sucursal__nome', 'departamento__nome'],
                'unique_together': {('departamento', 'sucursal')},
            },
        ),
    ]
