# Generated by Django 5.2.6 on 2025-09-15 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0050_alter_departamento_tipo_departamentosucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nome'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursais'},
        ),
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('DI', 'Diurno'), ('NO', 'Noturno'), ('EX', 'Extraordinário')], default='DI', max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('quantidade_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_extras_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_extras_criadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='empresa.funcionario')),
            ],
            options={
                'verbose_name': 'Horas Extras',
                'verbose_name_plural': 'Horas Extras',
                'ordering': ['-data', '-data_criacao'],
                'unique_together': {('funcionario', 'data', 'tipo')},
            },
        ),
    ]
