# Generated by Django 5.2.6 on 2025-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0051_add_horas_extras_complete_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='horas_extras_100',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='horas_extras_50',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='trabalho_extraordinario',
        ),
        migrations.AlterField(
            model_name='presenca',
            name='horas_extras',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas extras trabalhadas (básico - para referência)', max_digits=4, null=True),
        ),
    ]
