# Generated by Django 5.2.6 on 2025-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0052_remove_duplicate_overtime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('EXCELENTE', 'Excelente'), ('MUITO_BOM', 'Muito Bom'), ('BOM', 'Bom'), ('SATISFATORIO', 'Satisfatório'), ('REGULAR', 'Regular'), ('INSATISFATORIO', 'Insatisfatório')], max_length=50, verbose_name='Classificação'),
        ),
    ]
