# Generated by Django 5.2.6 on 2025-09-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0053_alter_avaliacaodesempenho_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='beneficios',
            field=models.ManyToManyField(blank=True, help_text='Benefícios aos quais o funcionário está sujeito', related_name='funcionarios_beneficiarios', to='empresa.beneficiosalarial'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='descontos',
            field=models.ManyToManyField(blank=True, help_text='Descontos aos quais o funcionário está sujeito', related_name='funcionarios_descontados', to='empresa.descontosalarial'),
        ),
    ]
