# Generated by Django 5.2.6 on 2025-09-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0054_funcionario_beneficios_funcionario_descontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='outros_subsidios',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='subsidio_alimentacao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='subsidio_transporte',
        ),
    ]
