# Generated by Django 5.2.6 on 2025-09-23 09:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0056_fornecedor_provincia_tipomovimentostock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('PRODUTO_FINAL', 'Produto Final'), ('PRODUTO_COMPRADO', 'Produto Comprado'), ('SERVICO', 'Serviço')], default='PRODUTO_FINAL', help_text='Tipo do produto', max_length=20),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do material', max_length=200)),
                ('codigo', models.CharField(help_text='Código único do material', max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras do material', max_length=50)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do material')),
                ('tipo', models.CharField(choices=[('MATERIA_PRIMA', 'Matéria-Prima'), ('INSUMO', 'Insumo'), ('COMPONENTE', 'Componente'), ('EMBALAGEM', 'Embalagem'), ('ACESSORIO', 'Acessório'), ('FERRAMENTA', 'Ferramenta'), ('EQUIPAMENTO', 'Equipamento'), ('OUTRO', 'Outro')], default='MATERIA_PRIMA', help_text='Tipo do material', max_length=20)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('PC', 'Peça'), ('DZ', 'Dúzia'), ('GR', 'Grosa'), ('ROL', 'Rolo'), ('FOL', 'Folha'), ('BAR', 'Barra'), ('TUB', 'Tubo')], default='UN', help_text='Unidade de medida do material', max_length=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, help_text='Preço de custo do material', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estoque_minimo', models.PositiveIntegerField(default=0, help_text='Quantidade mínima em estoque')),
                ('estoque_maximo', models.PositiveIntegerField(default=0, help_text='Quantidade máxima em estoque')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('ESGOTADO', 'Esgotado'), ('DESCONTINUADO', 'Descontinuado')], default='ATIVO', help_text='Status do material', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro do material')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o material')),
                ('categoria', models.ForeignKey(help_text='Categoria do material', on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='empresa.categoriaproduto')),
                ('fornecedor_principal', models.ForeignKey(blank=True, help_text='Fornecedor principal do material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_principais', to='empresa.fornecedor')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da receita', max_length=200)),
                ('codigo', models.CharField(help_text='Código único da receita', max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da receita')),
                ('versao', models.CharField(default='1.0', help_text='Versão da receita', max_length=10)),
                ('rendimento', models.PositiveIntegerField(default=1, help_text='Quantidade de produtos produzidos por lote')),
                ('tempo_producao_minutos', models.PositiveIntegerField(default=0, help_text='Tempo de produção em minutos')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('TESTE', 'Em Teste'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='ATIVA', help_text='Status da receita', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação da receita')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a receita')),
                ('produto', models.ForeignKey(help_text='Produto que será produzido', on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='empresa.produto')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['produto__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade do material necessária', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('PC', 'Peça'), ('DZ', 'Dúzia'), ('GR', 'Grosa'), ('ROL', 'Rolo'), ('FOL', 'Folha'), ('BAR', 'Barra'), ('TUB', 'Tubo')], help_text='Unidade de medida', max_length=10)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre este item')),
                ('material', models.ForeignKey(help_text='Material utilizado', on_delete=django.db.models.deletion.CASCADE, related_name='receitas_utilizadas', to='empresa.material')),
                ('receita', models.ForeignKey(help_text='Receita', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresa.receita')),
            ],
            options={
                'verbose_name': 'Item da Receita',
                'verbose_name_plural': 'Itens da Receita',
                'unique_together': {('receita', 'material')},
            },
        ),
        migrations.CreateModel(
            name='StockMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade atual em estoque', max_digits=10)),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade reservada para produção', max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('material', models.ForeignKey(help_text='Material', on_delete=django.db.models.deletion.CASCADE, related_name='stocks_sucursais', to='empresa.material')),
                ('sucursal', models.ForeignKey(help_text='Sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='stocks_materiais', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Stock de Material',
                'verbose_name_plural': 'Stocks de Materiais',
                'unique_together': {('material', 'sucursal')},
            },
        ),
    ]
