# Generated by Django 5.2.6 on 2025-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0057_produto_tipo_material_receita_itemreceita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='tipo',
            field=models.CharField(choices=[('PRODUTO', 'Produto'), ('MATERIAL', 'Material'), ('AMBOS', 'Produto e Material')], default='AMBOS', help_text='Tipo de categoria (Produto, Material ou Ambos)', max_length=10),
        ),
    ]
