# Generated by Django 5.2.6 on 2025-09-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0058_alter_categoriaproduto_options_categoriaproduto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproduto',
            name='tipo',
            field=models.CharField(choices=[('PRODUTO', 'Produto'), ('MATERIAL', 'Material'), ('SERVICO', 'Serviço'), ('AMBOS', 'Produto e Material'), ('TODOS', 'Todos (Produto, Material e Serviço)')], default='AMBOS', help_text='Tipo de categoria (Produto, Material ou Ambos)', max_length=10),
        ),
    ]
