# Generated by Django 5.2.6 on 2025-09-23 12:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0059_alter_categoriaproduto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal', max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='desconto_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto padrão em percentagem', max_digits=5),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Limite de crédito em MT', max_digits=12),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='pais',
            field=models.CharField(default='Moçambique', help_text='País', max_length=50),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazo_pagamento',
            field=models.PositiveIntegerField(default=0, help_text='Prazo de pagamento em dias'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso')], default='ATIVO', help_text='Status do fornecedor', max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='website',
            field=models.URLField(blank=True, help_text='Website do fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade', max_length=100),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contato', max_length=254),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço completo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nuit',
            field=models.CharField(blank=True, help_text='Número de Identificação Única do Trabalhador (NUIT)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='provincia',
            field=models.CharField(blank=True, help_text='Província', max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número de telefone com código do país (+258)', max_length=13),
        ),
    ]
