# Generated by Django 5.2.6 on 2025-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0060_fornecedor_codigo_postal_fornecedor_desconto_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='unidade_rendimento',
            field=models.CharField(default='UN', help_text='Unidade de medida do rendimento', max_length=20),
        ),
    ]
