# Generated by Django 5.2.6 on 2025-09-23 12:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0061_receita_unidade_rendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='tempo_producao_minutos',
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_producao_horas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tempo de produção em horas', max_digits=5),
        ),
    ]
