# Generated by Django 5.2.6 on 2025-09-23 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0062_remove_receita_tempo_producao_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_geral', models.BooleanField(default=False, help_text='Acesso total a todas as sucursais', verbose_name='Administrador Geral')),
                ('permissoes_stock', models.BooleanField(default=True, help_text='Pode acessar módulo de stock', verbose_name='Acesso ao Stock')),
                ('permissoes_rh', models.BooleanField(default=True, help_text='Pode acessar módulo de RH', verbose_name='Acesso ao RH')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to='empresa.funcionario', verbose_name='Funcionário')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='empresa.sucursal', verbose_name='Sucursal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['usuario__username'],
            },
        ),
    ]
