# Generated by Django 5.2.6 on 2025-09-23 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0063_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da transferência', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status da transferência', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a transferência')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, help_text='Usuário que confirmou o recebimento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_stock_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(help_text='Usuário que criou a transferência', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_stock_criadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal_destino', models.ForeignKey(help_text='Sucursal de destino', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='empresa.sucursal')),
                ('sucursal_origem', models.ForeignKey(help_text='Sucursal de origem', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Transferência de Stock',
                'verbose_name_plural': 'Transferências de Stock',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField(help_text='Quantidade solicitada para transferência')),
                ('quantidade_recebida', models.PositiveIntegerField(default=0, help_text='Quantidade efetivamente recebida')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre este item')),
                ('produto', models.ForeignKey(help_text='Produto a ser transferido', on_delete=django.db.models.deletion.CASCADE, to='empresa.produto')),
                ('transferencia', models.ForeignKey(help_text='Transferência a que pertence este item', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresa.transferenciastock')),
            ],
            options={
                'verbose_name': 'Item de Transferência',
                'verbose_name_plural': 'Itens de Transferência',
                'unique_together': {('transferencia', 'produto')},
            },
        ),
    ]
