# Generated by Django 5.2.6 on 2025-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0064_transferenciastock_itemtransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciastock',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', help_text='Status da transferência', max_length=20),
        ),
    ]
