# Generated by Django 5.2.6 on 2025-09-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0065_alter_transferenciastock_status'),
    ]

    operations = [
    ]
