# Generated by Django 5.2.6 on 2025-09-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0067_remove_material_reference'),
    ]

    operations = [
    ]
