# Generated by Django 5.2.6 on 2025-10-01 09:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0070_merge_20250929_1134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentostock',
            options={'ordering': ['-data_movimento'], 'verbose_name': 'Movimento de Stock (Produto)', 'verbose_name_plural': 'Movimentos de Stock (Produtos)'},
        ),
        migrations.CreateModel(
            name='MovimentoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade movimentada')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço unitário do material no movimento', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do movimento', max_digits=12)),
                ('data_movimento', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do movimento')),
                ('referencia', models.CharField(blank=True, help_text='Referência do movimento (ex: número da nota fiscal)', max_length=100)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o movimento')),
                ('material', models.ForeignKey(help_text='Material movimentado', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='empresa.material')),
                ('sucursal', models.ForeignKey(help_text='Sucursal onde ocorreu o movimento', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_material', to='empresa.sucursal')),
                ('tipo_movimento', models.ForeignKey(help_text='Tipo de movimento', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_material', to='empresa.tipomovimentostock')),
                ('usuario', models.ForeignKey(help_text='Usuário que registrou o movimento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento de Stock (Material)',
                'verbose_name_plural': 'Movimentos de Stock (Materiais)',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
