# Generated by Django 5.2.6 on 2025-10-01 09:33

from django.db import migrations, models


def update_codigos(apps, schema_editor):
    """Atualiza códigos únicos para movimentações existentes"""
    MovimentoStock = apps.get_model('empresa', 'MovimentoStock')
    MovimentoMaterial = apps.get_model('empresa', 'MovimentoMaterial')
    
    # Atualizar códigos para MovimentoStock
    for i, movimento in enumerate(MovimentoStock.objects.all(), 1):
        movimento.codigo = f"MOV{i:04d}"
        movimento.save()
    
    # Atualizar códigos para MovimentoMaterial
    total_stock = MovimentoStock.objects.count()
    for i, movimento in enumerate(MovimentoMaterial.objects.all(), total_stock + 1):
        movimento.codigo = f"MOV{i:04d}"
        movimento.save()


def reverse_update_codigos(apps, schema_editor):
    """Reverte códigos para TEMP"""
    MovimentoStock = apps.get_model('empresa', 'MovimentoStock')
    MovimentoMaterial = apps.get_model('empresa', 'MovimentoMaterial')
    
    MovimentoStock.objects.all().update(codigo='TEMP')
    MovimentoMaterial.objects.all().update(codigo='TEMP')


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0071_alter_movimentostock_options_movimentomaterial'),
    ]

    operations = [
        # Adicionar campo sem unique primeiro
        migrations.AddField(
            model_name='movimentomaterial',
            name='codigo',
            field=models.CharField(default='TEMP', help_text='Código único da movimentação', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentostock',
            name='codigo',
            field=models.CharField(default='TEMP', help_text='Código único da movimentação', max_length=20),
        ),
        
        # Atualizar códigos únicos
        migrations.RunPython(update_codigos, reverse_update_codigos),
        
        # Adicionar constraint unique
        migrations.AlterField(
            model_name='movimentomaterial',
            name='codigo',
            field=models.CharField(help_text='Código único da movimentação', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='movimentostock',
            name='codigo',
            field=models.CharField(help_text='Código único da movimentação', max_length=20, unique=True),
        ),
    ]