# Generated by Django 5.2.6 on 2025-10-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0074_migrate_data_to_unified_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemtransferencia',
            unique_together={('transferencia', 'produto')},
        ),
        migrations.AddField(
            model_name='itemtransferencia',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Item a ser transferido (produto ou material)', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.item'),
        ),
        migrations.AlterField(
            model_name='itemtransferencia',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Produto a ser transferido (sistema antigo)', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtransferencia',
            unique_together={('transferencia', 'item'), ('transferencia', 'produto')},
        ),
    ]
