# Generated by Django 5.2.6 on 2025-10-01 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0075_update_transferencias_unified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da requisição', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', help_text='Status da requisição', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a requisição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_atendimento', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, help_text='Usuário que aprovou a requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_stock_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(help_text='Usuário que criou a requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_stock_criadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal_destino', models.ForeignKey(help_text='Sucursal que fornece', on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_recebidas', to='empresa.sucursal')),
                ('sucursal_origem', models.ForeignKey(help_text='Sucursal que solicita', on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_enviadas', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Requisição de Stock',
                'verbose_name_plural': 'Requisições de Stock',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicaoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField(help_text='Quantidade solicitada')),
                ('quantidade_atendida', models.PositiveIntegerField(default=0, help_text='Quantidade efetivamente atendida')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre este item')),
                ('item', models.ForeignKey(blank=True, help_text='Item solicitado (produto ou material)', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.item')),
                ('produto', models.ForeignKey(blank=True, help_text='Produto solicitado (sistema antigo)', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.produto')),
                ('requisicao', models.ForeignKey(help_text='Requisição a que pertence este item', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresa.requisicaostock')),
            ],
            options={
                'verbose_name': 'Item de Requisição',
                'verbose_name_plural': 'Itens de Requisição',
                'unique_together': {('requisicao', 'item'), ('requisicao', 'produto')},
            },
        ),
    ]
