# Generated by Django 5.2.6 on 2025-10-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0077_requisicaocompraexterna_itemrequisicaocompraexterna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequisicaocompraexterna',
            name='preco_unitario_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço unitário estimado para compra (opcional)', max_digits=10, null=True),
        ),
    ]
