# Generated by Django 5.2.6 on 2025-10-01 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0078_make_preco_optional_compra_externa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaostock',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, help_text='Sucursal que fornece (será definida por item)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_recebidas', to='empresa.sucursal'),
        ),
    ]
