# Generated by Django 5.2.6 on 2025-10-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0079_make_sucursal_destino_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fornecedorproduto',
            unique_together={('fornecedor', 'produto')},
        ),
        migrations.AddField(
            model_name='fornecedorproduto',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Material fornecido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='empresa.material'),
        ),
        migrations.AlterField(
            model_name='fornecedorproduto',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Produto fornecido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='empresa.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='fornecedorproduto',
            unique_together={('fornecedor', 'material'), ('fornecedor', 'produto')},
        ),
    ]
