# Generated by Django 5.2.6 on 2025-10-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0080_update_fornecedor_produto_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da ordem', max_length=20, unique=True)),
                ('numero_cotacao', models.CharField(help_text='Número da cotação do fornecedor', max_length=50)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('APROVADA', 'Aprovada'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais')),
                ('criado_por', models.ForeignKey(help_text='Usuário que criou a ordem', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(help_text='Fornecedor', on_delete=django.db.models.deletion.CASCADE, to='empresa.fornecedor')),
                ('requisicao_origem', models.ForeignKey(help_text='Requisição que originou esta ordem', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_compra', to='empresa.requisicaocompraexterna')),
                ('sucursal_destino', models.ForeignKey(help_text='Sucursal que receberá os produtos', on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Ordem de Compra',
                'verbose_name_plural': 'Ordens de Compra',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, help_text='Quantidade solicitada na ordem', max_digits=10)),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade efetivamente recebida', max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço unitário acordado', max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, help_text='Preço total do item', max_digits=12)),
                ('material', models.ForeignKey(blank=True, help_text='Material', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.material')),
                ('produto', models.ForeignKey(blank=True, help_text='Produto', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.produto')),
                ('ordem_compra', models.ForeignKey(help_text='Ordem de compra', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresa.ordemcompra')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Compra',
                'verbose_name_plural': 'Itens da Ordem de Compra',
                'unique_together': {('ordem_compra', 'material'), ('ordem_compra', 'produto')},
            },
        ),
    ]
