# Generated by Django 5.2.6 on 2025-10-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0083_fix_sucursal_field'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE empresa_ordemcompra DROP CONSTRAINT empresa_ordemcompra_requisicao_compra_id_c9da4a92_fk_empresa_r;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "ALTER TABLE empresa_ordemcompra ADD CONSTRAINT empresa_ordemcompra_requisicao_origem_id_fk_empresa_r FOREIGN KEY (requisicao_origem_id) REFERENCES empresa_requisicaocompraexterna(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE empresa_ordemcompra DROP CONSTRAINT empresa_ordemcompra_requisicao_origem_id_fk_empresa_r;"
        ),
    ]
