# Generated by Django 5.2.6 on 2025-10-07 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0084_fix_ordem_compra_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreceita',
            name='material',
            field=models.ForeignKey(help_text='Material utilizado', on_delete=django.db.models.deletion.CASCADE, related_name='receitas_utilizadas', to='empresa.item'),
        ),
        migrations.AlterField(
            model_name='stockmaterial',
            name='material',
            field=models.ForeignKey(help_text='Material', on_delete=django.db.models.deletion.CASCADE, related_name='stocks_material_antigo', to='empresa.item'),
        ),
        migrations.AlterField(
            model_name='fornecedorproduto',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Material fornecido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_material', to='empresa.item'),
        ),
        migrations.AlterField(
            model_name='movimentomaterial',
            name='material',
            field=models.ForeignKey(help_text='Material movimentado', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_material', to='empresa.item'),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor_principal',
        ),
        migrations.AlterField(
            model_name='receita',
            name='produto',
            field=models.ForeignKey(help_text='Produto que será produzido', on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='empresa.item'),
        ),
        migrations.AlterField(
            model_name='fornecedorproduto',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Produto fornecido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_produto', to='empresa.item'),
        ),
        migrations.AlterField(
            model_name='movimentostock',
            name='produto',
            field=models.ForeignKey(help_text='Produto movimentado', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_stock', to='empresa.item'),
        ),
        migrations.AlterField(
            model_name='stocksucursal',
            name='produto',
            field=models.ForeignKey(help_text='Produto', on_delete=django.db.models.deletion.CASCADE, related_name='stocks_sucursal_antigo', to='empresa.item'),
        ),
        migrations.AlterField(
            model_name='itemordemcompra',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Produto', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemordemcompra',
            unique_together={('ordem_compra', 'produto')},
        ),
        migrations.AlterUniqueTogether(
            name='itemrequisicaocompraexterna',
            unique_together={('requisicao', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='itemrequisicaostock',
            unique_together={('requisicao', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='itemtransferencia',
            unique_together={('transferencia', 'item')},
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='categoria',
            field=models.CharField(default='Geral', help_text='Categoria do item', max_length=100),
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='descricao',
            field=models.CharField(default='Item sem descrição', help_text='Descrição do item', max_length=200),
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='especificacoes',
            field=models.TextField(default='Sem especificações', help_text='Especificações técnicas'),
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='observacoes',
            field=models.TextField(default='', help_text='Observações sobre o item'),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='contato_externo',
            field=models.CharField(default='N/A', help_text='Nome do contato externo', max_length=100),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='cotacao_aprovada',
            field=models.TextField(default='', help_text='Cotação aprovada'),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='data_cotacao',
            field=models.DateTimeField(blank=True, help_text='Data da cotação', null=True),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='data_fatura',
            field=models.DateField(blank=True, help_text='Data da fatura', null=True),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='email_externo',
            field=models.CharField(default='N/A', help_text='Email do contato externo', max_length=100),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='empresa_externa',
            field=models.CharField(default='N/A', help_text='Nome da empresa externa', max_length=100),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='numero_fatura',
            field=models.CharField(default='PENDENTE', help_text='Número da fatura', max_length=50),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='telefone_externo',
            field=models.CharField(default='N/A', help_text='Telefone do contato externo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='tipo',
            field=models.CharField(default='COMPRA_EXTERNA', help_text='Tipo da ordem', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemordemcompra',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço unitário acordado', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemordemcompra',
            name='quantidade_recebida',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade efetivamente recebida'),
        ),
        migrations.AlterField(
            model_name='itemordemcompra',
            name='quantidade_solicitada',
            field=models.PositiveIntegerField(help_text='Quantidade solicitada na ordem'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou a ordem', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Fornecedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.fornecedor'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='observacoes',
            field=models.TextField(help_text='Observações adicionais'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='requisicao_origem',
            field=models.ForeignKey(blank=True, help_text='Requisição que originou esta ordem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_compra', to='empresa.requisicaocompraexterna'),
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='preco_total',
        ),
        migrations.RemoveField(
            model_name='itemrequisicaocompraexterna',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemrequisicaostock',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemtransferencia',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
