# Generated by Django 5.2.6 on 2025-10-07 10:42

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0084_fix_ordem_compra_constraint'),
    ]

    operations = [
        # Adicionar campos obrigatórios ao OrdemCompra
        migrations.AddField(
            model_name='ordemcompra',
            name='contato_externo',
            field=models.CharField(default='N/A', help_text='Nome do contato externo', max_length=100),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='empresa_externa',
            field=models.CharField(default='N/A', help_text='Nome da empresa externa', max_length=100),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='email_externo',
            field=models.CharField(default='N/A', help_text='Email do contato externo', max_length=100),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='telefone_externo',
            field=models.CharField(default='N/A', help_text='Telefone do contato externo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='tipo',
            field=models.CharField(default='COMPRA_EXTERNA', help_text='Tipo da ordem', max_length=50),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='cotacao_aprovada',
            field=models.TextField(default='', help_text='Cotação aprovada'),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='numero_fatura',
            field=models.CharField(default='PENDENTE', help_text='Número da fatura', max_length=50),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='data_cotacao',
            field=models.DateTimeField(blank=True, help_text='Data da cotação', null=True),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='data_fatura',
            field=models.DateField(blank=True, help_text='Data da fatura', null=True),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='ordens_aprovadas', to='auth.user'),
        ),
        
        # Adicionar campos obrigatórios ao ItemOrdemCompra
        migrations.AddField(
            model_name='itemordemcompra',
            name='categoria',
            field=models.CharField(default='Geral', help_text='Categoria do item', max_length=100),
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='descricao',
            field=models.CharField(default='Item sem descrição', help_text='Descrição do item', max_length=200),
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='especificacoes',
            field=models.TextField(default='Sem especificações', help_text='Especificações técnicas'),
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='observacoes',
            field=models.TextField(default='', help_text='Observações sobre o item'),
        ),
    ]
