# Generated by Django 5.2.6 on 2025-10-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0085_alter_itemreceita_material_and_more'),
        ('empresa', '0086_fix_ordem_compra_fields'),
    ]

    operations = [
    ]
