# Generated by Django 5.2.6 on 2025-10-07 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0087_merge_20251007_1250'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(help_text='Email do destinatário', max_length=254)),
                ('assunto', models.CharField(help_text='Assunto do email', max_length=200)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALHOU', 'Falhou'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('mensagem_erro', models.TextField(blank=True, help_text='Mensagem de erro se falhou', null=True)),
                ('sendgrid_message_id', models.CharField(blank=True, help_text='ID da mensagem no SendGrid', max_length=100, null=True)),
                ('anexo_pdf', models.FileField(blank=True, help_text='PDF anexado', null=True, upload_to='emails/pdfs/')),
                ('enviado_por', models.ForeignKey(help_text='Usuário que enviou', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordem_compra', models.ForeignKey(help_text='Ordem de compra relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='historico_envios', to='empresa.ordemcompra')),
            ],
            options={
                'verbose_name': 'Histórico de Envio de Email',
                'verbose_name_plural': 'Histórico de Envios de Email',
                'ordering': ['-data_envio'],
            },
        ),
    ]
