# Generated by Django 5.2.6 on 2025-10-07 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0088_historicoenvioemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_baixo', 'Stock Baixo'), ('requisicao_pendente', 'Requisição Pendente'), ('movimentacao_sem_usuario', 'Movimentação sem Usuário'), ('requisicao_antiga', 'Requisição Antiga'), ('sistema', 'Sistema'), ('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro')], help_text='Tipo da notificação', max_length=30)),
                ('titulo', models.CharField(help_text='Título da notificação', max_length=200)),
                ('mensagem', models.TextField(help_text='Mensagem detalhada')),
                ('url', models.URLField(blank=True, help_text='URL para ação relacionada')),
                ('lida', models.BooleanField(default=False, help_text='Se a notificação foi lida')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação da notificação')),
                ('data_leitura', models.DateTimeField(blank=True, help_text='Data em que foi lida', null=True)),
                ('prioridade', models.IntegerField(default=1, help_text='Prioridade (1=baixa, 2=média, 3=alta, 4=crítica)')),
                ('dados_extras', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON')),
                ('usuario_destinatario', models.ForeignKey(blank=True, help_text='Usuário destinatário (null = todos)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação de Stock',
                'verbose_name_plural': 'Notificações de Stock',
                'ordering': ['-prioridade', '-data_criacao'],
            },
        ),
    ]
