# Generated by Django 5.2.6 on 2025-10-08 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0089_notificacaostock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do inventário', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome/descrição do inventário', max_length=200)),
                ('data_inicio', models.DateTimeField(help_text='Data e hora de início do inventário')),
                ('data_fim', models.DateTimeField(blank=True, help_text='Data e hora de conclusão do inventário', null=True)),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', help_text='Status do inventário', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o inventário')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação do inventário')),
                ('sucursal', models.ForeignKey(help_text='Sucursal onde será realizado o inventário', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_fisicos', to='empresa.sucursal')),
                ('usuario_criador', models.ForeignKey(help_text='Usuário que criou o inventário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsavel', models.ForeignKey(help_text='Usuário responsável pelo inventário', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventário Físico',
                'verbose_name_plural': 'Inventários Físicos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do ajuste', max_length=20, unique=True)),
                ('tipo_ajuste', models.CharField(choices=[('INVENTARIO', 'Inventário Físico'), ('PERDA', 'Perda'), ('DANIFICADO', 'Danificado'), ('VENCIDO', 'Vencido'), ('OUTROS', 'Outros')], default='INVENTARIO', help_text='Tipo do ajuste', max_length=20)),
                ('quantidade_anterior', models.PositiveIntegerField(help_text='Quantidade antes do ajuste')),
                ('quantidade_nova', models.PositiveIntegerField(help_text='Quantidade após o ajuste')),
                ('diferenca', models.IntegerField(help_text='Diferença (nova - anterior)')),
                ('motivo', models.TextField(help_text='Motivo do ajuste')),
                ('data_ajuste', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do ajuste')),
                ('aprovado', models.BooleanField(default=False, help_text='Se o ajuste foi aprovado')),
                ('data_aprovacao', models.DateTimeField(blank=True, help_text='Data de aprovação', null=True)),
                ('item', models.ForeignKey(help_text='Item ajustado', on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_inventario', to='empresa.item')),
                ('sucursal', models.ForeignKey(help_text='Sucursal do ajuste', on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_inventario', to='empresa.sucursal')),
                ('usuario_ajuste', models.ForeignKey(help_text='Usuário que fez o ajuste', on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_inventario', to=settings.AUTH_USER_MODEL)),
                ('usuario_aprovacao', models.ForeignKey(blank=True, help_text='Usuário que aprovou o ajuste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aprovados', to=settings.AUTH_USER_MODEL)),
                ('inventario', models.ForeignKey(blank=True, help_text='Inventário que gerou este ajuste', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='empresa.inventariofisico')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventário',
                'verbose_name_plural': 'Ajustes de Inventário',
                'ordering': ['-data_ajuste'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema', models.PositiveIntegerField(help_text='Quantidade registrada no sistema')),
                ('quantidade_contada', models.PositiveIntegerField(blank=True, help_text='Quantidade contada fisicamente', null=True)),
                ('diferenca', models.IntegerField(default=0, help_text='Diferença entre contado e sistema (contado - sistema)')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a contagem')),
                ('data_contagem', models.DateTimeField(blank=True, help_text='Data e hora da contagem', null=True)),
                ('inventario', models.ForeignKey(help_text='Inventário ao qual pertence este item', on_delete=django.db.models.deletion.CASCADE, related_name='itens_inventario', to='empresa.inventariofisico')),
                ('item', models.ForeignKey(help_text='Item sendo inventariado', on_delete=django.db.models.deletion.CASCADE, related_name='itens_inventario', to='empresa.item')),
                ('usuario_contador', models.ForeignKey(blank=True, help_text='Usuário que fez a contagem', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Inventário',
                'verbose_name_plural': 'Itens do Inventário',
                'ordering': ['item__nome'],
                'unique_together': {('inventario', 'item')},
            },
        ),
    ]
