# Generated by Django 5.2.6 on 2025-10-08 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0090_inventariofisico_ajusteinventario_iteminventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventario',
            name='contagem_finalizada',
            field=models.BooleanField(default=False, help_text='Indica se as 3 contagens foram finalizadas'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='numero_contagem',
            field=models.PositiveIntegerField(default=0, help_text='Número da contagem atual (1, 2 ou 3)'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='precisa_recontagem',
            field=models.BooleanField(default=False, help_text='Indica se o item precisa ser recontado'),
        ),
        migrations.CreateModel(
            name='HistoricoContagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contagem', models.PositiveIntegerField(help_text='Número da contagem (1, 2 ou 3)')),
                ('quantidade_contada', models.PositiveIntegerField(help_text='Quantidade contada nesta contagem')),
                ('diferenca', models.IntegerField(help_text='Diferença entre contado e sistema')),
                ('observacoes', models.TextField(blank=True, help_text='Observações desta contagem')),
                ('data_contagem', models.DateTimeField(help_text='Data e hora da contagem')),
                ('item_inventario', models.ForeignKey(help_text='Item do inventário', on_delete=django.db.models.deletion.CASCADE, related_name='historico_contagens', to='empresa.iteminventario')),
                ('usuario_contador', models.ForeignKey(help_text='Usuário que fez a contagem', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Contagem',
                'verbose_name_plural': 'Histórico de Contagens',
                'ordering': ['-data_contagem'],
            },
        ),
    ]
