# Generated by Django 5.2.6 on 2025-10-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0091_iteminventario_contagem_finalizada_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocksucursal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stocksucursal',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='stocksucursal',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='MovimentoMaterial',
        ),
        migrations.DeleteModel(
            name='StockSucursal',
        ),
    ]
