# Generated by Django 5.2.6 on 2025-10-09 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0092_remove_duplicate_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimentoitem',
            index=models.Index(fields=['item', 'sucursal'], name='empresa_mov_item_id_07cdaf_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoitem',
            index=models.Index(fields=['data_movimento'], name='empresa_mov_data_mo_11507d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoitem',
            index=models.Index(fields=['tipo_movimento'], name='empresa_mov_tipo_mo_c293b6_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoitem',
            index=models.Index(fields=['item', 'data_movimento'], name='empresa_mov_item_id_8089c8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoitem',
            index=models.Index(fields=['sucursal', 'data_movimento'], name='empresa_mov_sucursa_639d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['item', 'sucursal'], name='empresa_sto_item_id_2c23d1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['quantidade_atual'], name='empresa_sto_quantid_9ede3c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['data_atualizacao'], name='empresa_sto_data_at_a82021_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['item', 'quantidade_atual'], name='empresa_sto_item_id_8ed8b0_idx'),
        ),
    ]
