# Generated by Django 5.2.6 on 2025-10-09 12:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0093_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da transportadora', max_length=200)),
                ('codigo', models.CharField(help_text='Código único da transportadora', max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('TRANSPORTADORA', 'Transportadora'), ('ENTREGA_RAPIDA', 'Entrega Rápida'), ('CORREIOS', 'Correios'), ('MOTORISTA', 'Motorista Próprio'), ('TERCEIRIZADA', 'Terceirizada')], default='TRANSPORTADORA', help_text='Tipo de transportadora', max_length=20)),
                ('nuit', models.CharField(blank=True, help_text='Número de Identificação Única do Trabalhador (NUIT)', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email de contato', max_length=254)),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone com código do país (+258)', max_length=13)),
                ('website', models.URLField(blank=True, help_text='Website da transportadora')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo')),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('provincia', models.CharField(blank=True, help_text='Província', max_length=50)),
                ('prazo_entrega_padrao', models.PositiveIntegerField(default=1, help_text='Prazo de entrega padrão em dias')),
                ('custo_por_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo por quilograma em MT', max_digits=10)),
                ('custo_fixo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo fixo por entrega em MT', max_digits=10)),
                ('cobertura_provincias', models.JSONField(blank=True, default=list, help_text='Províncias cobertas pela transportadora')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('SUSPENSA', 'Suspensa')], default='ATIVA', help_text='Status da transportadora', max_length=20)),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a transportadora está ativa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro da transportadora')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a transportadora')),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RastreamentoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreamento', models.CharField(help_text='Código único de rastreamento', max_length=50, unique=True)),
                ('destinatario_nome', models.CharField(help_text='Nome do destinatário', max_length=200)),
                ('destinatario_telefone', models.CharField(blank=True, help_text='Telefone do destinatário', max_length=13)),
                ('endereco_entrega', models.TextField(help_text='Endereço de entrega')),
                ('cidade_entrega', models.CharField(help_text='Cidade de entrega', max_length=100)),
                ('provincia_entrega', models.CharField(help_text='Província de entrega', max_length=50)),
                ('status_atual', models.CharField(choices=[('PREPARANDO', 'Preparando'), ('COLETADO', 'Coletado'), ('EM_TRANSITO', 'Em Trânsito'), ('EM_DISTRIBUICAO', 'Em Distribuição'), ('ENTREGUE', 'Entregue'), ('DEVOLVIDO', 'Devolvido'), ('PERDIDO', 'Perdido'), ('CANCELADO', 'Cancelado')], default='PREPARANDO', help_text='Status atual da entrega', max_length=20)),
                ('data_coleta', models.DateTimeField(blank=True, help_text='Data e hora da coleta', null=True)),
                ('data_entrega_prevista', models.DateTimeField(blank=True, help_text='Data prevista para entrega', null=True)),
                ('data_entrega_realizada', models.DateTimeField(blank=True, help_text='Data e hora da entrega realizada', null=True)),
                ('peso_total', models.DecimalField(blank=True, decimal_places=3, help_text='Peso total em kg', max_digits=10, null=True)),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor declarado do envio', max_digits=12, null=True)),
                ('custo_envio', models.DecimalField(blank=True, decimal_places=2, help_text='Custo do envio', max_digits=10, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do rastreamento')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a entrega')),
                ('criado_por', models.ForeignKey(help_text='Usuário que criou o rastreamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rastreamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('ordem_compra', models.ForeignKey(blank=True, help_text='Ordem de compra relacionada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rastreamentos', to='empresa.ordemcompra')),
                ('transferencia', models.ForeignKey(blank=True, help_text='Transferência relacionada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rastreamentos', to='empresa.transferenciastock')),
                ('transportadora', models.ForeignKey(help_text='Transportadora responsável', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='empresa.transportadora')),
            ],
            options={
                'verbose_name': 'Rastreamento de Entrega',
                'verbose_name_plural': 'Rastreamentos de Entrega',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EventoRastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIADO', 'Criado'), ('COLETADO', 'Coletado'), ('EM_TRANSITO', 'Em Trânsito'), ('EM_DISTRIBUICAO', 'Em Distribuição'), ('TENTATIVA_ENTREGA', 'Tentativa de Entrega'), ('ENTREGUE', 'Entregue'), ('DEVOLVIDO', 'Devolvido'), ('PERDIDO', 'Perdido'), ('CANCELADO', 'Cancelado'), ('OBSERVACAO', 'Observação')], help_text='Tipo do evento', max_length=20)),
                ('descricao', models.TextField(help_text='Descrição do evento')),
                ('localizacao', models.CharField(blank=True, help_text='Localização onde ocorreu o evento', max_length=200)),
                ('data_evento', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do evento')),
                ('dados_extras', models.JSONField(blank=True, default=dict, help_text='Dados adicionais do evento')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que registrou o evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rastreamento', models.ForeignKey(help_text='Rastreamento relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='empresa.rastreamentoentrega')),
            ],
            options={
                'verbose_name': 'Evento de Rastreamento',
                'verbose_name_plural': 'Eventos de Rastreamento',
                'ordering': ['-data_evento'],
            },
        ),
    ]
