# Generated by Django 5.2.6 on 2025-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0094_transportadora_rastreamentoentrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='ano_fabricacao',
            field=models.PositiveIntegerField(blank=True, help_text='Ano de fabricação da viatura', null=True),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='capacidade_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade de carga em kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='categoria',
            field=models.CharField(blank=True, choices=[('CAMINHAO', 'Caminhão'), ('VAN', 'Van'), ('MOTO', 'Moto'), ('CARRO', 'Carro'), ('BICICLETA', 'Bicicleta'), ('ONIBUS', 'Ônibus')], help_text='Categoria da viatura (para viaturas internas)', max_length=20),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca da viatura', max_length=50),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo da viatura', max_length=100),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='motorista_responsavel',
            field=models.CharField(blank=True, help_text='Nome do motorista responsável', max_length=200),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='placa',
            field=models.CharField(blank=True, help_text='Placa da viatura (para viaturas internas)', max_length=10),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='proxima_revisao',
            field=models.DateField(blank=True, help_text='Data da próxima revisão', null=True),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='quilometragem_atual',
            field=models.PositiveIntegerField(default=0, help_text='Quilometragem atual da viatura'),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='telefone_motorista',
            field=models.CharField(blank=True, help_text='Telefone do motorista', max_length=13),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('SUSPENSA', 'Suspensa'), ('MANUTENCAO', 'Em Manutenção')], default='ATIVA', help_text='Status da transportadora', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='tipo',
            field=models.CharField(choices=[('TRANSPORTADORA', 'Transportadora Externa'), ('ENTREGA_RAPIDA', 'Entrega Rápida'), ('CORREIOS', 'Correios'), ('VIATURA_INTERNA', 'Viatura Interna'), ('MOTORISTA', 'Motorista Próprio'), ('TERCEIRIZADA', 'Terceirizada')], default='TRANSPORTADORA', help_text='Tipo de transportadora', max_length=20),
        ),
    ]
