# Generated by Django 5.2.6 on 2025-10-10 08:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0095_add_viatura_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do veículo', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome do veículo (ex: "Van de Entregas - Matola")', max_length=200)),
                ('categoria', models.CharField(choices=[('CAMINHAO', 'Caminhão'), ('VAN', 'Van'), ('MOTO', 'Moto'), ('CARRO', 'Carro'), ('BICICLETA', 'Bicicleta'), ('ONIBUS', 'Ônibus')], help_text='Categoria do veículo', max_length=20)),
                ('placa', models.CharField(help_text='Placa do veículo', max_length=10, unique=True)),
                ('marca', models.CharField(help_text='Marca do veículo', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo do veículo', max_length=100)),
                ('ano_fabricacao', models.PositiveIntegerField(help_text='Ano de fabricação do veículo')),
                ('capacidade_kg', models.DecimalField(decimal_places=2, help_text='Capacidade de carga em kg', max_digits=10)),
                ('quilometragem_atual', models.PositiveIntegerField(default=0, help_text='Quilometragem atual do veículo')),
                ('proxima_revisao', models.DateField(blank=True, help_text='Data da próxima revisão', null=True)),
                ('motorista_responsavel', models.CharField(help_text='Nome do motorista responsável', max_length=200)),
                ('telefone_motorista', models.CharField(help_text='Telefone do motorista', max_length=13)),
                ('custo_por_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo por quilômetro em MT', max_digits=10)),
                ('custo_fixo_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo fixo mensal em MT', max_digits=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Em Manutenção')], default='ATIVO', help_text='Status do veículo', max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o veículo está ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro do veículo')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o veículo')),
            ],
            options={
                'verbose_name': 'Veículo Interno',
                'verbose_name_plural': 'Veículos Internos',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='ano_fabricacao',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='capacidade_kg',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='motorista_responsavel',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='proxima_revisao',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='quilometragem_atual',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='telefone_motorista',
        ),
        migrations.AlterField(
            model_name='rastreamentoentrega',
            name='transportadora',
            field=models.ForeignKey(blank=True, help_text='Transportadora externa responsável', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='empresa.transportadora'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='tipo',
            field=models.CharField(choices=[('TRANSPORTADORA', 'Transportadora Externa'), ('ENTREGA_RAPIDA', 'Entrega Rápida'), ('CORREIOS', 'Correios'), ('MOTORISTA', 'Motorista Próprio'), ('TERCEIRIZADA', 'Terceirizada')], default='TRANSPORTADORA', help_text='Tipo de transportadora', max_length=20),
        ),
        migrations.AddField(
            model_name='rastreamentoentrega',
            name='veiculo_interno',
            field=models.ForeignKey(blank=True, help_text='Veículo interno responsável', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='empresa.veiculointerno'),
        ),
    ]
