# Generated by Django 5.2.6 on 2025-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0096_create_veiculo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculointerno',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único do veículo', max_length=20, unique=True),
        ),
    ]
