# Generated by Django 5.2.6 on 2025-10-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0097_alter_veiculointerno_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='horas_extras',
        ),
    ]
