# Generated by Django 5.2.6 on 2025-10-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0098_remove_horas_extras_from_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='ano_fabricacao',
            field=models.PositiveIntegerField(blank=True, help_text='Ano de fabricação do veículo', null=True),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='capacidade_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade de carga em kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='categoria_veiculo',
            field=models.CharField(blank=True, help_text='Categoria do veículo (Automóvel, Moto, Van, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca do veículo', max_length=50),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo do veículo', max_length=100),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='motorista_responsavel',
            field=models.CharField(blank=True, help_text='Nome do motorista responsável', max_length=200),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='placa',
            field=models.CharField(blank=True, help_text='Placa do veículo', max_length=10),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='proxima_revisao',
            field=models.DateField(blank=True, help_text='Data da próxima revisão', null=True),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='quilometragem_atual',
            field=models.PositiveIntegerField(blank=True, help_text='Quilometragem atual do veículo', null=True),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='telefone_motorista',
            field=models.CharField(blank=True, help_text='Telefone do motorista', max_length=13),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='tipo',
            field=models.CharField(choices=[('TRANSPORTADORA', 'Transportadora Externa'), ('ENTREGA_RAPIDA', 'Entrega Rápida'), ('CORREIOS', 'Correios'), ('MOTORISTA', 'Motorista Próprio'), ('TERCEIRIZADA', 'Terceirizada'), ('VIATURA_INTERNA', 'Viatura Interna')], default='TRANSPORTADORA', help_text='Tipo de transportadora', max_length=20),
        ),
    ]
