# Generated by Django 5.2.6 on 2025-10-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0099_add_vehicle_fields_to_transportadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal responsável pela viatura (apenas para viaturas internas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.sucursal'),
        ),
    ]
