# Generated by Django 5.2.6 on 2025-10-16 10:05

from django.db import migrations


def redistribute_vehicles_sucursals(apps, schema_editor):
    """
    Redistribui os veículos entre as sucursais de forma mais equilibrada
    """
    Transportadora = apps.get_model('empresa', 'Transportadora')
    Sucursal = apps.get_model('empresa', 'Sucursal')
    
    # Obter todas as sucursais ativas
    sucursais = list(Sucursal.objects.filter(ativa=True).order_by('id'))
    
    if not sucursais:
        print("Nenhuma sucursal ativa encontrada!")
        return
    
    # Obter todos os veículos
    viaturas = Transportadora.objects.filter(tipo='VIATURA_INTERNA').order_by('id')
    
    # Distribuição mais equilibrada baseada no tipo de veículo e função
    distribuicao = {
        # ID da viatura: ID da sucursal
        6: 19,   # LOJ-VAN-01 (Van de Entregas - Matola) -> LOJA DA MATOLA
        11: 7,   # SED-AUTO-01 (Carro Executivo) -> Sede - Conception  
        12: 20,  # LOJ-MOTO-01 (Moto de Entregas Rápidas) -> LOJA DE MARRACUENE
        13: 19,  # LOJ-VAN-02 (Van de Manutenção) -> LOJA DA MATOLA
        14: 7,   # LOJ-AUTO-01 (Carro Executivo) -> Sede - Conception
    }
    
    for viatura in viaturas:
        nova_sucursal_id = distribuicao.get(viatura.id)
        if nova_sucursal_id:
            nova_sucursal = Sucursal.objects.get(id=nova_sucursal_id)
            viatura.sucursal = nova_sucursal
            
            # Regenerar nome baseado na nova sucursal
            categoria_abrev = {
                'AUTOMOVEL': 'AUTO',
                'MOTOCICLETA': 'MOTO',
                'VAN': 'VAN',
                'CAMINHAO': 'CAM',
                'BICICLETA': 'BIC',
                'PICKUP': 'PIC',
                'CAMINHONETE': 'CAM',
                'ONIBUS': 'ONI',
                'AMBULANCIA': 'AMB',
            }
            
            abrev_categoria = categoria_abrev.get(viatura.categoria_veiculo, 'VEI')
            abrev_sucursal = nova_sucursal.nome[:3].upper()
            
            # Contar quantas viaturas já existem desta categoria nesta sucursal
            count = Transportadora.objects.filter(
                tipo='VIATURA_INTERNA',
                sucursal=nova_sucursal,
                categoria_veiculo=viatura.categoria_veiculo
            ).exclude(id=viatura.id).count()
            
            numero = count + 1
            novo_nome = f"{abrev_sucursal}-{abrev_categoria}-{numero:02d}"
            viatura.nome = novo_nome
            
            viatura.save()
            print(f"Redistribuído: {viatura.nome} -> {nova_sucursal.nome}")


def reverse_redistribution(apps, schema_editor):
    """
    Reverte a redistribuição (não fazemos nada específico)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0101_migrate_existing_vehicles'),
    ]

    operations = [
        migrations.RunPython(redistribute_vehicles_sucursals, reverse_redistribution),
    ]
