# Generated by Django 5.2.6 on 2025-10-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0105_balance_vehicles_distribution'),
    ]

    operations = [
    ]
