# Generated by Django 5.2.6 on 2025-10-16 12:35

from django.db import migrations


def update_motorista_telefones(apps, schema_editor):
    """Atualiza telefones dos motoristas com base nos funcionários cadastrados"""
    Transportadora = apps.get_model('empresa', 'Transportadora')
    Funcionario = apps.get_model('empresa', 'Funcionario')
    
    # Buscar todas as viaturas internas com motorista responsável
    viaturas = Transportadora.objects.filter(
        tipo='VIATURA_INTERNA',
        motorista_responsavel__isnull=False
    ).exclude(motorista_responsavel='')
    
    print(f"Atualizando telefones para {viaturas.count()} viaturas...")
    
    for viatura in viaturas:
        try:
            # Buscar funcionário pelo nome completo
            funcionario = Funcionario.objects.get(
                nome_completo=viatura.motorista_responsavel,
                status='AT'
            )
            
            # Usar telefone principal ou alternativo
            telefone = funcionario.telefone or funcionario.telefone_alternativo
            
            if telefone and telefone != viatura.telefone_motorista:
                viatura.telefone_motorista = telefone
                viatura.save()
                print(f"✓ {viatura.nome}: {viatura.motorista_responsavel} -> {telefone}")
            elif not telefone:
                print(f"⚠ {viatura.nome}: {viatura.motorista_responsavel} não tem telefone cadastrado")
                
        except Funcionario.DoesNotExist:
            print(f"✗ {viatura.nome}: Funcionário '{viatura.motorista_responsavel}' não encontrado")
        except Exception as e:
            print(f"✗ {viatura.nome}: Erro ao atualizar telefone - {e}")


def reverse_update_motorista_telefones(apps, schema_editor):
    """Reverter atualização de telefones"""
    # Não há necessidade de reverter, pois apenas atualizamos dados existentes
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0106_redistribute_viaturas_balanced'),
    ]

    operations = [
        migrations.RunPython(update_motorista_telefones, reverse_update_motorista_telefones),
    ]