# Generated by Django 5.2.6 on 2025-10-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0107_update_motorista_telefones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadora',
            name='tipo',
            field=models.CharField(choices=[('TRANSPORTADORA', 'Transportadora Externa'), ('ENTREGA_RAPIDA', 'Entrega Rápida'), ('CORREIOS', 'Correios'), ('MOTORISTA', 'Motorista Próprio'), ('TERCEIRIZADA', 'Terceirizada'), ('VIATURA_INTERNA_ENTREGA', 'Viatura Interna - Entregas'), ('VIATURA_INTERNA_EXECUTIVO', 'Viatura Interna - Executivo')], default='TRANSPORTADORA', help_text='Tipo de transportadora', max_length=30),
        ),
    ]
