# Generated by Django 5.0.8 on 2025-01-27

from django.db import migrations

def fix_requisicoes_sem_destino(apps, schema_editor):
    """Corrigir requisições sem sucursal destino"""
    RequisicaoStock = apps.get_model('empresa', 'RequisicaoStock')
    Sucursal = apps.get_model('empresa', 'Sucursal')
    
    # Buscar requisições sem sucursal destino
    requisicoes_sem_destino = RequisicaoStock.objects.filter(sucursal_destino__isnull=True)
    
    print(f"Corrigindo {requisicoes_sem_destino.count()} requisicoes sem sucursal destino...")
    
    # Obter todas as sucursais ativas
    sucursais = Sucursal.objects.filter(ativa=True)
    
    if not sucursais.exists():
        print("Nenhuma sucursal ativa encontrada!")
        return
    
    # Para cada requisição sem destino, atribuir uma sucursal diferente da origem
    for i, requisicao in enumerate(requisicoes_sem_destino):
        # Encontrar uma sucursal diferente da origem
        sucursal_destino = sucursais.exclude(id=requisicao.sucursal_origem_id).first()
        
        if sucursal_destino:
            requisicao.sucursal_destino = sucursal_destino
            requisicao.save(update_fields=['sucursal_destino'])
            print(f"OK {requisicao.codigo}: {requisicao.sucursal_origem.nome} -> {sucursal_destino.nome}")
        else:
            print(f"ERRO {requisicao.codigo}: Nao foi possivel encontrar sucursal destino")
    
    print("Correcao concluida!")

def reverse_fix_requisicoes_sem_destino(apps, schema_editor):
    """Reverter correção - definir sucursal destino como None"""
    RequisicaoStock = apps.get_model('empresa', 'RequisicaoStock')
    
    # Reverter para None (não recomendado, mas necessário para rollback)
    requisicoes = RequisicaoStock.objects.all()
    for requisicao in requisicoes:
        requisicao.sucursal_destino = None
        requisicao.save(update_fields=['sucursal_destino'])
    
    print("Correcao revertida!")

class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0107_update_motorista_telefones'),
    ]

    operations = [
        migrations.RunPython(fix_requisicoes_sem_destino, reverse_fix_requisicoes_sem_destino),
    ]
