# Generated by Django 5.2.6 on 2025-10-17 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0108_alter_transportadora_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoTransferenciaLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status da notificação logística', max_length=20)),
                ('tipo_transporte', models.CharField(blank=True, choices=[('VEICULO_INTERNO', 'Veículo Interno'), ('TRANSPORTADORA_EXTERNA', 'Transportadora Externa')], help_text='Tipo de transporte escolhido', max_length=30, null=True)),
                ('data_notificacao', models.DateTimeField(auto_now_add=True, help_text='Data da notificação')),
                ('data_atribuicao', models.DateTimeField(blank=True, help_text='Data em que foi atribuída ao transporte', null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data de conclusão do transporte', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o transporte')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', help_text='Prioridade da transferência', max_length=20)),
                ('transferencia', models.OneToOneField(help_text='Transferência que precisa de transporte', on_delete=django.db.models.deletion.CASCADE, related_name='notificacao_logistica', to='empresa.transferenciastock')),
                ('transportadora_externa', models.ForeignKey(blank=True, help_text='Transportadora externa escolhida', limit_choices_to={'tipo__in': ['TRANSPORTADORA', 'ENTREGA_RAPIDA', 'CORREIOS', 'MOTORISTA', 'TERCEIRIZADA']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_externas', to='empresa.transportadora')),
                ('usuario_atribuicao', models.ForeignKey(blank=True, help_text='Usuário que atribuiu o transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_logistica_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_notificacao', models.ForeignKey(blank=True, help_text='Usuário que criou a notificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_logistica_criadas', to=settings.AUTH_USER_MODEL)),
                ('veiculo_interno', models.ForeignKey(blank=True, help_text='Veículo interno escolhido', limit_choices_to={'tipo__in': ['VIATURA_INTERNA_ENTREGA', 'VIATURA_INTERNA_EXECUTIVO']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_internas', to='empresa.transportadora')),
            ],
            options={
                'verbose_name': 'Notificação de Transferência Logística',
                'verbose_name_plural': 'Notificações de Transferências Logísticas',
                'ordering': ['-data_notificacao'],
                'indexes': [models.Index(fields=['status'], name='empresa_not_status_e5bb10_idx'), models.Index(fields=['data_notificacao'], name='empresa_not_data_no_fa83e9_idx'), models.Index(fields=['prioridade'], name='empresa_not_priorid_c10f2d_idx')],
            },
        ),
    ]
