# Generated by Django 5.2.6 on 2025-10-17 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0109_add_notificacao_transferencia_logistica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoColetaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('COLETADA', 'Coletada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status da notificação de coleta', max_length=20)),
                ('tipo_transporte', models.CharField(blank=True, choices=[('VEICULO_INTERNO', 'Veículo Interno'), ('TRANSPORTADORA_EXTERNA', 'Transportadora Externa')], help_text='Tipo de transporte escolhido', max_length=30, null=True)),
                ('data_notificacao', models.DateTimeField(auto_now_add=True, help_text='Data da notificação')),
                ('data_atribuicao', models.DateTimeField(blank=True, help_text='Data em que foi atribuída ao transporte', null=True)),
                ('data_coleta', models.DateTimeField(blank=True, help_text='Data de coleta realizada', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a coleta')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', help_text='Prioridade da coleta', max_length=20)),
                ('ordem_compra', models.OneToOneField(help_text='Ordem de compra que precisa de coleta', on_delete=django.db.models.deletion.CASCADE, related_name='notificacao_coleta', to='empresa.ordemcompra')),
                ('transportadora_externa', models.ForeignKey(blank=True, help_text='Transportadora externa escolhida', limit_choices_to={'tipo__in': ['TRANSPORTADORA', 'ENTREGA_RAPIDA', 'CORREIOS', 'MOTORISTA', 'TERCEIRIZADA']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coletas_externas', to='empresa.transportadora')),
                ('usuario_atribuicao', models.ForeignKey(blank=True, help_text='Usuário que atribuiu o transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_coleta_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_notificacao', models.ForeignKey(blank=True, help_text='Usuário que criou a notificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_coleta_criadas', to=settings.AUTH_USER_MODEL)),
                ('veiculo_interno', models.ForeignKey(blank=True, help_text='Veículo interno escolhido', limit_choices_to={'tipo__in': ['VIATURA_INTERNA_ENTREGA', 'VIATURA_INTERNA_EXECUTIVO']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coletas_internas', to='empresa.transportadora')),
            ],
            options={
                'verbose_name': 'Notificação de Coleta de Compra',
                'verbose_name_plural': 'Notificações de Coletas de Compras',
                'ordering': ['-data_notificacao'],
                'indexes': [models.Index(fields=['status'], name='empresa_not_status_048659_idx'), models.Index(fields=['data_notificacao'], name='empresa_not_data_no_644cd6_idx'), models.Index(fields=['prioridade'], name='empresa_not_priorid_1a6896_idx')],
            },
        ),
    ]
