# Generated by Django 5.2.6 on 2025-10-17 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0110_add_notificacao_coleta_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaotransferencialogistica',
            name='transferencia',
        ),
        migrations.RemoveField(
            model_name='notificacaotransferencialogistica',
            name='transportadora_externa',
        ),
        migrations.RemoveField(
            model_name='notificacaotransferencialogistica',
            name='usuario_atribuicao',
        ),
        migrations.RemoveField(
            model_name='notificacaotransferencialogistica',
            name='usuario_notificacao',
        ),
        migrations.RemoveField(
            model_name='notificacaotransferencialogistica',
            name='veiculo_interno',
        ),
        migrations.CreateModel(
            name='NotificacaoLogisticaUnificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('TRANSFERENCIA', 'Transferência Interna'), ('COLETA', 'Coleta de Compra')], help_text='Tipo de operação logística', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status da notificação logística', max_length=20)),
                ('tipo_transporte', models.CharField(blank=True, choices=[('VEICULO_INTERNO', 'Veículo Interno'), ('TRANSPORTADORA_EXTERNA', 'Transportadora Externa')], help_text='Tipo de transporte escolhido', max_length=30, null=True)),
                ('data_notificacao', models.DateTimeField(auto_now_add=True, help_text='Data da notificação')),
                ('data_atribuicao', models.DateTimeField(blank=True, help_text='Data em que foi atribuída ao transporte', null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data de conclusão da operação', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a operação')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', help_text='Prioridade da operação', max_length=20)),
                ('ordem_compra', models.OneToOneField(blank=True, help_text='Ordem de compra relacionada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacao_logistica_unificada', to='empresa.ordemcompra')),
                ('transferencia', models.OneToOneField(blank=True, help_text='Transferência relacionada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacao_logistica_unificada', to='empresa.transferenciastock')),
                ('transportadora_externa', models.ForeignKey(blank=True, help_text='Transportadora externa escolhida', limit_choices_to={'tipo__in': ['TRANSPORTADORA', 'ENTREGA_RAPIDA', 'CORREIOS', 'MOTORISTA', 'TERCEIRIZADA']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_externas', to='empresa.transportadora')),
                ('usuario_atribuicao', models.ForeignKey(blank=True, help_text='Usuário que atribuiu o transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_logistica_unificada_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_notificacao', models.ForeignKey(blank=True, help_text='Usuário que criou a notificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_logistica_unificada_criadas', to=settings.AUTH_USER_MODEL)),
                ('veiculo_interno', models.ForeignKey(blank=True, help_text='Veículo interno escolhido', limit_choices_to={'tipo__in': ['VIATURA_INTERNA_ENTREGA', 'VIATURA_INTERNA_EXECUTIVO']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_internas', to='empresa.transportadora')),
            ],
            options={
                'verbose_name': 'Notificação Logística Unificada',
                'verbose_name_plural': 'Notificações Logísticas Unificadas',
                'ordering': ['-data_notificacao'],
            },
        ),
        migrations.DeleteModel(
            name='NotificacaoColetaCompra',
        ),
        migrations.DeleteModel(
            name='NotificacaoTransferenciaLogistica',
        ),
        migrations.AddIndex(
            model_name='notificacaologisticaunificada',
            index=models.Index(fields=['tipo_operacao'], name='empresa_not_tipo_op_baebe1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaologisticaunificada',
            index=models.Index(fields=['status'], name='empresa_not_status_276443_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaologisticaunificada',
            index=models.Index(fields=['data_notificacao'], name='empresa_not_data_no_bc4507_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacaologisticaunificada',
            index=models.Index(fields=['prioridade'], name='empresa_not_priorid_c623be_idx'),
        ),
    ]
