# Generated by Django 5.0.8 on 2025-01-27

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0112_fix_requisicoes_sem_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaostock',
            name='sucursal_destino',
            field=models.ForeignKey(
                help_text='Sucursal que fornece (obrigatória para requisições internas)',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='requisicoes_recebidas',
                to='empresa.sucursal',
                null=False,
                blank=False
            ),
        ),
    ]
