# Generated by Django 5.2.6 on 2025-10-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0108_fix_requisicoes_sem_destino'),
        ('empresa', '0113_make_sucursal_destino_required'),
    ]

    operations = [
    ]
