# Generated by Django 5.2.6 on 2025-10-17 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0114_merge_20251017_1525'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='coletado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que confirmou a coleta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_coletadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='comprovante_recebimento',
            field=models.FileField(blank=True, help_text='Comprovante de recebimento assinado', null=True, upload_to='comprovantes_recebimento/'),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='data_coleta',
            field=models.DateTimeField(blank=True, help_text='Data e hora da coleta', null=True),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='data_entrega',
            field=models.DateTimeField(blank=True, help_text='Data e hora da entrega', null=True),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='entregue_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que confirmou a entrega', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_entregues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='guia_coleta',
            field=models.FileField(blank=True, help_text='Guia de coleta gerada', null=True, upload_to='guias_coleta/'),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='guia_entrega',
            field=models.FileField(blank=True, help_text='Guia de entrega gerada', null=True, upload_to='guias_entrega/'),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='local_coleta',
            field=models.CharField(blank=True, help_text='Local onde foi realizada a coleta', max_length=200),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='local_entrega',
            field=models.CharField(blank=True, help_text='Local onde foi realizada a entrega', max_length=200),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='observacoes_coleta',
            field=models.TextField(blank=True, help_text='Observações sobre a coleta'),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='observacoes_entrega',
            field=models.TextField(blank=True, help_text='Observações sobre a entrega'),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='recebido_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que confirmou o recebimento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacaologisticaunificada',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATRIBUIDA', 'Transporte Atribuído'), ('COLETADA', 'Coletada'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status da notificação logística', max_length=20),
        ),
    ]
