# Generated by Django 5.2.6 on 2025-10-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0115_improve_logistics_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaostock',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, help_text='Sucursal que fornece (será definida quando adicionar itens)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_recebidas', to='empresa.sucursal'),
        ),
    ]
