# Generated by Django 5.2.6 on 2025-10-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0116_allow_null_sucursal_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('APROVADA', 'Aprovada'), ('GUARDADA', 'Guardada'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
    ]
