# Generated by Django 5.2.6 on 2025-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0117_add_guardada_status_to_ordem_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='data_inicio_transporte',
            field=models.DateTimeField(blank=True, help_text='Data e hora do início do transporte', null=True),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='observacoes_conclusao',
            field=models.TextField(blank=True, help_text='Observações sobre a conclusão'),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='observacoes_transporte',
            field=models.TextField(blank=True, help_text='Observações sobre o transporte'),
        ),
    ]
