# Generated by Django 5.2.6 on 2025-10-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0118_add_transport_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaologisticaunificada',
            name='veiculo_interno',
            field=models.ForeignKey(blank=True, help_text='Veículo interno escolhido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_internas', to='empresa.veiculointerno'),
        ),
    ]
