# Generated by Django 5.2.6 on 2025-10-19 18:39

from django.db import migrations


def clear_inconsistent_veiculo_data(apps, schema_editor):
    """Limpar dados inconsistentes de veículo interno"""
    NotificacaoLogisticaUnificada = apps.get_model('empresa', 'NotificacaoLogisticaUnificada')
    
    # Limpar veiculo_interno_id para registros que referenciam IDs inexistentes
    NotificacaoLogisticaUnificada.objects.filter(veiculo_interno_id__isnull=False).update(veiculo_interno_id=None)


def reverse_clear_inconsistent_veiculo_data(apps, schema_editor):
    """Não há como reverter esta operação"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0119_fix_veiculo_interno_field'),
    ]

    operations = [
        migrations.RunPython(clear_inconsistent_veiculo_data, reverse_clear_inconsistent_veiculo_data),
    ]
