# Generated by Django 5.2.6 on 2025-10-20 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0120_clear_inconsistent_veiculo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código único do checklist', max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('PRE_VIAGEM', 'Pré-Viagem'), ('POS_VIAGEM', 'Pós-Viagem'), ('MANUTENCAO', 'Manutenção'), ('INSPECAO', 'Inspeção Geral'), ('SEMANAL', 'Inspeção Semanal'), ('MENSAL', 'Inspeção Mensal')], help_text='Tipo de checklist', max_length=20)),
                ('motorista', models.CharField(help_text='Motorista presente na inspeção', max_length=200)),
                ('data_inspecao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da inspeção')),
                ('local_inspecao', models.CharField(help_text='Local onde foi realizada a inspeção', max_length=200)),
                ('quilometragem', models.PositiveIntegerField(help_text='Quilometragem no momento da inspeção')),
                ('freios_funcionando', models.BooleanField(default=True, help_text='Freios funcionando corretamente')),
                ('fluido_freio_ok', models.BooleanField(default=True, help_text='Fluido de freio em nível adequado')),
                ('pastilhas_ok', models.BooleanField(default=True, help_text='Pastilhas de freio em bom estado')),
                ('direcao_funcionando', models.BooleanField(default=True, help_text='Direção funcionando corretamente')),
                ('fluido_direcao_ok', models.BooleanField(default=True, help_text='Fluido de direção em nível adequado')),
                ('bateria_ok', models.BooleanField(default=True, help_text='Bateria em bom estado')),
                ('alternador_ok', models.BooleanField(default=True, help_text='Alternador funcionando')),
                ('farois_funcionando', models.BooleanField(default=True, help_text='Faróis funcionando')),
                ('luzes_sinalizacao', models.BooleanField(default=True, help_text='Luzes de sinalização funcionando')),
                ('pneus_pressao_ok', models.BooleanField(default=True, help_text='Pressão dos pneus adequada')),
                ('pneus_desgaste_ok', models.BooleanField(default=True, help_text='Desgaste dos pneus dentro do limite')),
                ('rodas_ok', models.BooleanField(default=True, help_text='Rodas em bom estado')),
                ('motor_funcionando', models.BooleanField(default=True, help_text='Motor funcionando corretamente')),
                ('oleo_motor_ok', models.BooleanField(default=True, help_text='Óleo do motor em nível adequado')),
                ('agua_radiador_ok', models.BooleanField(default=True, help_text='Água do radiador em nível adequado')),
                ('combustivel_ok', models.BooleanField(default=True, help_text='Combustível suficiente')),
                ('documentos_ok', models.BooleanField(default=True, help_text='Documentação do veículo em dia')),
                ('seguro_ok', models.BooleanField(default=True, help_text='Seguro do veículo em dia')),
                ('licenciamento_ok', models.BooleanField(default=True, help_text='Licenciamento em dia')),
                ('limpeza_interior', models.BooleanField(default=True, help_text='Interior limpo e organizado')),
                ('limpeza_exterior', models.BooleanField(default=True, help_text='Exterior limpo')),
                ('extintor_ok', models.BooleanField(default=True, help_text='Extintor presente e em dia')),
                ('triangulo_ok', models.BooleanField(default=True, help_text='Triângulo de sinalização presente')),
                ('macaco_ok', models.BooleanField(default=True, help_text='Macaco presente e funcionando')),
                ('chave_roda_ok', models.BooleanField(default=True, help_text='Chave de roda presente')),
                ('status_final', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONDICIONAL', 'Aprovado com Condições')], help_text='Status final da inspeção', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a inspeção')),
                ('recomendacoes', models.TextField(blank=True, help_text='Recomendações para manutenção')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do checklist')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o checklist está ativo')),
                ('inspetor', models.ForeignKey(help_text='Inspetor responsável', on_delete=django.db.models.deletion.PROTECT, related_name='checklists_realizados', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(help_text='Veículo avaliado', on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='empresa.veiculointerno')),
            ],
            options={
                'verbose_name': 'Checklist de Viatura',
                'verbose_name_plural': 'Checklists de Viaturas',
                'ordering': ['-data_inspecao'],
            },
        ),
    ]
