# Generated by Django 5.2.6 on 2025-10-20 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0121_checklistviatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorastreamento',
            name='tipo_evento',
            field=models.CharField(choices=[('PREPARANDO', 'Preparando'), ('CRIADO', 'Criado'), ('COLETADO', 'Coletado'), ('EM_TRANSITO', 'Em Trânsito'), ('EM_DISTRIBUICAO', 'Em Distribuição'), ('TENTATIVA_ENTREGA', 'Tentativa de Entrega'), ('ENTREGUE', 'Entregue'), ('DEVOLVIDO', 'Devolvido'), ('PERDIDO', 'Perdido'), ('CANCELADO', 'Cancelado'), ('OBSERVACAO', 'Observação')], help_text='Tipo do evento', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacaologisticaunificada',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_index=True, default='NORMAL', help_text='Prioridade da operação', max_length=20),
        ),
        migrations.AlterField(
            model_name='rastreamentoentrega',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data de criação do rastreamento'),
        ),
        migrations.AlterField(
            model_name='rastreamentoentrega',
            name='status_atual',
            field=models.CharField(choices=[('PREPARANDO', 'Preparando'), ('COLETADO', 'Coletado'), ('EM_TRANSITO', 'Em Trânsito'), ('EM_DISTRIBUICAO', 'Em Distribuição'), ('ENTREGUE', 'Entregue'), ('DEVOLVIDO', 'Devolvido'), ('PERDIDO', 'Perdido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PREPARANDO', help_text='Status atual da entrega', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='tipo',
            field=models.CharField(choices=[('TRANSPORTADORA', 'Transportadora Externa'), ('ENTREGA_RAPIDA', 'Entrega Rápida'), ('CORREIOS', 'Correios'), ('MOTORISTA', 'Motorista Próprio'), ('TERCEIRIZADA', 'Terceirizada')], default='TRANSPORTADORA', help_text='Tipo de transportadora', max_length=30),
        ),
        migrations.AddIndex(
            model_name='rastreamentoentrega',
            index=models.Index(fields=['status_atual'], name='empresa_ras_status__347309_idx'),
        ),
        migrations.AddIndex(
            model_name='rastreamentoentrega',
            index=models.Index(fields=['data_criacao'], name='empresa_ras_data_cr_ba6dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='rastreamentoentrega',
            index=models.Index(fields=['transportadora'], name='empresa_ras_transpo_458601_idx'),
        ),
        migrations.AddIndex(
            model_name='rastreamentoentrega',
            index=models.Index(fields=['veiculo_interno'], name='empresa_ras_veiculo_46cfc8_idx'),
        ),
    ]
