# Generated by Django 5.2.6 on 2025-10-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0126_catalogodimensoes_configuracaoescalabilidade_and_more'),
    ]

    operations = [
        # Remover constraint antiga e adicionar nova para NotificacaoLogisticaUnificada
        migrations.RunSQL(
            # Remover constraints antigas
            sql="""
                ALTER TABLE empresa_notificacaologisticaunificada 
                DROP CONSTRAINT IF EXISTS empresa_notificacaol_veiculo_interno_id_e076e069_fk_empresa_v;
                
                ALTER TABLE empresa_notificacaologisticaunificada 
                DROP CONSTRAINT IF EXISTS empresa_notificacaol_transportadora_exte_veiculo_intern_f5c8e7da_fk_empresa_v;
                
                ALTER TABLE empresa_notificacaologisticaunificada 
                DROP CONSTRAINT IF EXISTS empresa_notificacaol_transportadora_exte_veiculo_intern_f5c8e7da_fk_empresa_t;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        # Adicionar novas constraints corretas (se não existirem)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'empresa_notificacaol_veiculo_interno_id_fk'
                    ) THEN
                        ALTER TABLE empresa_notificacaologisticaunificada 
                        ADD CONSTRAINT empresa_notificacaol_veiculo_interno_id_fk
                        FOREIGN KEY (veiculo_interno_id) 
                        REFERENCES empresa_transportadora(id) 
                        DEFERRABLE INITIALLY DEFERRED;
                    END IF;
                    
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'empresa_notificacaol_transportadora_externa_id_fk'
                    ) THEN
                        ALTER TABLE empresa_notificacaologisticaunificada 
                        ADD CONSTRAINT empresa_notificacaol_transportadora_externa_id_fk
                        FOREIGN KEY (transportadora_externa_id) 
                        REFERENCES empresa_transportadora(id) 
                        DEFERRABLE INITIALLY DEFERRED;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        # Remover constraint antiga e adicionar nova para RastreamentoEntrega
        migrations.RunSQL(
            sql="""
                ALTER TABLE empresa_rastreamentoentrega 
                DROP CONSTRAINT IF EXISTS empresa_rastreamento_veiculo_interno_id_90c4194a_fk_empresa_v;
                
                ALTER TABLE empresa_rastreamentoentrega 
                DROP CONSTRAINT IF EXISTS empresa_rastreame_veiculo_interno_id_d9477100_fk_empresa_v;
                
                ALTER TABLE empresa_rastreamentoentrega 
                DROP CONSTRAINT IF EXISTS empresa_rastreame_transportadora_id_22a83e98_fk_empresa_t;
                
                ALTER TABLE empresa_rastreamentoentrega 
                DROP CONSTRAINT IF EXISTS empresa_rastreamento_transportadora_id_fk;
                
                ALTER TABLE empresa_rastreamentoentrega 
                DROP CONSTRAINT IF EXISTS empresa_rastreame_transportadora_id_fk;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'empresa_rastreame_veiculo_interno_id_fk'
                    ) THEN
                        ALTER TABLE empresa_rastreamentoentrega 
                        ADD CONSTRAINT empresa_rastreame_veiculo_interno_id_fk
                        FOREIGN KEY (veiculo_interno_id) 
                        REFERENCES empresa_transportadora(id) 
                        DEFERRABLE INITIALLY DEFERRED;
                    END IF;
                    
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'empresa_rastreame_transportadora_id_fk'
                    ) THEN
                        ALTER TABLE empresa_rastreamentoentrega 
                        ADD CONSTRAINT empresa_rastreame_transportadora_id_fk
                        FOREIGN KEY (transportadora_id) 
                        REFERENCES empresa_transportadora(id) 
                        DEFERRABLE INITIALLY DEFERRED;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
