# Generated by Django 5.2.6 on 2025-10-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0127_auto_20251027_2201'),
    ]

    operations = [
    ]
