# Generated by Django 5.2.6 on 2025-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0128_add_motorista_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='motorista_operacao',
            field=models.CharField(blank=True, help_text='Nome do motorista designado para esta operação específica', max_length=200),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='telefone_motorista_operacao',
            field=models.CharField(blank=True, help_text='Telefone do motorista designado para esta operação', max_length=13),
        ),
    ]
