# Generated by Django 5.2.6 on 2025-10-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0130_funcionario_chefe_checklistviatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoHierarquica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da posição (ex.: Gerente, Analista)', max_length=100)),
                ('nivel', models.PositiveIntegerField(default=0, help_text='Ordem hierárquica (menor número = mais alto)')),
                ('ativa', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='empresa.departamento')),
                ('posicao_superior', models.ForeignKey(blank=True, help_text='Posição imediatamente superior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subposicoes', to='empresa.posicaohierarquica')),
            ],
            options={
                'verbose_name': 'Posição Hierárquica',
                'verbose_name_plural': 'Posições Hierárquicas',
                'ordering': ['departamento__nome', 'nivel', 'nome'],
                'unique_together': {('departamento', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='posicao',
            field=models.ForeignKey(blank=True, help_text='Posição hierárquica no departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='empresa.posicaohierarquica'),
        ),
    ]
