# Generated by Django 5.2.6 on 2025-10-31 08:27

from django.db import migrations, models


def migrar_departamentos_para_manytomany(apps, schema_editor):
    """Migra dados do campo departamento (FK) para departamentos (ManyToMany)"""
    PosicaoHierarquica = apps.get_model('empresa', 'PosicaoHierarquica')
    for posicao in PosicaoHierarquica.objects.all():
        # Acessar o campo antigo através do histórico
        if hasattr(posicao, 'departamento_id') and posicao.departamento_id:
            # Adicionar ao novo campo ManyToMany
            posicao.departamentos.add(posicao.departamento_id)


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0132_fix_solicitacao_hierarquia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posicaohierarquica',
            options={'ordering': ['nivel', 'nome'], 'verbose_name': 'Posição Hierárquica', 'verbose_name_plural': 'Posições Hierárquicas'},
        ),
        migrations.AlterUniqueTogether(
            name='posicaohierarquica',
            unique_together=set(),
        ),
        # Primeiro adicionar o novo campo ManyToMany (vazio)
        migrations.AddField(
            model_name='posicaohierarquica',
            name='departamentos',
            field=models.ManyToManyField(help_text='Departamentos aos quais esta posição se aplica', related_name='posicoes_hierarquicas', to='empresa.departamento'),
        ),
        # Migrar dados antes de remover o campo antigo
        migrations.RunPython(migrar_departamentos_para_manytomany, reverse_code=migrations.RunPython.noop),
        # Agora remover o campo antigo
        migrations.RemoveField(
            model_name='posicaohierarquica',
            name='departamento',
        ),
    ]
