# Generated by Django 5.2.6 on 2025-10-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0133_posicao_hierarquica_multiplos_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicaohierarquica',
            name='cargos',
            field=models.ManyToManyField(blank=True, help_text='Cargos aos quais esta posição se aplica (opcional)', related_name='posicoes_hierarquicas', to='empresa.cargo'),
        ),
    ]
