# Generated by Django 5.2.6 on 2025-10-31 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0134_posicao_hierarquica_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoalteracaohierarquia',
            name='novo_nivel',
            field=models.PositiveIntegerField(blank=True, help_text='Novo nível hierárquico solicitado (0=TOPO, 1=subordinado de 0, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoalteracaohierarquia',
            name='novo_posicao',
            field=models.ForeignKey(blank=True, help_text='Nova posição hierárquica para o funcionário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.posicaohierarquica'),
        ),
    ]
