# Generated by Django 5.2.6 on 2025-10-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0135_add_novo_nivel_posicao_to_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='nivel_hierarquico',
            field=models.PositiveIntegerField(default=2, help_text='Nível hierárquico do departamento na estrutura organizacional. Nível 0-1 são globais (TOPO), nível 2+ são departamentos específicos. Usado para calcular hierarquias dentro do departamento.'),
        ),
    ]
