# Generated by Django 5.2.6 on 2025-10-31 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0136_add_nivel_hierarquico_to_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='departamento_pai',
            field=models.ForeignKey(blank=True, help_text='Departamento pai (para subdepartamentos como Importação/Exportação que pertencem a Logística)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartamentos', to='empresa.departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nivel_hierarquico',
            field=models.PositiveIntegerField(default=2, help_text='Nível hierárquico do departamento na estrutura organizacional. Nível 0-1 são globais (TOPO como Direcção Geral), nível 2 são departamentos principais, nível 3+ são subdepartamentos.'),
        ),
    ]
