# Generated by Django 5.2.6 on 2025-10-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0137_add_departamento_pai_to_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='numero_contribuinte_inss',
            field=models.CharField(blank=True, help_text='Número de Contribuinte INSS (para canalização da contribuição social)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descontosalarial',
            name='tipo',
            field=models.CharField(choices=[('IR', 'Imposto de Renda'), ('IN', 'INSS Moçambique (Contribuição Social)'), ('SS', 'Segurança Social'), ('EM', 'Empréstimo'), ('AD', 'Adiantamento'), ('FA', 'Falta'), ('AT', 'Atraso'), ('OU', 'Outro')], max_length=2, verbose_name='Tipo'),
        ),
    ]
