# Generated by Django 5.2.6 on 2025-11-01 16:21

import meuprojeto.empresa.models_rh
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0139_fix_telefone_alternativo_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariofolha',
            name='inss_empregador',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Contribuição do empregador para INSS', max_digits=10, verbose_name='INSS Empregador (4%)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone_alternativo',
            field=models.CharField(blank=True, help_text='Telefone alternativo', max_length=13, null=True, validators=[meuprojeto.empresa.models_rh.validar_telefone_moz]),
        ),
    ]
