# Generated by Django 5.2.6 on 2025-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0140_add_inss_empregador'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhasalarial',
            name='total_encargos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo total para a empresa (salário bruto + INSS empregador)', max_digits=12, verbose_name='Total Encargos'),
        ),
        migrations.AddField(
            model_name='folhasalarial',
            name='total_inss_empregador',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo total do INSS do empregador para todos os funcionários', max_digits=12, verbose_name='Total INSS Empregador (4%)'),
        ),
    ]
