# Generated by Django 5.2.6 on 2025-11-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0141_add_encargos_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='confirmado_por_funcionario',
            field=models.BooleanField(default=False, verbose_name='Confirmado pelo Funcionário'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='observacoes_confirmacao',
            field=models.TextField(blank=True, verbose_name='Observações da Confirmação'),
        ),
    ]
