# Generated by Django 5.2.6 on 2025-11-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0142_adicionar_campos_confirmacao_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhasalarial',
            name='data_fim_abertura',
            field=models.DateField(blank=True, help_text='Data até a qual a folha pode ser aberta. Se não informado, não há restrição.', null=True, verbose_name='Data Fim para Abertura'),
        ),
        migrations.AddField(
            model_name='folhasalarial',
            name='data_fim_fechamento',
            field=models.DateField(blank=True, help_text='Data até a qual a folha pode ser fechada. Se não informado, não há restrição.', null=True, verbose_name='Data Fim para Fechamento'),
        ),
        migrations.AddField(
            model_name='folhasalarial',
            name='data_inicio_abertura',
            field=models.DateField(blank=True, help_text='Data a partir da qual a folha pode ser aberta. Se não informado, não há restrição.', null=True, verbose_name='Data Início para Abertura'),
        ),
        migrations.AddField(
            model_name='folhasalarial',
            name='data_inicio_fechamento',
            field=models.DateField(blank=True, help_text='Data a partir da qual a folha pode ser fechada. Se não informado, não há restrição.', null=True, verbose_name='Data Início para Fechamento'),
        ),
    ]
