# Generated by Django 5.2.6 on 2025-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0143_add_periodos_folha_salarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFolhaSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_pagamento', models.PositiveSmallIntegerField(default=25, help_text='Dia do mês em que os salários são pagos (ex: 25 = dia 25 de cada mês). Deve ser antes do último dia do mês.', verbose_name='Dia do Mês para Pagamento')),
                ('dias_antes_pagamento_para_fechar', models.PositiveSmallIntegerField(default=3, help_text='Número de dias antes da data de pagamento que a folha deve ser fechada (ex: 3 = fechar 3 dias antes do pagamento)', verbose_name='Dias Antes do Pagamento para Fechar')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Folha Salarial',
                'verbose_name_plural': 'Configurações de Folha Salarial',
            },
        ),
    ]
