# Generated by Django 5.2.6 on 2025-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0144_add_configuracao_folha_salarial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaofolhasalarial',
            name='dia_pagamento',
        ),
        migrations.RemoveField(
            model_name='configuracaofolhasalarial',
            name='dias_antes_pagamento_para_fechar',
        ),
        migrations.AddField(
            model_name='configuracaofolhasalarial',
            name='dia_fechamento_folha',
            field=models.PositiveSmallIntegerField(default=22, help_text='Dia do mês seguinte ao mês de referência em que a folha deve ser fechada (ex: 22 = fechar no dia 22). A folha será fechada neste dia específico.', verbose_name='Dia para Fechar a Folha'),
        ),
        migrations.AddField(
            model_name='configuracaofolhasalarial',
            name='dias_apos_fechamento_para_pagamento',
            field=models.PositiveSmallIntegerField(default=3, help_text='Número de dias após o fechamento em que os salários serão pagos (ex: 3 = pagar 3 dias depois do fechamento)', verbose_name='Dias Após Fechamento para Pagamento'),
        ),
    ]
