# Generated by Django 5.2.6 on 2025-11-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0145_simplify_config_folha_salarial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descontosalarial',
            name='conta_canalizacao',
            field=models.CharField(blank=True, help_text='Código da conta contábil onde os valores deste desconto devem ser canalizados (ex: 2.1.1.01 para IRPS, 2.1.2.01 para INSS)', max_length=50, verbose_name='Conta para Canalização'),
        ),
        migrations.AddField(
            model_name='descontosalarial',
            name='descricao_canalizacao',
            field=models.CharField(blank=True, help_text="Descrição do destino dos valores (ex: 'IRPS a Recolher', 'INSS a Recolher', 'Empréstimos Consignados')", max_length=200, verbose_name='Descrição da Canalização'),
        ),
    ]
