# Generated by Django 5.2.6 on 2025-11-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0146_add_conta_canalizacao_descontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='assinatura_receptor',
            field=models.ImageField(blank=True, help_text='Assinatura do receptor para confirmação de recebimento', null=True, upload_to='assinaturas_receptor/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='documento_receptor',
            field=models.CharField(blank=True, help_text='Número de documento (BI/Passaporte) do receptor', max_length=50),
        ),
        migrations.AddField(
            model_name='notificacaologisticaunificada',
            name='nome_receptor',
            field=models.CharField(blank=True, help_text='Nome completo do receptor que assinou o documento', max_length=200),
        ),
    ]
