# Generated by Django 5.2.6 on 2025-11-03 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0147_add_assinatura_receptor_campos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViagemConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código único da viagem consolidada', max_length=50, unique=True)),
                ('motorista', models.CharField(blank=True, help_text='Nome do motorista', max_length=200)),
                ('telefone_motorista', models.CharField(blank=True, help_text='Telefone do motorista', max_length=13)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('ATRIBUIDA', 'Transporte Atribuído'), ('EM_ROTA', 'Em Rota'), ('EM_ENTREGA', 'Em Entrega'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', help_text='Status da viagem consolidada', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação da viagem consolidada')),
                ('data_saida', models.DateTimeField(blank=True, help_text='Data e hora de saída', null=True)),
                ('data_retorno', models.DateTimeField(blank=True, help_text='Data e hora de retorno', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais sobre a viagem')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que criou a viagem consolidada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_consolidadas_criadas', to=settings.AUTH_USER_MODEL)),
                ('operacoes', models.ManyToManyField(help_text='Operações logísticas incluídas nesta viagem', related_name='viagens_consolidadas', to='empresa.notificacaologisticaunificada')),
                ('transportadora_externa', models.ForeignKey(blank=True, help_text='Transportadora externa escolhida', limit_choices_to={'tipo__in': ['TRANSPORTADORA', 'ENTREGA_RAPIDA', 'CORREIOS', 'MOTORISTA', 'TERCEIRIZADA']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens_consolidadas_externas', to='empresa.transportadora')),
                ('veiculo_interno', models.ForeignKey(blank=True, help_text='Veículo interno escolhido', limit_choices_to={'tipo__startswith': 'VIATURA_INTERNA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens_consolidadas_internas', to='empresa.transportadora')),
            ],
            options={
                'verbose_name': 'Viagem Consolidada',
                'verbose_name_plural': 'Viagens Consolidadas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
