# Generated by Django 5.2.6 on 2025-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0148_add_viagem_consolidada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcompra',
            name='forma_pagamento',
            field=models.CharField(choices=[('PRONTO_PAGAMENTO', 'Pronto Pagamento'), ('CREDITO', 'A Crédito')], default='PRONTO_PAGAMENTO', help_text='Forma de pagamento', max_length=20),
        ),
    ]
