# Generated by Django 5.2.6 on 2025-11-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0150_migrar_codigos_requisicoes_ordens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaocompraexterna',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('ENVIADA', 'Enviada ao Fornecedor'), ('RECEBIDA', 'Recebida'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', help_text='Status da requisição de compra', max_length=20),
        ),
    ]
