# Generated by Django 5.2.6 on 2025-11-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0153_fix_receita_produto_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='documento_pdf',
            field=models.FileField(blank=True, help_text='Documento PDF do projeto/receita (especificações técnicas, desenhos, etc.)', null=True, upload_to='receitas/documentos/%Y/%m/%d/'),
        ),
    ]
