# Generated by Django 5.2.6 on 2025-11-06 08:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0154_receita_documento_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da ordem de produção', max_length=20, unique=True)),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade de produtos a produzir', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PLANEJADA', 'Planejada'), ('EM_PRODUCAO', 'Em Produção'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('PAUSADA', 'Pausada')], default='RASCUNHO', help_text='Status da ordem de produção', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', help_text='Prioridade da ordem', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação da ordem')),
                ('data_planejada_inicio', models.DateTimeField(blank=True, help_text='Data planejada para início da produção', null=True)),
                ('data_planejada_conclusao', models.DateTimeField(blank=True, help_text='Data planejada para conclusão da produção', null=True)),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data real de início da produção', null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data real de conclusão da produção', null=True)),
                ('quantidade_produzida', models.PositiveIntegerField(default=0, help_text='Quantidade efetivamente produzida')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a ordem de produção')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que criou a ordem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao_criadas', to=settings.AUTH_USER_MODEL)),
                ('receita', models.ForeignKey(help_text='Receita a ser utilizada na produção', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_producao', to='empresa.receita')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Responsável pela produção', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao_responsavel', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(help_text='Sucursal onde será realizada a produção', on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
