# Generated by Django 5.2.6 on 2025-11-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0155_ordemproducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, help_text='Data de cancelamento da ordem', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, help_text='Motivo do cancelamento da ordem'),
        ),
    ]
