# Generated by Django 5.2.6 on 2025-11-06 09:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0156_ordemproducao_data_cancelamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do processo produtivo', max_length=200)),
                ('codigo', models.CharField(blank=True, help_text='Código único do processo (gerado automaticamente se vazio)', max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do processo')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado')], default='RASCUNHO', help_text='Status do processo', max_length=20)),
                ('tempo_total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tempo total estimado em horas', max_digits=10)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o processo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do processo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que criou o processo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
                ('receita', models.ForeignKey(blank=True, help_text='Receita associada ao processo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='empresa.receita')),
            ],
            options={
                'verbose_name': 'Processo de Produção',
                'verbose_name_plural': 'Processos de Produção',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da etapa', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da etapa')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem de execução da etapa')),
                ('tempo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tempo estimado em horas', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a etapa')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Responsável pela etapa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_responsaveis', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(help_text='Processo ao qual esta etapa pertence', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='empresa.processoproducao')),
            ],
            options={
                'verbose_name': 'Etapa do Processo',
                'verbose_name_plural': 'Etapas do Processo',
                'ordering': ['processo', 'ordem'],
                'unique_together': {('processo', 'ordem')},
            },
        ),
    ]
