# Generated by Django 5.2.6 on 2025-11-06 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0157_add_processo_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='processo',
            field=models.ForeignKey(blank=True, help_text='Processo de produção a ser seguido (opcional, pode ser sugerido automaticamente baseado na receita)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao', to='empresa.processoproducao'),
        ),
    ]
