# Generated by Django 5.2.6 on 2025-11-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0158_add_processo_to_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapaprocesso',
            options={'ordering': ['processo', 'ordem', 'nome'], 'verbose_name': 'Etapa do Processo', 'verbose_name_plural': 'Etapas do Processo'},
        ),
        migrations.AlterUniqueTogether(
            name='etapaprocesso',
            unique_together=set(),
        ),
    ]
