# Generated by Django 5.2.6 on 2025-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0159_allow_parallel_etapas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoproducao',
            name='receita',
        ),
        migrations.AddField(
            model_name='processoproducao',
            name='receitas',
            field=models.ManyToManyField(blank=True, help_text='Receitas que utilizam este processo (múltiplas receitas podem usar o mesmo processo)', related_name='processos', to='empresa.receita'),
        ),
    ]
