# Generated by Django 5.2.6 on 2025-11-06 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0160_change_processo_receita_to_manytomany'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da máquina ou equipamento', max_length=200)),
                ('codigo', models.CharField(blank=True, help_text='Código único da máquina (gerado automaticamente se vazio)', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('MAQUINA', 'Máquina'), ('EQUIPAMENTO', 'Equipamento'), ('FERRAMENTA', 'Ferramenta'), ('LINHA_PRODUCAO', 'Linha de Produção'), ('CELULA_PRODUCAO', 'Célula de Produção'), ('OUTRO', 'Outro')], default='MAQUINA', help_text='Tipo de máquina ou equipamento', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da máquina')),
                ('marca', models.CharField(blank=True, help_text='Marca da máquina', max_length=100)),
                ('modelo', models.CharField(blank=True, help_text='Modelo da máquina', max_length=100)),
                ('numero_serie', models.CharField(blank=True, help_text='Número de série da máquina', max_length=100)),
                ('capacidade', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade de produção da máquina', max_digits=10, null=True)),
                ('unidade_capacidade', models.CharField(blank=True, choices=[('UN/H', 'Unidades por Hora'), ('KG/H', 'Quilogramas por Hora'), ('L/H', 'Litros por Hora'), ('M/H', 'Metros por Hora'), ('M2/H', 'Metros Quadrados por Hora'), ('M3/H', 'Metros Cúbicos por Hora')], help_text='Unidade de medida da capacidade', max_length=10)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em Uso'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo'), ('RESERVADO', 'Reservado')], default='DISPONIVEL', help_text='Status atual da máquina', max_length=20)),
                ('localizacao', models.CharField(blank=True, help_text='Localização física da máquina (ex: Setor A, Linha 1)', max_length=200)),
                ('data_aquisicao', models.DateField(blank=True, help_text='Data de aquisição da máquina', null=True)),
                ('data_proxima_manutencao', models.DateField(blank=True, help_text='Data prevista para próxima manutenção', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a máquina')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro da máquina')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que cadastrou a máquina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_criadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(help_text='Sucursal onde a máquina está localizada', on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
