# Generated by Django 5.2.6 on 2025-11-06 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0161_add_maquina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da linha de produção', max_length=200)),
                ('codigo', models.CharField(blank=True, help_text='Código único da linha (gerado automaticamente se vazio)', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('LINHA', 'Linha de Produção'), ('CELULA', 'Célula de Produção'), ('ESTACAO', 'Estação de Trabalho'), ('AREA', 'Área de Produção')], default='LINHA', help_text='Tipo de linha de produção', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da linha')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('MANUTENCAO', 'Em Manutenção'), ('RESERVADA', 'Reservada')], default='ATIVA', help_text='Status atual da linha', max_length=20)),
                ('localizacao', models.CharField(blank=True, help_text='Localização física da linha (ex: Setor A, Piso 2)', max_length=200)),
                ('capacidade_horaria', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade de produção por hora (em unidades)', max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a linha')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro da linha')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que cadastrou a linha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_producao_criadas', to=settings.AUTH_USER_MODEL)),
                ('maquinas', models.ManyToManyField(blank=True, help_text='Máquinas e equipamentos associados à linha', related_name='linhas_producao', to='empresa.maquina')),
                ('processos', models.ManyToManyField(blank=True, help_text='Processos de produção que podem ser executados nesta linha', related_name='linhas_producao', to='empresa.processoproducao')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Responsável pela linha de produção', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_producao_responsavel', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(help_text='Sucursal onde a linha está localizada', on_delete=django.db.models.deletion.CASCADE, related_name='linhas_producao', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Linha de Produção',
                'verbose_name_plural': 'Linhas de Produção',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
