# Generated by Django 5.2.6 on 2025-11-06 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0162_add_linha_producao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaOrdemConcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True, help_text='Data de conclusão da etapa')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a conclusão da etapa')),
                ('concluida_por', models.ForeignKey(blank=True, help_text='Usuário que marcou a etapa como concluída', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_concluidas', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(help_text='Etapa do processo concluída', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_concluidas', to='empresa.etapaprocesso')),
                ('ordem', models.ForeignKey(help_text='Ordem de produção', on_delete=django.db.models.deletion.CASCADE, related_name='etapas_concluidas', to='empresa.ordemproducao')),
            ],
            options={
                'verbose_name': 'Etapa Concluída',
                'verbose_name_plural': 'Etapas Concluídas',
                'ordering': ['ordem', 'etapa__ordem', 'data_conclusao'],
                'unique_together': {('ordem', 'etapa')},
            },
        ),
    ]
