# Generated by Django 5.2.6 on 2025-11-07 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0163_add_etapa_ordem_concluida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_planejada_conclusao',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_planejada_inicio',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='status',
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='acabamentos_concluidos',
            field=models.BooleanField(default=False, help_text='Acabamentos foram concluídos'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que aprovou a ordem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='aprovado_qualidade_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que aprovou o controle de qualidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_aprovadas_qualidade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='controle_qualidade_aprovado',
            field=models.BooleanField(default=False, help_text='Controle de qualidade foi aprovado'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, help_text='Data de aprovação da ordem', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_aprovacao_qualidade',
            field=models.DateTimeField(blank=True, help_text='Data de aprovação do controle de qualidade', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, help_text='Data de finalização completa da ordem', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_inicio_fase2',
            field=models.DateTimeField(blank=True, help_text='Data de início da Fase 2 (Preparação e Execução)', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_inicio_fase3',
            field=models.DateTimeField(blank=True, help_text='Data de início da Fase 3 (Acabamentos)', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='fase_atual',
            field=models.CharField(choices=[('FASE1_CRIACAO', 'Fase 1: Criação e Aprovação'), ('FASE2_EXECUCAO', 'Fase 2: Preparação e Execução'), ('FASE3_FINALIZACAO', 'Fase 3: Acabamentos e Finalizações'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='FASE1_CRIACAO', help_text='Fase atual da ordem de produção', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='montagem_concluida',
            field=models.BooleanField(default=False, help_text='Montagem foi concluída'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, help_text='Motivo da rejeição (se aplicável)'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='observacoes_criacao',
            field=models.TextField(blank=True, help_text='Observações na criação da ordem'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='observacoes_execucao',
            field=models.TextField(blank=True, help_text='Observações durante a execução'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='observacoes_finalizacao',
            field=models.TextField(blank=True, help_text='Observações na finalização'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='observacoes_qualidade',
            field=models.TextField(blank=True, help_text='Observações do controle de qualidade'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='preparacao_pecas_concluida',
            field=models.BooleanField(default=False, help_text='Preparação das peças foi concluída'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='produto_disponibilizado',
            field=models.BooleanField(default=False, help_text='Produto foi disponibilizado para consumidores'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='requisicao_material_criada',
            field=models.BooleanField(default=False, help_text='Requisição de material foi criada'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='requisicao_material_id',
            field=models.IntegerField(blank=True, help_text='ID da requisição de material criada', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='responsavel_fase2',
            field=models.ForeignKey(blank=True, help_text='Responsável pela Fase 2 (Preparação e Execução)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsavel_fase2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='responsavel_fase3',
            field=models.ForeignKey(blank=True, help_text='Responsável pela Fase 3 (Acabamentos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsavel_fase3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='retoques_concluidos',
            field=models.BooleanField(default=False, help_text='Retoques finais foram concluídos'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='status_aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', help_text='Status de aprovação da ordem', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='quantidade_produzida',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade efetivamente produzida e aprovada'),
        ),
    ]
