# Generated by Django 5.2.6 on 2025-11-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0164_refactor_ordem_producao_3_fases'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaostock',
            name='ordem_producao',
            field=models.ForeignKey(blank=True, help_text='Ordem de produção associada (para requisições de consumo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_material', to='empresa.ordemproducao'),
        ),
        migrations.AlterField(
            model_name='requisicaostock',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, help_text='Sucursal que fornece (será definida quando adicionar itens). Se vazio, é requisição de consumo para produção.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_recebidas', to='empresa.sucursal'),
        ),
    ]
