# Generated by Django 5.2.6 on 2025-11-07 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0165_add_ordem_producao_to_requisicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemproducao',
            name='requisicao_material_id',
        ),
        migrations.RemoveField(
            model_name='requisicaostock',
            name='ordem_producao',
        ),
        migrations.AlterField(
            model_name='requisicaostock',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, help_text='Sucursal que fornece (será definida quando adicionar itens). Requisições de produção usam RequisicaoProducao.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_recebidas', to='empresa.sucursal'),
        ),
        migrations.CreateModel(
            name='RequisicaoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da requisição de produção', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', help_text='Status da requisição', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a requisição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_atendimento', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, help_text='Usuário que aprovou a requisição (armazém)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_producao_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(help_text='Usuário que criou a requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_producao_criadas', to=settings.AUTH_USER_MODEL)),
                ('ordem_producao', models.ForeignKey(help_text='Ordem de produção associada', on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_material', to='empresa.ordemproducao')),
                ('sucursal_origem', models.ForeignKey(help_text='Sucursal que solicita (armazém)', on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_producao_enviadas', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Requisição de Produção',
                'verbose_name_plural': 'Requisições de Produção',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='requisicao_material',
            field=models.ForeignKey(blank=True, help_text='Requisição de material de produção associada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_producao_rel', to='empresa.requisicaoproducao'),
        ),
        migrations.CreateModel(
            name='ItemRequisicaoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField(help_text='Quantidade solicitada')),
                ('quantidade_atendida', models.PositiveIntegerField(default=0, help_text='Quantidade efetivamente atendida pelo armazém')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre este item')),
                ('item', models.ForeignKey(help_text='Material solicitado', on_delete=django.db.models.deletion.CASCADE, to='empresa.item')),
                ('requisicao', models.ForeignKey(help_text='Requisição de produção a que pertence este item', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresa.requisicaoproducao')),
            ],
            options={
                'verbose_name': 'Item de Requisição de Produção',
                'verbose_name_plural': 'Itens de Requisição de Produção',
                'unique_together': {('requisicao', 'item')},
            },
        ),
    ]
