# Generated by Django 5.2.6 on 2025-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0166_criar_requisicao_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='plano_corte_pdf',
            field=models.FileField(blank=True, help_text='Documento PDF do plano de corte', null=True, upload_to='receitas/planos_corte/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='documento_pdf',
            field=models.FileField(blank=True, help_text='Documento PDF do projeto da receita (especificações técnicas, desenhos, etc.)', null=True, upload_to='receitas/documentos/%Y/%m/%d/'),
        ),
    ]
