# Generated by Django 5.2.6 on 2025-11-10 11:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0167_add_plano_corte_pdf_to_receita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do cliente', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email do cliente', max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, help_text='Telefone do cliente', max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo do cliente', null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o cliente', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('ativo', models.BooleanField(default=True, help_text='Cliente ativo')),
            ],
            options={
                'verbose_name': 'Cliente de Serviço',
                'verbose_name_plural': 'Clientes de Serviço',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da ordem de serviço', max_length=20, unique=True)),
                ('data_agendada', models.DateTimeField(help_text='Data e hora agendada para prestação do serviço')),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data e hora de início real do serviço', null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data e hora de conclusão do serviço', null=True)),
                ('endereco_servico', models.TextField(help_text='Endereço onde o serviço será prestado')),
                ('cidade_servico', models.CharField(blank=True, help_text='Cidade onde o serviço será prestado', max_length=100, null=True)),
                ('equipe', models.CharField(blank=True, help_text='Equipe responsável pelo serviço', max_length=200, null=True)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em Andamento'), ('PAUSADA', 'Pausada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='AGENDADA', help_text='Status da ordem de serviço', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', help_text='Prioridade da ordem', max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantidade do serviço (ex: horas, unidades, etc.)', max_digits=10)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário do serviço', max_digits=10, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto aplicado', max_digits=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total do serviço (calculado automaticamente)', max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o serviço', null=True)),
                ('problema_relatado', models.TextField(blank=True, help_text='Problema relatado pelo cliente', null=True)),
                ('solucao_aplicada', models.TextField(blank=True, help_text='Solução aplicada', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação da ordem')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('cliente', models.ForeignKey(help_text='Cliente que receberá o serviço', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='empresa.clienteservico')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que criou a ordem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_criadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, help_text='Responsável técnico pelo serviço', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_responsavel', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(help_text='Serviço a ser prestado', limit_choices_to={'produto_tipo': 'SERVICO', 'tipo': 'PRODUTO'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='empresa.item')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_agendada', '-data_criacao'],
            },
        ),
    ]
