# Generated by Django 5.2.6 on 2025-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0168_clienteservico_ordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='forma_pagamento',
            field=models.CharField(choices=[('PRONTO_PAGAMENTO', 'Pronto Pagamento'), ('POR_CONTA', 'Por Conta')], default='PRONTO_PAGAMENTO', help_text='Forma de pagamento', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nome_cliente_pagamento',
            field=models.CharField(blank=True, help_text='Nome do cliente (obrigatório para pronto pagamento)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nuit_cliente_pagamento',
            field=models.CharField(blank=True, help_text='NUIT do cliente (opcional para pronto pagamento)', max_length=20, null=True),
        ),
    ]
