# Generated by Django 5.2.6 on 2025-11-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0169_ordemservico_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='forma_pagamento',
            field=models.CharField(choices=[('PRONTO_PAGAMENTO', 'PRONTO PAGAMENTO'), ('CREDITO', 'CREDITO')], default='PRONTO_PAGAMENTO', help_text='Forma de pagamento', max_length=20),
        ),
    ]
