# Generated by Django 5.2.6 on 2025-11-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0170_alter_ordemservico_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='telefone_cliente_pagamento',
            field=models.CharField(blank=True, help_text='Telefone/Contato do cliente (opcional para pronto pagamento)', max_length=20, null=True),
        ),
    ]
