# Generated by Django 5.2.6 on 2025-11-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0171_ordemservico_telefone_cliente_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteservico',
            name='nuit',
            field=models.CharField(blank=True, help_text='Número Único de Identificação Tributária (NUIT)', max_length=20, null=True),
        ),
    ]
