# Generated by Django 5.2.6 on 2025-11-11 13:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0172_clienteservico_nuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantidade do item', max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitário do item', max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto aplicado ao item', max_digits=10)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o item', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do item')),
                ('item', models.ForeignKey(help_text='Produto ou material', limit_choices_to={'tipo__in': ['PRODUTO', 'MATERIAL']}, on_delete=django.db.models.deletion.CASCADE, to='empresa.item')),
                ('ordem_servico', models.ForeignKey(help_text='Orçamento de serviço', on_delete=django.db.models.deletion.CASCADE, related_name='itens_orcamento', to='empresa.ordemservico')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'ordering': ['-data_criacao'],
                'unique_together': {('ordem_servico', 'item')},
            },
        ),
    ]
