# Generated by Django 5.2.6 on 2025-11-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0173_itemorcamentoservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteOrcamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(choices=[('INTERNO', 'Veículo Interno'), ('EXTERNO', 'Transportadora Externa')], default='EXTERNO', help_text='Tipo de transporte', max_length=30)),
                ('valor_frete', models.DecimalField(decimal_places=2, help_text='Valor do frete/transporte', max_digits=10)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o transporte', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('ordem_servico', models.ForeignKey(help_text='Orçamento de serviço', on_delete=django.db.models.deletion.CASCADE, related_name='transportes_orcamento', to='empresa.ordemservico')),
                ('transportadora', models.ForeignKey(help_text='Transportadora ou veículo', on_delete=django.db.models.deletion.PROTECT, to='empresa.transportadora')),
            ],
            options={
                'verbose_name': 'Transporte de Orçamento',
                'verbose_name_plural': 'Transportes de Orçamento',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
