# Generated by Django 5.2.6 on 2025-11-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0174_transporteorcamentoservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='Dia da semana (0=Segunda, 1=Terça, ..., 6=Domingo)')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se este horário está ativo')),
                ('hora_inicio', models.TimeField(help_text='Hora de início do expediente')),
                ('hora_fim', models.TimeField(help_text='Hora de fim do expediente')),
                ('duracao_almoco', models.DurationField(default='01:00:00', help_text='Duração da pausa para almoço')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do horário')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data de última atualização')),
                ('sucursal', models.ForeignKey(help_text='Sucursal a que pertence este horário', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_expediente', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Horário de Expediente',
                'verbose_name_plural': 'Horários de Expediente',
                'ordering': ['sucursal', 'dia_semana'],
                'unique_together': {('sucursal', 'dia_semana')},
            },
        ),
    ]
