# Generated by Django 5.2.6 on 2025-11-11 14:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0175_horarioexpediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='servico',
            field=models.ForeignKey(blank=True, help_text='Serviço principal (legado - use servicos_orcamento para múltiplos serviços)', limit_choices_to={'produto_tipo': 'SERVICO', 'tipo': 'PRODUTO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_legado', to='empresa.item'),
        ),
        migrations.CreateModel(
            name='ServicoOrcamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantidade do serviço', max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitário do serviço', max_digits=10)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto percentual aplicado', max_digits=5)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto aplicado ao serviço (valor fixo)', max_digits=10)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o serviço', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('ordem_servico', models.ForeignKey(help_text='Orçamento de serviço', on_delete=django.db.models.deletion.CASCADE, related_name='servicos_orcamento', to='empresa.ordemservico')),
                ('servico', models.ForeignKey(help_text='Serviço a ser prestado', limit_choices_to={'produto_tipo': 'SERVICO', 'tipo': 'PRODUTO'}, on_delete=django.db.models.deletion.CASCADE, to='empresa.item')),
            ],
            options={
                'verbose_name': 'Serviço de Orçamento',
                'verbose_name_plural': 'Serviços de Orçamento',
                'ordering': ['-data_criacao'],
                'unique_together': {('ordem_servico', 'servico')},
            },
        ),
    ]
