# Generated by Django 5.2.6 on 2025-11-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0176_alter_ordemservico_servico_servicoorcamentoservico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemorcamentoservico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemorcamentoservico',
            name='servico_orcamento',
            field=models.ForeignKey(blank=True, help_text='Serviço do orçamento ao qual este item pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresa.servicoorcamentoservico'),
        ),
        migrations.AlterField(
            model_name='itemorcamentoservico',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, help_text='Orçamento de serviço (legado - use servico_orcamento)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_orcamento_legado', to='empresa.ordemservico'),
        ),
        migrations.AlterUniqueTogether(
            name='itemorcamentoservico',
            unique_together={('servico_orcamento', 'item')},
        ),
    ]
