# Generated by Django 5.2.6 on 2025-11-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0178_add_nome_documento_to_ordemservico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='nome_documento',
        ),
        migrations.AddField(
            model_name='servicoorcamentoservico',
            name='nome_documento',
            field=models.CharField(blank=True, help_text='Nome personalizado a ser apresentado no documento para este serviço (se não preenchido, usa o nome do serviço)', max_length=200, null=True),
        ),
    ]
