# Generated by Django 5.2.6 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0179_move_nome_documento_to_servico_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='nome_documento',
            field=models.CharField(blank=True, help_text='Nome personalizado a ser apresentado no documento da cotação (se não preenchido, usa o nome do cliente)', max_length=200, null=True),
        ),
    ]
