# Generated by Django 5.2.6 on 2025-11-12 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0180_add_nome_documento_to_ordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente que receberá o serviço (opcional para pronto pagamento)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='empresa.clienteservico'),
        ),
    ]
