# Generated by Django 5.2.6 on 2025-11-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0181_allow_null_cliente_ordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='forma_pagamento',
            field=models.CharField(choices=[('PRONTO_PAGAMENTO', 'CASH'), ('CREDITO', 'CREDITO')], default='PRONTO_PAGAMENTO', help_text='Forma de pagamento', max_length=20),
        ),
    ]
