# Generated by Django 5.2.6 on 2025-11-12 13:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0182_update_forma_pagamento_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configuração Padrão', help_text='Nome da configuração', max_length=100, unique=True)),
                ('taxa_iva', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taxa de IVA em percentual (ex: 16.00 para 16%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('ativo', models.BooleanField(default=True, help_text='Indica se esta configuração está ativa')),
                ('padrao', models.BooleanField(default=True, help_text='Indica se esta é a configuração padrão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Fiscal',
                'verbose_name_plural': 'Configurações Fiscais',
                'ordering': ['-padrao', '-ativo', 'nome'],
            },
        ),
    ]
