# Generated by Django 5.2.6 on 2025-11-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0183_add_configuracao_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='orcamento_origem',
            field=models.ForeignKey(blank=True, help_text='Cotação/Orçamento original que gerou esta ordem de serviço', limit_choices_to={'codigo__startswith': 'COT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_geradas', to='empresa.ordemservico'),
        ),
    ]
