# Generated by Django 5.2.6 on 2025-11-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0184_add_orcamento_origem_to_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='numero_impressao_fatura',
            field=models.IntegerField(default=0, help_text='Número de vezes que a fatura foi impressa (0 = ainda não impressa, 1+ = número da cópia)'),
        ),
    ]
