# Generated by Django 5.2.7 on 2025-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0185_add_numero_impressao_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosempresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logotipo oficial utilizado em documentos e relatórios', null=True, upload_to='logos_empresas/'),
        ),
    ]
