# Generated by Django 5.2.7 on 2025-11-20 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0186_dadosempresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosempresa',
            name='logo',
            field=models.FileField(blank=True, help_text='Logotipo oficial utilizado em documentos e relatórios', null=True, upload_to='logos_empresas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])]),
        ),
    ]
