# Generated by Django 5.2.8 on 2025-11-28 21:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0187_alter_dadosempresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamentoservico',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto percentual aplicado ao item', max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemorcamentoservico',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto aplicado ao item (valor fixo)', max_digits=10),
        ),
    ]
