# Generated by Django 5.2.6 on 2025-12-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0188_add_desconto_percentual_item_orcamento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicoorcamentoservico',
            unique_together=set(),
        ),
    ]
