# Generated by Django 5.2.6 on 2025-12-02 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0189_remove_unique_together_servico_orcamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosempresa',
            name='cargo_representante',
            field=models.CharField(blank=True, default='Responsável', help_text='Cargo do representante legal (ex: Diretor, Gerente, Responsável)', max_length=100, verbose_name='Cargo do Representante'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='representante_legal',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pela empresa (usado em contratos e documentos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_representadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Empresa'),
        ),
    ]
