# Generated by Django 5.2.6 on 2025-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0190_add_representante_legal_to_dados_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='numero_impressao_garantia',
            field=models.IntegerField(default=0, help_text='Número de vezes que a garantia foi impressa (0 = ainda não impressa, 1+ = número da cópia)'),
        ),
    ]
