# Generated by Django 5.2.6 on 2025-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0191_ordemservico_numero_impressao_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='validade_garantia_dias',
            field=models.IntegerField(default=90, help_text='Validade da garantia em dias (padrão: 90 dias)'),
        ),
    ]
