# Generated by Django 5.2.6 on 2025-12-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0192_ordemservico_validade_garantia_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da equipe', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da equipe e suas responsabilidades', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Equipe ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('lider', models.ForeignKey(blank=True, help_text='Líder/Responsável da equipe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to='empresa.funcionario')),
                ('membros', models.ManyToManyField(blank=True, help_text='Membros da equipe', related_name='equipes', to='empresa.funcionario')),
            ],
            options={
                'verbose_name': 'Equipe de Serviço',
                'verbose_name_plural': 'Equipes de Serviço',
                'ordering': ['nome'],
            },
        ),
    ]
