# Generated by Django 5.2.6 on 2025-12-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0193_add_equipe_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicoorcamentoservico',
            options={'ordering': ['data_criacao'], 'verbose_name': 'Serviço de Orçamento', 'verbose_name_plural': 'Serviços de Orçamento'},
        ),
        migrations.AddField(
            model_name='clienteservico',
            name='isento_iva',
            field=models.BooleanField(default=False, help_text='Cliente isento de IVA'),
        ),
    ]
