# Generated by Django 5.2.6 on 2026-01-22 10:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0194_add_isento_iva_to_clienteservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da forma de pagamento (ex: "Pagamento Parcelado", "À Vista", etc.)', max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da forma de pagamento', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se esta forma de pagamento está ativa')),
                ('padrao', models.BooleanField(default=False, help_text='Indica se esta é a forma de pagamento padrão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['-padrao', '-ativo', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='forma_pagamento',
            field=models.CharField(choices=[('PRONTO_PAGAMENTO', 'CASH'), ('CREDITO', 'CREDITO')], default='PRONTO_PAGAMENTO', help_text='Forma de pagamento (legado)', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='forma_pagamento_configurada',
            field=models.ForeignKey(blank=True, help_text='Forma de pagamento configurável com períodos nomeados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='empresa.formapagamento'),
        ),
        migrations.CreateModel(
            name='PeriodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do período (ex: "Entrada", "1ª Parcela", "Finalização", etc.)', max_length=100)),
                ('percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual do valor total a ser pago neste período', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('dias_apos_evento', models.IntegerField(default=0, help_text='Número de dias após o evento de referência (0 = no evento, ex: assinatura)')),
                ('evento_referencia', models.CharField(choices=[('ASSINATURA', 'Assinatura do Contrato'), ('INICIO', 'Início dos Serviços'), ('CONCLUSAO', 'Conclusão dos Serviços'), ('ENTREGA', 'Entrega do Serviço')], default='ASSINATURA', help_text='Evento de referência para calcular a data de pagamento', max_length=50)),
                ('ordem', models.IntegerField(default=1, help_text='Ordem de exibição do período')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre este período', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('forma_pagamento', models.ForeignKey(help_text='Forma de pagamento a que este período pertence', on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='empresa.formapagamento')),
            ],
            options={
                'verbose_name': 'Período de Pagamento',
                'verbose_name_plural': 'Períodos de Pagamento',
                'ordering': ['forma_pagamento', 'ordem'],
                'unique_together': {('forma_pagamento', 'ordem')},
            },
        ),
    ]
