# Generated by Django 5.2.6 on 2026-02-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0196_add_clausulas_contrato_to_ordemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoContratoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Contrato Padrão', help_text='Nome desta configuração de contrato (ex: Contrato Padrão, Obra Civil, Serviços TI, etc.)', max_length=200)),
                ('ativo', models.BooleanField(default=True, help_text='Se marcado, esta configuração pode ser usada nas views do contrato.')),
                ('padrao', models.BooleanField(default=True, help_text='Configuração padrão utilizada quando nenhuma outra for escolhida.')),
                ('clausula4_obrigacoes', models.TextField(blank=True, help_text='Texto (HTML permitido) para a cláusula de Obrigações das Partes.', null=True)),
                ('clausula5_garantia', models.TextField(blank=True, help_text='Texto (HTML permitido) para a cláusula de Garantia. Pode usar {{ validade_garantia_dias }} para inserir o número de dias de garantia.', null=True)),
                ('clausula6_alteracoes', models.TextField(blank=True, help_text='Texto (HTML permitido) para a cláusula de Alterações do Contrato.', null=True)),
                ('clausula7_rescisao', models.TextField(blank=True, help_text='Texto (HTML permitido) para a cláusula de Rescisão.', null=True)),
                ('clausula8_confidencialidade', models.TextField(blank=True, help_text='Texto (HTML permitido) para a cláusula de Confidencialidade.', null=True)),
                ('clausula9_foro', models.TextField(blank=True, help_text='Texto (HTML permitido) para a cláusula de Legislação e Foro.', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Contrato de Serviço',
                'verbose_name_plural': 'Configurações de Contrato de Serviço',
                'ordering': ['-padrao', '-ativo', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='clausula4_obrigacoes',
            field=models.TextField(blank=True, help_text='Cláusula 4 - Obrigações das Partes (editável pelo utilizador antes da confirmação)', null=True),
        ),
    ]
