# Generated by Django 5.2.6 on 2026-02-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0197_configuracaocontratoservico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='clausula2_pagamento',
            field=models.TextField(blank=True, help_text='Cláusula 2.2 - Condições de Pagamento (editável pelo utilizador antes da confirmação)', null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='clausula3_prazo',
            field=models.TextField(blank=True, help_text='Cláusula 3 - Prazo de Execução (editável pelo utilizador antes da confirmação)', null=True),
        ),
    ]
