# Generated by Django 5.2.6 on 2026-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0198_ordemservico_clausula2_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='prazo_excluir_feriados',
            field=models.BooleanField(default=True, help_text='Se o prazo exclui feriados nacionais'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prazo_excluir_fins_semana',
            field=models.BooleanField(default=True, help_text='Se o prazo exclui sábados e domingos (dias úteis)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prazo_execucao_numero',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Número do prazo de execução (ex.: 30 para 30 dias/meses)', null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prazo_execucao_unidade',
            field=models.CharField(blank=True, choices=[('DIAS', 'Dias'), ('MESES', 'Meses'), ('ANOS', 'Anos')], default='MESES', help_text='Unidade do prazo de execução (dias, meses ou anos)', max_length=10),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='validade_garantia_unidade',
            field=models.CharField(blank=True, choices=[('DIAS', 'Dias'), ('MESES', 'Meses'), ('ANOS', 'Anos')], default='DIAS', help_text='Unidade em que a garantia é expressa no contrato (dias, meses ou anos)', max_length=10),
        ),
    ]
