# Generated by Django 5.2.6 on 2026-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0199_contrato_prazo_garantia_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='pagamento_percentagem_assinatura',
            field=models.PositiveSmallIntegerField(blank=True, default=50, help_text='Percentagem a pagar no ato da assinatura (deve somar 100 com percentagem conclusão)', null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pagamento_percentagem_conclusao',
            field=models.PositiveSmallIntegerField(blank=True, default=50, help_text='Percentagem a pagar na conclusão dos serviços (deve somar 100 com percentagem assinatura)', null=True),
        ),
    ]
