# Generated by Django 5.2.6 on 2026-02-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0200_pagamento_percentagens_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaPagamentoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.PositiveSmallIntegerField(help_text='Ordem da parcela (1, 2, 3, ...)')),
                ('percentagem', models.PositiveSmallIntegerField(help_text='Percentagem do valor total a pagar nesta parcela (0-100)')),
                ('tipo', models.CharField(choices=[('ASSINATURA', 'À assinatura do contrato'), ('CONCLUSAO_SERVICOS', 'Na conclusão dos serviços seleccionados'), ('CONCLUSAO_TOTAL', 'Na conclusão total dos serviços')], default='CONCLUSAO_TOTAL', help_text='Momento em que esta parcela é exigível', max_length=24)),
                ('ordem_servico', models.ForeignKey(help_text='Orçamento/cotação a que pertence esta parcela', on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_pagamento', to='empresa.ordemservico')),
                ('servicos', models.ManyToManyField(blank=True, help_text='Serviços da cotação cuja conclusão exige o pagamento desta parcela (apenas quando tipo = Na conclusão dos serviços seleccionados)', related_name='parcelas_pagamento_que_exigem', to='empresa.servicoorcamentoservico')),
            ],
            options={
                'verbose_name': 'Parcela de pagamento (contrato)',
                'verbose_name_plural': 'Parcelas de pagamento (contrato)',
                'ordering': ['ordem_servico', 'numero_ordem'],
                'unique_together': {('ordem_servico', 'numero_ordem')},
            },
        ),
    ]
