# Generated by Django 5.2.6 on 2026-02-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0201_parcelas_pagamento_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='obrigacao_contratada_1',
            field=models.CharField(blank=True, help_text='Obrigação 1 da CONTRATADA', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='obrigacao_contratada_2',
            field=models.CharField(blank=True, help_text='Obrigação 2 da CONTRATADA', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='obrigacao_contratada_3',
            field=models.CharField(blank=True, help_text='Obrigação 3 da CONTRATADA', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='obrigacao_contratante_1',
            field=models.CharField(blank=True, help_text='Obrigação 1 do CONTRATANTE', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='obrigacao_contratante_2',
            field=models.CharField(blank=True, help_text='Obrigação 2 do CONTRATANTE', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='obrigacao_contratante_3',
            field=models.CharField(blank=True, help_text='Obrigação 3 do CONTRATANTE', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='clausula4_obrigacoes',
            field=models.TextField(blank=True, help_text='Cláusula 4 - Obrigações das Partes (HTML livre; usado se obrigações estruturadas não estiverem todas preenchidas)', null=True),
        ),
    ]
