# Generated by Django 5.2.6 on 2026-02-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0202_obrigacoes_estruturadas_clausula4'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosempresa',
            name='conta_bci',
            field=models.CharField(blank=True, help_text='IBAN ou número da conta bancária BCI', max_length=80, verbose_name='Conta BCI'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='conta_emola',
            field=models.CharField(blank=True, help_text='Número ou referência e-Mola para pagamentos', max_length=50, verbose_name='Conta e-Mola'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='conta_millennium_bim',
            field=models.CharField(blank=True, help_text='IBAN ou número da conta bancária Millennium BIM', max_length=80, verbose_name='Conta Millennium BIM'),
        ),
        migrations.AddField(
            model_name='dadosempresa',
            name='conta_mpesa',
            field=models.CharField(blank=True, help_text='Número ou referência M-Pesa para pagamentos', max_length=50, verbose_name='Conta M-Pesa'),
        ),
    ]
