# Generated by Django 5.2.6 on 2026-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0203_contas_pagamento_dados_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosempresa',
            name='validade_cotacao',
            field=models.CharField(blank=True, help_text='Texto exibido na cotação/orçamento (ex.: "30 dias", "15 dias úteis", "Válida até à data indicada")', max_length=120, verbose_name='Validade da cotação'),
        ),
    ]
