# Generated by Django 5.2.6 on 2026-02-05 18:41

import meuprojeto.empresa.models_rh
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0204_validade_cotacao_dados_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone do operador (ex.: +258841234567). Usado em "Processado Por" na cotação. Se vazio e houver funcionário associado, usa o telefone do funcionário.', max_length=13, null=True, validators=[meuprojeto.empresa.models_rh.validar_telefone_moz], verbose_name='Telefone do utilizador'),
        ),
    ]
