# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0205_perfil_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='prazo_fins_semana_modo',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '— usar opção clássica (checkbox abaixo) —'),
                    ('SABADO_DOMINGO', 'Excluir sábados e domingos (apenas dias úteis)'),
                    ('SO_DOMINGO', 'Excluir apenas domingos (sábado conta como dia útil)'),
                    ('SABADO_MEIO', 'Sábado conta como meio dia; domingo excluído'),
                    ('CORRIDOS', 'Dias corridos (não excluir fins de semana)'),
                ],
                help_text='Como contar fins de semana no prazo: excluir ambos, só domingo, sábado meio dia, ou corridos.',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='incluir_clausula_suspensao_clima',
            field=models.BooleanField(
                default=False,
                help_text='Incluir no contrato cláusula que permite suspender actividades quando as condições climáticas não forem favoráveis.'
            ),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='clausula_suspensao_clima',
            field=models.TextField(
                blank=True,
                help_text='Texto opcional da cláusula de suspensão por condições climáticas. Se vazio, usa texto padrão.',
                null=True
            ),
        ),
    ]
