# Generated by Django 5.2.6 on 2026-02-05 22:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0206_prazo_fins_semana_modo_suspensao_clima'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='prazo_excluir_fins_semana',
            field=models.BooleanField(default=True, help_text='Se o prazo exclui sábados e domingos (dias úteis). Mantido por compatibilidade; use prazo_fins_semana_modo para mais opções.'),
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código da conta (ex: 11.01, 71.01)', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome da conta', max_length=200)),
                ('tipo', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PATRIMONIO', 'Património líquido'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], help_text='Natureza da conta para balanço e DRE', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conta_pai', models.ForeignKey(blank=True, help_text='Conta pai na hierarquia do plano', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontas', to='empresa.conta')),
            ],
            options={
                'verbose_name': 'Conta (Plano de Contas)',
                'verbose_name_plural': 'Contas (Plano de Contas)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do movimento')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor (positivo = entrada/crédito, negativo = saída/débito conforme conta)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('-999999999999.99'))])),
                ('descricao', models.CharField(help_text='Descrição do movimento', max_length=500)),
                ('documento_ref', models.CharField(blank=True, help_text='Referência do documento (factura, recibo, etc.)', max_length=100)),
                ('origem_tipo', models.CharField(choices=[('MANUAL', 'Lançamento manual'), ('VENDAS', 'Vendas (fatura/OS)'), ('COMPRAS', 'Compras'), ('RH', 'RH (folha de pagamento)'), ('LOGISTICA', 'Logística (custos/faturamento)')], default='MANUAL', max_length=20)),
                ('origem_id', models.PositiveIntegerField(blank=True, help_text='ID do registo de origem (ex: OrdemServico.id, OrdemCompra.id)', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(help_text='Conta do plano de contas', on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='empresa.conta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento financeiro',
                'verbose_name_plural': 'Lançamentos financeiros',
                'ordering': ['-data', '-data_criacao'],
            },
        ),
    ]
