# Generated by Django 5.2.6 on 2026-02-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0207_add_plano_contas_lancamentos_financas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorSerieDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(help_text='Ex: FT, RC, NC', max_length=20)),
                ('ano', models.PositiveIntegerField(help_text='Ano (ex: 2025)')),
                ('proximo_numero', models.PositiveIntegerField(default=1, help_text='Próximo número a atribuir (incrementa após uso)')),
                ('descricao', models.CharField(blank=True, help_text='Ex: Factura de venda', max_length=100)),
            ],
            options={
                'verbose_name': 'Contador de série (numeração legal)',
                'verbose_name_plural': 'Contadores de série',
                'ordering': ['serie', '-ano'],
                'unique_together': {('serie', 'ano')},
            },
        ),
    ]
