# Generated by Django 5.2.6 on 2026-02-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0208_add_contador_serie_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='numero_fatura_fiscal',
            field=models.CharField(blank=True, help_text='Número da fatura para efeitos fiscais (ex: FT-2025-000001), preenchido na primeira emissão', max_length=30),
        ),
    ]
