# Generated by Django 5.2.6 on 2026-02-05 23:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0209_add_numero_fatura_fiscal_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='taxa_irpc',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('32.00'), help_text='Taxa de IRPC em percentual (ex: 32.00 para 32%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
