# Generated by Django (add prazo retenção documentos)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0210_add_taxa_irpc_configuracao_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='prazo_retencao_documentos_anos',
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=10,
                help_text='Prazo de conservação de documentos fiscais/contabilísticos em anos (ex.: 10 anos - Lei MZ)',
                null=True
            ),
        ),
    ]
