# Generated by Django (add LogAuditoria)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0211_add_prazo_retencao_configuracao_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.PositiveIntegerField(db_index=True)),
                ('acao', models.CharField(choices=[('CREATED', 'Criado'), ('UPDATED', 'Alterado'), ('DELETED', 'Eliminado')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dados_resumo', models.CharField(blank=True, help_text='Resumo dos dados alterados (ex: valor, conta)', max_length=500)),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de auditoria',
                'verbose_name_plural': 'Registos de auditoria',
                'ordering': ['-data'],
            },
        ),
    ]
