# Generated by Django 5.2.6 on 2026-02-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0212_add_log_auditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'ordering': ['codigo'], 'permissions': [('acesso_financas', 'Pode aceder ao módulo Finanças')], 'verbose_name': 'Conta (Plano de Contas)', 'verbose_name_plural': 'Contas (Plano de Contas)'},
        ),
    ]
