# Generated by Django 5.2.6 on 2026-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0214_seed_plano_contas_pgc_nirf_mz'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcompra',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data em que foi registado o pagamento ao fornecedor; preenchido ao marcar ordem como paga', null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_cobranca',
            field=models.DateField(blank=True, help_text='Data em que foi registada a cobrança (cliente pagou); preenchido ao marcar fatura como paga', null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='codigo',
            field=models.CharField(help_text='Código da conta PGC-NIRF MZ (ex: 11.01 Activo, 61.01/62.01/63.01 Gastos, 71.01/72.01 Receitas)', max_length=20, unique=True),
        ),
    ]
