# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0215_add_data_cobranca_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='departamento_origem',
            field=models.CharField(
                blank=True,
                choices=[('VENDAS', 'Vendas'), ('PRODUCAO', 'Produção')],
                help_text='Módulo onde o orçamento foi confirmado / ordem criada (Vendas ou Produção)',
                max_length=20,
                null=True,
            ),
        ),
    ]
