# Generated by Django 5.2.6

from django.db import migrations


def create_groups(apps, schema_editor):
    from django.contrib.auth.models import Group
    Group.objects.get_or_create(name='Vendas')
    Group.objects.get_or_create(name='Produção')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0216_ordemservico_departamento_origem'),
    ]

    operations = [
        migrations.RunPython(create_groups, noop),
    ]
