# Generated by Django 5.2.6 on 2026-02-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0217_seed_grupos_vendas_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('MANUAL', 'Lançamento manual'), ('VENDAS', 'Vendas (fatura/OS)'), ('COMPRAS', 'Compras'), ('RH', 'RH (folha de pagamento)'), ('RH_TREINAMENTO', 'RH (treinamentos)'), ('LOGISTICA', 'Logística (custos/faturamento)')], default='MANUAL', max_length=20),
        ),
    ]
