# Generated by Django 5.2.6 on 2026-02-15 20:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0219_add_transferencia_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('MANUAL', 'Lançamento manual'), ('VENDAS', 'Vendas (fatura/OS)'), ('COMPRAS', 'Compras'), ('RH', 'RH (folha de pagamento)'), ('RH_TREINAMENTO', 'RH (treinamentos)'), ('RH_EMPREITADA', 'RH (empreitada/trabalho por tarefa)'), ('LOGISTICA', 'Logística (custos/faturamento)'), ('TRANSFERENCIA', 'Transferência entre sucursais')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='TrabalhoEmpreitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição do trabalho')),
                ('valor_fixo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor fixo (MT)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('incluir_na_folha', models.BooleanField(default=True, help_text='Se marcado, ao concluir o valor será adicionado à folha do mês de conclusão', verbose_name='Incluir na folha de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos_empreitada', to='empresa.funcionario', verbose_name='Funcionário/Prestador')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos_empreitada', to='empresa.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Trabalho por empreitada',
                'verbose_name_plural': 'Trabalhos por empreitada',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
