# Generated by Django 5.2.6 on 2026-02-15 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0220_add_trabalho_empreitada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SINGULAR', 'Pessoa singular'), ('EMPRESA', 'Empresa')], default='SINGULAR', max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(help_text='Nome completo (singular) ou razão social (empresa)', max_length=200, verbose_name='Nome / Razão social')),
                ('representante_legal', models.CharField(blank=True, help_text='Apenas para empresas: nome do representante', max_length=200, verbose_name='Representante legal')),
                ('contacto', models.CharField(blank=True, max_length=50, verbose_name='Contacto/Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nuit', models.CharField(blank=True, max_length=20, verbose_name='NUIT')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestador de Serviços',
                'verbose_name_plural': 'Prestadores de Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='trabalhoempreitada',
            name='funcionario',
            field=models.ForeignKey(blank=True, help_text='Funcionário da empresa (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos_empreitada', to='empresa.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='trabalhoempreitada',
            name='incluir_na_folha',
            field=models.BooleanField(default=True, help_text='Apenas para funcionários: adiciona o valor à folha do mês de conclusão', verbose_name='Incluir na folha de pagamento'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='prestador',
            field=models.ForeignKey(blank=True, help_text='Prestador externo (se não for funcionário)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos_empreitada', to='empresa.prestadorservico', verbose_name='Prestador de Serviços'),
        ),
    ]
