# Generated by Django 5.2.6 on 2026-02-15 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0222_remove_funcionario_empreitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='servico_orcamento',
            field=models.ForeignKey(blank=True, help_text='Serviço da ordem (cotado, aprovado e em execução)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos_empreitada', to='empresa.servicoorcamentoservico', verbose_name='Serviço cotado/orçamento'),
        ),
    ]
