# Generated by Django 5.2.6 on 2026-02-15 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0223_trabalhoempreitada_servico_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal que cotou o serviço (origem da cotação)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='empresa.sucursal'),
        ),
    ]
