# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0224_add_sucursal_ordem_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoContratoEmpreitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Contrato Empreitada Padrão', help_text='Nome desta configuração de contrato de empreitada.', max_length=200)),
                ('ativo', models.BooleanField(default=True, help_text='Se marcado, esta configuração pode ser usada.')),
                ('padrao', models.BooleanField(default=True, help_text='Configuração padrão utilizada quando nenhuma outra for escolhida.')),
                ('clausula4_obrigacoes', models.TextField(blank=True, help_text='Texto (HTML) para a cláusula de Obrigações das Partes.', null=True)),
                ('clausula5_garantia', models.TextField(blank=True, help_text='Texto (HTML) para Garantia. Pode usar {{ validade_garantia_dias }}.', null=True)),
                ('clausula6_alteracoes', models.TextField(blank=True, help_text='Texto (HTML) para Alterações do Contrato.', null=True)),
                ('clausula7_rescisao', models.TextField(blank=True, help_text='Texto (HTML) para Rescisão.', null=True)),
                ('clausula8_confidencialidade', models.TextField(blank=True, help_text='Texto (HTML) para Confidencialidade.', null=True)),
                ('clausula9_foro', models.TextField(blank=True, help_text='Texto (HTML) para Legislação e Foro.', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Contrato de Empreitada',
                'verbose_name_plural': 'Configurações de Contrato de Empreitada',
                'ordering': ['-padrao', '-ativo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='clausula2_pagamento',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula 2 - Pagamento'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='clausula3_prazo',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula 3 - Prazo'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='obrigacao_contratada_1',
            field=models.CharField(blank=True, help_text='Obrigação 1 da CONTRATADA (prestador)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='obrigacao_contratada_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='obrigacao_contratada_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='obrigacao_contratante_1',
            field=models.CharField(blank=True, help_text='Obrigação 1 do CONTRATANTE (empresa)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='obrigacao_contratante_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='obrigacao_contratante_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='clausula5_garantia',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula 5 - Garantia'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='clausula6_alteracoes',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula 6 - Alterações'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='clausula7_rescisao',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula 7 - Rescisão'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='clausula8_confidencialidade',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula 8 - Confidencialidade'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='clausula9_foro',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula 9 - Foro'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='prazo_execucao_numero',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Prazo execução (número)'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='prazo_execucao_unidade',
            field=models.CharField(blank=True, default='DIAS', max_length=10, null=True, verbose_name='Prazo execução (unidade)'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='validade_garantia_dias',
            field=models.PositiveIntegerField(blank=True, default=90, null=True, verbose_name='Garantia (dias)'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='validade_garantia_unidade',
            field=models.CharField(blank=True, default='DIAS', max_length=10, null=True, verbose_name='Garantia (unidade)'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='incluir_clausula_suspensao_clima',
            field=models.BooleanField(default=False, verbose_name='Incluir cláusula suspensão climática'),
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='clausula_suspensao_clima',
            field=models.TextField(blank=True, null=True, verbose_name='Texto cláusula suspensão climática'),
        ),
    ]
