# Generated by Django 5.2.6

import django.db.models.deletion
from django.db import migrations, models


def criar_contratos_consolidados(apps, schema_editor):
    """Cria ContratoEmpreitada para cada grupo (prestador, ordem_servico). Avulsos: um contrato por trabalho."""
    TrabalhoEmpreitada = apps.get_model('empresa', 'TrabalhoEmpreitada')
    ContratoEmpreitada = apps.get_model('empresa', 'ContratoEmpreitada')
    # Agrupar por (prestador_id, ordem_servico_id). Quando ordem_servico é None (avulso), cada trabalho é seu próprio grupo.
    grupos = {}
    for t in TrabalhoEmpreitada.objects.select_related('servico_orcamento', 'prestador').all():
        ordem_id = t.servico_orcamento.ordem_servico_id if t.servico_orcamento else None
        if ordem_id is not None:
            chave = (t.prestador_id, ordem_id)
        else:
            chave = (t.prestador_id, None, t.id)  # Avulso: um contrato por trabalho
        if chave not in grupos:
            grupos[chave] = []
        grupos[chave].append(t)
    for chave, trabalhos in grupos.items():
        prestador_id = chave[0]
        ordem_id = chave[1] if len(chave) == 2 else None
        primeiro = trabalhos[0]
        # unique_together (prestador, ordem_servico) - para avulsos (ordem=None) múltiplos são permitidos
        contrato = ContratoEmpreitada.objects.create(
            prestador_id=prestador_id,
            ordem_servico_id=ordem_id,
            clausula2_pagamento=primeiro.clausula2_pagamento,
            clausula3_prazo=primeiro.clausula3_prazo,
            obrigacao_contratada_1=primeiro.obrigacao_contratada_1,
            obrigacao_contratada_2=primeiro.obrigacao_contratada_2,
            obrigacao_contratada_3=primeiro.obrigacao_contratada_3,
            obrigacao_contratante_1=primeiro.obrigacao_contratante_1,
            obrigacao_contratante_2=primeiro.obrigacao_contratante_2,
            obrigacao_contratante_3=primeiro.obrigacao_contratante_3,
            clausula5_garantia=primeiro.clausula5_garantia,
            clausula6_alteracoes=primeiro.clausula6_alteracoes,
            clausula7_rescisao=primeiro.clausula7_rescisao,
            clausula8_confidencialidade=primeiro.clausula8_confidencialidade,
            clausula9_foro=primeiro.clausula9_foro,
            prazo_execucao_numero=primeiro.prazo_execucao_numero or 30,
            prazo_execucao_unidade=primeiro.prazo_execucao_unidade or 'DIAS',
            validade_garantia_dias=primeiro.validade_garantia_dias or 90,
            validade_garantia_unidade=primeiro.validade_garantia_unidade or 'DIAS',
            incluir_clausula_suspensao_clima=primeiro.incluir_clausula_suspensao_clima or False,
            clausula_suspensao_clima=primeiro.clausula_suspensao_clima,
        )
        for t in trabalhos:
            t.contrato_empreitada = contrato
            t.save(update_fields=['contrato_empreitada'])


def reverter_contratos(apps, schema_editor):
    """Remove vínculos antes de dropar a tabela."""
    TrabalhoEmpreitada = apps.get_model('empresa', 'TrabalhoEmpreitada')
    TrabalhoEmpreitada.objects.filter(contrato_empreitada__isnull=False).update(contrato_empreitada=None)


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0225_trabalhoempreitada_clausulas_configuracaocontratoempreitada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoEmpreitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula2_pagamento', models.TextField(blank=True, null=True, verbose_name='Cláusula 2 - Pagamento')),
                ('clausula3_prazo', models.TextField(blank=True, null=True, verbose_name='Cláusula 3 - Prazo')),
                ('obrigacao_contratada_1', models.CharField(blank=True, max_length=500, null=True)),
                ('obrigacao_contratada_2', models.CharField(blank=True, max_length=500, null=True)),
                ('obrigacao_contratada_3', models.CharField(blank=True, max_length=500, null=True)),
                ('obrigacao_contratante_1', models.CharField(blank=True, max_length=500, null=True)),
                ('obrigacao_contratante_2', models.CharField(blank=True, max_length=500, null=True)),
                ('obrigacao_contratante_3', models.CharField(blank=True, max_length=500, null=True)),
                ('clausula5_garantia', models.TextField(blank=True, null=True, verbose_name='Cláusula 5 - Garantia')),
                ('clausula6_alteracoes', models.TextField(blank=True, null=True, verbose_name='Cláusula 6 - Alterações')),
                ('clausula7_rescisao', models.TextField(blank=True, null=True, verbose_name='Cláusula 7 - Rescisão')),
                ('clausula8_confidencialidade', models.TextField(blank=True, null=True, verbose_name='Cláusula 8 - Confidencialidade')),
                ('clausula9_foro', models.TextField(blank=True, null=True, verbose_name='Cláusula 9 - Foro')),
                ('prazo_execucao_numero', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('prazo_execucao_unidade', models.CharField(blank=True, default='DIAS', max_length=10, null=True)),
                ('validade_garantia_dias', models.PositiveIntegerField(blank=True, default=90, null=True)),
                ('validade_garantia_unidade', models.CharField(blank=True, default='DIAS', max_length=10, null=True)),
                ('incluir_clausula_suspensao_clima', models.BooleanField(default=False)),
                ('clausula_suspensao_clima', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ordem_servico', models.ForeignKey(blank=True, help_text='Cotação à qual os trabalhos pertencem. Nulo para trabalhos avulsos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_empreitada', to='empresa.ordemservico', verbose_name='Cotação / Ordem de serviço')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_empreitada', to='empresa.prestadorservico', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Contrato de Empreitada',
                'verbose_name_plural': 'Contratos de Empreitada',
                'ordering': ['-data_criacao'],
                'unique_together': {('prestador', 'ordem_servico')},
            },
        ),
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='contrato_empreitada',
            field=models.ForeignKey(blank=True, help_text='Contrato que agrupa este trabalho (por prestador + cotação)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to='empresa.contratoempreitada', verbose_name='Contrato consolidado'),
        ),
        migrations.RunPython(criar_contratos_consolidados, reverter_contratos),
    ]
