# Generated by Django 5.2.6 on 2026-02-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0226_contrato_empreitada_consolidado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaPagamentoEmpreitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.PositiveSmallIntegerField(help_text='Ordem da parcela (1, 2, 3, ...)')),
                ('percentagem', models.PositiveSmallIntegerField(help_text='Percentagem do valor total a pagar nesta parcela (0-100)')),
                ('tipo', models.CharField(choices=[('ASSINATURA', 'À assinatura do contrato'), ('CONCLUSAO_TRABALHOS', 'Na conclusão dos trabalhos seleccionados'), ('CONCLUSAO_TOTAL', 'Na conclusão total dos trabalhos')], default='CONCLUSAO_TOTAL', help_text='Momento em que esta parcela é exigível', max_length=24)),
                ('data_pago', models.DateTimeField(blank=True, help_text='Preenchido quando a parcela foi paga (lançamento em Finanças criado)', null=True, verbose_name='Data de pagamento')),
                ('contrato_empreitada', models.ForeignKey(help_text='Contrato de empreitada a que pertence esta parcela', on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_pagamento', to='empresa.contratoempreitada')),
                ('trabalhos', models.ManyToManyField(blank=True, help_text='Trabalhos cuja conclusão exige o pagamento desta parcela (apenas quando tipo = Na conclusão dos trabalhos seleccionados)', related_name='parcelas_pagamento_que_exigem', to='empresa.trabalhoempreitada')),
            ],
            options={
                'verbose_name': 'Parcela de pagamento (empreitada)',
                'verbose_name_plural': 'Parcelas de pagamento (empreitada)',
                'ordering': ['contrato_empreitada', 'numero_ordem'],
                'unique_together': {('contrato_empreitada', 'numero_ordem')},
            },
        ),
    ]
