# Generated by Django 5.2.6 on 2026-02-16 07:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0227_parcelas_pagamento_empreitada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('MANUAL', 'Lançamento manual'), ('VENDAS', 'Vendas (fatura/OS)'), ('COMPRAS', 'Compras'), ('RH', 'RH (folha de pagamento)'), ('RH_TREINAMENTO', 'RH (treinamentos)'), ('RH_EMPREITADA', 'RH (empreitada/trabalho por tarefa)'), ('RH_EMP_PARCELA', 'RH (empreitada parcela)'), ('LOGISTICA', 'Logística (custos/faturamento)'), ('TRANSFERENCIA', 'Transferência entre sucursais')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='PendenteContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(choices=[('RH_EMP_PARCELA', 'RH (empreitada parcela)'), ('RH_EMPREITADA', 'RH (empreitada)'), ('RH_TREINAMENTO', 'RH (treinamento)'), ('COMPRAS', 'Compras'), ('LOGISTICA', 'Logística'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30)),
                ('origem_id', models.PositiveIntegerField(blank=True, help_text='ID do registo de origem', null=True)),
                ('beneficiario', models.CharField(help_text='Nome do prestador/fornecedor a pagar', max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor a pagar (MT)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descricao', models.CharField(help_text='Descrição do pagamento', max_length=500)),
                ('data_vencimento', models.DateField(blank=True, help_text='Data prevista de pagamento', null=True)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('REJEITADO', 'Rejeitado')], db_index=True, default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('url_origem', models.CharField(blank=True, help_text='URL para ver o documento de origem', max_length=500)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('lancamento', models.ForeignKey(blank=True, help_text='Lançamento criado após confirmação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendente_conta_pagar', to='empresa.lancamentofinanceiro')),
            ],
            options={
                'verbose_name': 'Pendente Conta a Pagar',
                'verbose_name_plural': 'Pendentes Contas a Pagar',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PendenteContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(choices=[('VENDAS_PARCELA', 'Vendas (parcela contrato)'), ('VENDAS_FATURA', 'Vendas (fatura)'), ('LOGISTICA', 'Logística (faturamento)'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30)),
                ('origem_id', models.PositiveIntegerField(blank=True, help_text='ID do registo de origem', null=True)),
                ('credor', models.CharField(help_text='Nome do cliente a cobrar', max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor a receber (MT)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descricao', models.CharField(help_text='Descrição do recebimento', max_length=500)),
                ('data_vencimento', models.DateField(blank=True, help_text='Data prevista de recebimento', null=True)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('REJEITADO', 'Rejeitado')], db_index=True, default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('url_origem', models.CharField(blank=True, help_text='URL para ver o documento de origem', max_length=500)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('lancamento', models.ForeignKey(blank=True, help_text='Lançamento criado após confirmação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendente_conta_receber', to='empresa.lancamentofinanceiro')),
            ],
            options={
                'verbose_name': 'Pendente Conta a Receber',
                'verbose_name_plural': 'Pendentes Contas a Receber',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
