# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0228_add_pendentes_contas_pagar_receber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da etapa/actividade (personalizável)', max_length=200)),
                ('numero_ordem', models.PositiveSmallIntegerField(default=1, help_text='Ordem de execução dentro do mesmo nível (1, 2, 3, ...)')),
                ('data_prevista_conclusao', models.DateField(blank=True, help_text='Prazo previsto para conclusão (para acompanhamento do cronograma)', null=True)),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data/hora real de início', null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data/hora real de conclusão', null=True)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em Andamento'), ('PAUSADA', 'Pausada'), ('CONCLUIDA', 'Concluída')], default='AGENDADA', help_text='Estado da actividade', max_length=20)),
                ('ordem_servico', models.ForeignKey(help_text='Ordem de serviço a que pertence esta etapa/actividade', on_delete=django.db.models.deletion.CASCADE, related_name='atividades_execucao', to='empresa.ordemservico')),
                ('parent', models.ForeignKey(blank=True, help_text='Actividade pai (vazio = actividade de primeiro nível)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subactividades', to='empresa.atividadeexecucao')),
                ('servicos_entregues', models.ManyToManyField(blank=True, help_text='Serviços do orçamento que esta actividade entrega (para parcelas e avisos ao financeiro)', related_name='atividades_que_entregam', to='empresa.servicoorcamentoservico')),
            ],
            options={
                'verbose_name': 'Actividade do plano de execução',
                'verbose_name_plural': 'Actividades do plano de execução',
                'ordering': ['ordem_servico', 'parent', 'numero_ordem'],
            },
        ),
    ]
