# Generated by Django 5.2.6 on 2026-02-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0229_atividadeexecucao_plano_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeexecucao',
            name='trabalho_empreitada',
            field=models.ForeignKey(blank=True, help_text='Trabalho de empreitada (RH) ligado a esta etapa; ao concluir a etapa, o trabalho é marcado concluído e gera aviso a Finanças', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_os', to='empresa.trabalhoempreitada'),
        ),
    ]
