# Generated by Django 5.2.6 on 2026-02-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0230_atividadeexecucao_trabalho_empreitada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadeexecucao',
            options={'ordering': ['ordem_servico', 'parent_id', 'numero_ordem'], 'verbose_name': 'Actividade do plano de execução', 'verbose_name_plural': 'Actividades do plano de execução'},
        ),
        migrations.AddField(
            model_name='atividadeexecucao',
            name='parcela',
            field=models.ForeignKey(blank=True, help_text='Parcela do contrato que fica exigível ao concluir esta etapa (liga etapa ao pagamento)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_que_liberam', to='empresa.parcelapagamentoorcamento'),
        ),
    ]
