# Generated by Django 5.2.6 on 2026-02-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0231_atividadeexecucao_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoempreitada',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, help_text='Preenchido pelo RH ao confirmar que o contrato foi assinado; notifica Finanças da conta a pagar (parcela à assinatura). O pagamento é confirmado em Finanças.', null=True, verbose_name='Data de confirmação da assinatura'),
        ),
    ]
