# Generated by Django 5.2.6 on 2026-02-19 07:15

import django.db.models.deletion
from django.db import migrations, models


def popular_atividade_execucao(apps, schema_editor):
    """Preenche atividade_execucao a partir de AtividadeExecucao.trabalho_empreitada."""
    TrabalhoEmpreitada = apps.get_model('empresa', 'TrabalhoEmpreitada')
    AtividadeExecucao = apps.get_model('empresa', 'AtividadeExecucao')
    for atv in AtividadeExecucao.objects.filter(trabalho_empreitada_id__isnull=False):
        TrabalhoEmpreitada.objects.filter(id=atv.trabalho_empreitada_id).update(atividade_execucao_id=atv.id)


def reverter_popular_atividade_execucao(apps, schema_editor):
    """Reverte: limpa atividade_execucao (o link reverso em AtividadeExecucao mantém-se)."""
    TrabalhoEmpreitada = apps.get_model('empresa', 'TrabalhoEmpreitada')
    TrabalhoEmpreitada.objects.filter(atividade_execucao__isnull=False).update(atividade_execucao=None)


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0232_add_data_assinatura_contrato_empreitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhoempreitada',
            name='atividade_execucao',
            field=models.ForeignKey(blank=True, help_text='Actividade planeada a que este trabalho está adjudicado. O limite de preço vem dos serviços entregues pela actividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos_empreitada', to='empresa.atividadeexecucao', verbose_name='Actividade do plano de trabalho'),
        ),
        migrations.AlterField(
            model_name='trabalhoempreitada',
            name='servico_orcamento',
            field=models.ForeignKey(blank=True, help_text='Mantido para compatibilidade. Preferir atividade_execucao; ordem e limite derivam do plano.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos_empreitada', to='empresa.servicoorcamentoservico', verbose_name='Serviço cotado (legado)'),
        ),
        migrations.RunPython(popular_atividade_execucao, reverter_popular_atividade_execucao),
    ]
