# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0233_add_atividade_execucao_trabalho_empreitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeexecucao',
            name='data_prevista_inicio',
            field=models.DateField(blank=True, help_text='Data prevista para início da actividade (opcional; usado no cronograma e para atrasos)', null=True),
        ),
    ]
