# Generated by Django 5.2.6 on 2026-02-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0219_add_proposta_tecnica_and_servico_levantamento'),
        ('empresa', '0234_atividadeexecucao_data_prevista_inicio'),
    ]

    operations = [
    ]
