# Generated by Django 5.2.6 on 2026-02-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0235_merge_20260225_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('HR', 'Hora'), ('DIA', 'Dia'), ('SEM', 'Semana'), ('MES', 'Mês'), ('PROJ', 'Projeto'), ('PISO', 'Piso'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('PC', 'Peça'), ('DZ', 'Dúzia'), ('GR', 'Grosa'), ('ROL', 'Rolo'), ('FOL', 'Folha'), ('BAR', 'Barra'), ('TUB', 'Tubo')], default='UN', help_text='Unidade de medida do item', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('HR', 'Hora'), ('DIA', 'Dia'), ('SEM', 'Semana'), ('MES', 'Mês'), ('PROJ', 'Projeto'), ('PISO', 'Piso'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('PC', 'Peça'), ('DZ', 'Dúzia'), ('GR', 'Grosa'), ('ROL', 'Rolo'), ('FOL', 'Folha'), ('BAR', 'Barra'), ('TUB', 'Tubo')], help_text='Unidade de medida', max_length=10),
        ),
    ]
