# Generated by Django 5.2.6 on 2026-03-06 19:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0239_create_taxa_servico_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propostatecnica',
            name='taxa_horaria_usada',
        ),
        migrations.AlterField(
            model_name='pendentecontapagar',
            name='origem_tipo',
            field=models.CharField(choices=[('RH_EMP_PARCELA', 'RH (empreitada parcela)'), ('RH_EMPREITADA', 'RH (empreitada)'), ('RH_TREINAMENTO', 'RH (treinamento)'), ('RH_FOLHA_SALARIAL', 'RH (folha salarial)'), ('COMPRAS', 'Compras'), ('LOGISTICA', 'Logística'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
        migrations.AlterField(
            model_name='pendentecontareceber',
            name='origem_tipo',
            field=models.CharField(choices=[('VENDAS_PARCELA', 'Vendas (parcela contrato)'), ('VENDAS_FATURA', 'Vendas (fatura)'), ('LOGISTICA', 'Logística (faturamento)'), ('PROPOSTA_TECNICA', 'Proposta técnica (adiantamento levantamento)'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
        migrations.AlterField(
            model_name='propostatecnica',
            name='estagio_atual',
            field=models.CharField(choices=[('AGENDADO', '0. Agendado'), ('LEVANTAMENTO', '1. Levantamento'), ('ANALISE_TECNICA', '2. Análise técnica'), ('ELABORACAO_PROPOSTA', '3. Elaboração da proposta'), ('APRESENTACAO', '4. Apresentação'), ('AJUSTES_FINAIS', '5. Ajustes finais'), ('APROVACAO', '6. Aprovação')], default='LEVANTAMENTO', help_text='Estágio atual do fluxo da proposta técnica', max_length=30),
        ),
        migrations.AlterField(
            model_name='taxaservicocategoria',
            name='categoria',
            field=models.CharField(choices=[('OP', 'Operacional - Ajudante'), ('ADM', 'Administrativo'), ('TEC', 'Técnico'), ('GES', 'Gestão'), ('EXE', 'Executivo')], help_text='Categoria profissional', max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='CampanhaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da campanha', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição e objetivos')),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PLANEADA', 'Planeada'), ('EM_CURSO', 'Em curso'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='RASCUNHO', max_length=20)),
                ('data_inicio', models.DateField(blank=True, help_text='Data de início prevista', null=True)),
                ('data_fim', models.DateField(blank=True, help_text='Data de fim prevista', null=True)),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Orçamento previsto (MT)', max_digits=12, null=True)),
                ('canal', models.CharField(blank=True, help_text='Canal principal (ex: Redes sociais, Email, Imprensa)', max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_marketing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha de Marketing',
                'verbose_name_plural': 'Campanhas de Marketing',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
