# Generated by Django 5.2.6 on 2026-03-06 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0240_add_campanha_marketing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestimentoPublicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(help_text='Ex: Facebook Ads, Google, Imprensa', max_length=100)),
                ('descricao', models.CharField(blank=True, help_text='Descrição do investimento', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor investido (MT)', max_digits=12)),
                ('data_investimento', models.DateField(help_text='Data do investimento')),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimentos', to='empresa.campanhamarketing')),
            ],
            options={
                'verbose_name': 'Investimento em Publicidade',
                'verbose_name_plural': 'Investimentos em Publicidade',
                'ordering': ['-data_investimento', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PublicacaoRedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(help_text='Ex: Facebook, Instagram, LinkedIn', max_length=80)),
                ('texto', models.TextField(help_text='Texto da publicação')),
                ('imagem_url', models.URLField(blank=True, help_text='URL da imagem (opcional)')),
                ('data_agendada', models.DateTimeField(blank=True, help_text='Data/hora de agendamento', null=True)),
                ('data_publicada', models.DateTimeField(blank=True, help_text='Data/hora em que foi publicada', null=True)),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGENDADA', 'Agendada'), ('PUBLICADA', 'Publicada'), ('CANCELADA', 'Cancelada')], db_index=True, default='RASCUNHO', max_length=20)),
                ('link_post', models.URLField(blank=True, help_text='Link do post após publicação')),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes', to='empresa.campanhamarketing')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_redes_sociais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicação em Rede Social',
                'verbose_name_plural': 'Publicações em Redes Sociais',
                'ordering': ['-data_agendada', '-data_criacao'],
            },
        ),
    ]
