from django.urls import path

from . import views_rh_presenca as views

urlpatterns = [
    path('presencas/', views.rh_presencas, name='presencas'),
    path('presencas/add/', views.rh_presenca_add, name='presenca_add'),
    path('presencas/<int:id>/', views.rh_presenca_detail, name='presenca_detail'),
    path('presencas/<int:id>/edit/', views.rh_presenca_edit, name='presenca_edit'),
    path('presencas/<int:id>/delete/', views.rh_presenca_delete, name='presenca_delete'),
    path('presencas/detalhes/<int:ano>/<int:mes>/', views.rh_detalhes_mes, name='detalhes_mes'),
    path('horas-extras/', views.rh_horas_extras_lista, name='horas_extras'),
    path('horas-extras/nova/', views.rh_horas_extras, name='horas_extras_nova'),
    path('horas-extras/lista/', views.rh_horas_extras_lista, name='horas_extras_lista'),
    path('horas-extras/<int:id>/editar/', views.rh_horas_extras_editar, name='horas_extras_editar'),
    path('horas-extras/<int:id>/excluir/', views.rh_horas_extras_excluir, name='horas_extras_excluir'),
    path('horas-extras/detectar-tipo/', views.rh_detectar_tipo_horas_extras, name='detectar_tipo_horas_extras'),
    path('horas-extras/calcular-mistas/', views.rh_calcular_horas_extras_mistas, name='calcular_horas_extras_mistas'),
    path('horas-extras/criar-mistas/', views.rh_criar_horas_extras_mistas, name='criar_horas_extras_mistas'),
    path('presencas/tipos/', views.rh_tipos_presenca, name='tipos_presenca'),
    path('presencas/tipos/add/', views.rh_tipo_presenca_add, name='tipo_presenca_add'),
    path('presencas/tipos/<int:id>/edit/', views.rh_tipo_presenca_edit, name='tipo_presenca_edit'),
    path('presencas/tipos/<int:id>/delete/', views.rh_tipo_presenca_delete, name='tipo_presenca_delete'),
    path('presencas/calendario/', views.rh_calendario_presencas, name='calendario_presencas'),
    path('presencas/calendario/debug/', views.rh_calendario_debug, name='calendario_debug'),
    path('presencas/calendario/teste/', views.rh_calendario_presencas, {'template_name': 'rh/presencas/calendario_teste.html'}, name='calendario_teste'),
    path('presencas/calendario/minimal/', views.rh_calendario_presencas, {'template_name': 'rh/presencas/calendario_minimal.html'}, name='calendario_minimal'),
    path('presencas/calendario/teste-navegacao/', views.rh_calendario_presencas, {'template_name': 'rh/presencas/calendario_teste_navegacao.html'}, name='calendario_teste_navegacao'),
    path('presencas/calendario/debug-navegacao/', views.rh_calendario_presencas, {'template_name': 'rh/presencas/calendario_debug_navegacao.html'}, name='calendario_debug_navegacao'),
    path('presencas/calendario/salvar/', views.rh_salvar_presenca_calendario, name='salvar_presenca_calendario'),
    path('presencas/calendario/remover/', views.rh_remover_presenca_calendario, name='remover_presenca_calendario'),
    path('presencas/calendario/marcar-dias-uteis/', views.rh_marcar_dias_uteis, name='marcar_dias_uteis'),
    path('presencas/calendario/marcar-finais-semana/', views.rh_marcar_finais_semana, name='marcar_finais_semana'),
    path('presencas/calendario/marcar-feriados/', views.rh_marcar_feriados_automaticos, name='marcar_feriados_automaticos'),
    path('presencas/calendario/marcar-finais-semana-automaticos/', views.rh_marcar_finais_semana_automaticos, name='marcar_finais_semana_automaticos'),
    path('feriados/', views.rh_feriados, name='feriados'),
    path('feriados/adicionar/', views.rh_feriado_add, name='feriado_add'),
    path('feriados/editar/<int:feriado_id>/', views.rh_feriado_edit, name='feriado_edit'),
    path('feriados/excluir/<int:feriado_id>/', views.rh_feriado_delete, name='feriado_delete'),
    path('horarios-expediente/', views.rh_horarios_expediente, name='horarios_expediente'),
    path('horarios-expediente/<int:sucursal_id>/', views.rh_horarios_expediente, name='horarios_expediente_sucursal'),
]
