from django.urls import path

from . import views_rh_desenvolvimento as views

urlpatterns = [
    path('treinamentos/', views.rh_treinamentos, name='treinamentos'),
    path('treinamentos/adicionar/', views.treinamento_add, name='treinamento_add'),
    path('treinamentos/editar/<int:treinamento_id>/', views.treinamento_edit, name='treinamento_edit'),
    path('treinamentos/detalhes/<int:treinamento_id>/', views.treinamento_detail, name='treinamento_detail'),
    path('treinamentos/deletar/<int:treinamento_id>/', views.treinamento_delete, name='treinamento_delete'),
    path('treinamentos/<int:treinamento_id>/inscrever/', views.treinamento_inscrever, name='treinamento_inscrever'),
    path('treinamentos/<int:treinamento_id>/inscricoes/', views.treinamento_inscricoes, name='treinamento_inscricoes'),
    path('inscricoes/<int:inscricao_id>/alterar-status/', views.inscricao_alterar_status, name='inscricao_alterar_status'),
    path('inscricoes/<int:inscricao_id>/avaliar/', views.inscricao_avaliar, name='inscricao_avaliar'),
    path('inscricoes/<int:inscricao_id>/deletar/', views.inscricao_deletar, name='inscricao_deletar'),
    path('avaliacoes/', views.rh_avaliacoes, name='avaliacoes'),
    path('avaliacoes/adicionar/', views.avaliacao_add, name='avaliacao_add'),
    path('avaliacoes/adicionar-lote/', views.avaliacao_add_batch, name='avaliacao_add_batch'),
    path('avaliacoes/editar/<int:avaliacao_id>/', views.avaliacao_edit, name='avaliacao_edit'),
    path('avaliacoes/detalhes/<int:avaliacao_id>/', views.avaliacao_detail, name='avaliacao_detail'),
    path('avaliacoes/iniciar/<int:avaliacao_id>/', views.avaliacao_iniciar, name='avaliacao_iniciar'),
    path('avaliacoes/concluir/<int:avaliacao_id>/', views.avaliacao_concluir, name='avaliacao_concluir'),
    path('avaliacoes/deletar/<int:avaliacao_id>/', views.avaliacao_delete, name='avaliacao_delete'),
    path('avaliacoes/imprimir/<int:avaliacao_id>/', views.avaliacao_print, name='avaliacao_print'),
    path('avaliacoes/visualizar/<int:avaliacao_id>/', views.avaliacao_print_html, name='avaliacao_print_html'),
    path('avaliacoes/criterios/', views.criterios, name='criterios'),
    path('avaliacoes/criterios/adicionar/', views.criterio_add, name='criterio_add'),
    path('avaliacoes/criterios/editar/<int:criterio_id>/', views.criterio_edit, name='criterio_edit'),
    path('avaliacoes/criterios/deletar/<int:criterio_id>/', views.criterio_delete, name='criterio_delete'),
    path('promocoes/', views.rh_promocoes, name='promocoes'),
    path('promocoes/adicionar/', views.rh_promocao_add, name='promocao_add'),
    path('promocoes/detalhes/<int:promocao_id>/', views.rh_promocao_detail, name='promocao_detail'),
    path('promocoes/editar/<int:promocao_id>/', views.rh_promocao_edit, name='promocao_edit'),
    path('promocoes/deletar/<int:promocao_id>/', views.rh_promocao_delete, name='promocao_delete'),
    path('promocoes/aprovar/<int:promocao_id>/', views.rh_promocao_aprovar, name='promocao_aprovar'),
    path('promocoes/rejeitar/<int:promocao_id>/', views.rh_promocao_rejeitar, name='promocao_rejeitar'),
    path('promocoes/implementar/<int:promocao_id>/', views.rh_promocao_implementar, name='promocao_implementar'),
    path('promocoes/relatorio/', views.rh_promocoes_relatorio, name='promocoes_relatorio'),
    path('transferencias/', views.rh_transferencias, name='transferencias'),
    path('transferencias/adicionar/', views.rh_transferencia_add, name='transferencia_add'),
    path('transferencias/detalhes/<int:transferencia_id>/', views.rh_transferencia_detail, name='transferencia_detail'),
    path('transferencias/editar/<int:transferencia_id>/', views.rh_transferencia_edit, name='transferencia_edit'),
    path('transferencias/deletar/<int:transferencia_id>/', views.rh_transferencia_delete, name='transferencia_delete'),
    path('transferencias/aprovar/<int:transferencia_id>/', views.rh_transferencia_aprovar, name='transferencia_aprovar'),
    path('transferencias/rejeitar/<int:transferencia_id>/', views.rh_transferencia_rejeitar, name='transferencia_rejeitar'),
    path('transferencias/implementar/<int:transferencia_id>/', views.rh_transferencia_implementar, name='transferencia_implementar'),
    path('transferencias/efetivar/<int:transferencia_id>/', views.rh_transferencia_efetivar, name='transferencia_efetivar'),
    path('transferencias/relatorio/', views.rh_transferencias_relatorio, name='transferencias_relatorio'),
]
