name: Python application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install coverage

      - name: Django check
        run: |
          python manage.py check

      - name: Run tests with coverage
        run: |
          coverage run --source=meuprojeto -m django test -v 2
          coverage xml -o coverage.xml

      - name: Report coverage to GitHub Summary
        run: |
          python - << 'PY'
          import os
          import xml.etree.ElementTree as ET
          tree = ET.parse('coverage.xml')
          root = tree.getroot()
          line_rate = root.get('line-rate')
          pct = float(line_rate) * 100 if line_rate is not None else 0.0
          summary_path = os.environ.get('GITHUB_STEP_SUMMARY')
          if summary_path:
              with open(summary_path, 'a', encoding='utf-8') as f:
                  f.write(f"## Test Coverage\n\n{pct:.2f}%\n")
          else:
              print(f"Coverage: {pct:.2f}%")
          PY

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml


